// Copyright 2026 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by zkeycodes from QMK hjson keycode files
const zkc_core = @import("../src/core.zig");
const core = @import("zigmkay").core;
const L_SFT = zkc_core.L_SFT;
const L_ALT = zkc_core.L_ALT;
const R_ALT = zkc_core.R_ALT;
const R_CTL = zkc_core.R_CTL;
const DEAD = zkc_core.DEAD;
pub const keycodes = @import("keycodes.zig");

pub const QMK_BELGIAN_KEYCODES_VERSION = "0.0.1";
pub const QMK_BELGIAN_KEYCODES_VERSION_BCD = @as(c_int, 0x00000001);
pub const QMK_BELGIAN_KEYCODES_VERSION_MAJOR = @as(c_int, 0);
pub const QMK_BELGIAN_KEYCODES_VERSION_MINOR = @as(c_int, 0);
pub const QMK_BELGIAN_KEYCODES_VERSION_PATCH = @as(c_int, 1);

//
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ² │ & │ é │ " │ ' │ ( │ § │ è │ ! │ ç │ à │ ) │ - │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ A │ Z │ E │ R │ T │ Y │ U │ I │ O │ P │ ^ │ $ │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │ Q │ S │ D │ F │ G │ H │ J │ K │ L │ M │ ù │ µ │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ < │ W │ X │ C │ V │ B │ N │ , │ ; │ : │ = │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ²
pub const SUP2 = keycodes.kcf.GRV;
/// &
pub const AMPR = keycodes.kcf.N1;
/// é
pub const EACU = keycodes.kcf.N2;
/// "
pub const DQUO = keycodes.kcf.N3;
/// '
pub const QUOT = keycodes.kcf.N4;
/// (
pub const LPRN = keycodes.kcf.N5;
/// §
pub const SECT = keycodes.kcf.N6;
/// è
pub const EGRV = keycodes.kcf.N7;
/// !
pub const EXLM = keycodes.kcf.N8;
/// ç
pub const CCED = keycodes.kcf.N9;
/// à
pub const AGRV = keycodes.kcf.N0;
/// )
pub const RPRN = keycodes.kcf.MINS;
/// -
pub const MINS = keycodes.kcf.EQL;
/// A
pub const A = keycodes.kcf.Q;
/// Z
pub const Z = keycodes.kcf.W;
/// E
pub const E = keycodes.kcf.E;
/// R
pub const R = keycodes.kcf.R;
/// T
pub const T = keycodes.kcf.T;
/// Y
pub const Y = keycodes.kcf.Y;
/// U
pub const U = keycodes.kcf.U;
/// I
pub const I = keycodes.kcf.I;
/// O
pub const O = keycodes.kcf.O;
/// P
pub const P = keycodes.kcf.P;
/// ^ (dead)
pub const DCIR = DEAD(keycodes.kcf.LBRC);
/// $
pub const DLR = keycodes.kcf.RBRC;
/// Q
pub const Q = keycodes.kcf.A;
/// S
pub const S = keycodes.kcf.S;
/// D
pub const D = keycodes.kcf.D;
/// F
pub const F = keycodes.kcf.F;
/// G
pub const G = keycodes.kcf.G;
/// H
pub const H = keycodes.kcf.H;
/// J
pub const J = keycodes.kcf.J;
/// K
pub const K = keycodes.kcf.K;
/// L
pub const L = keycodes.kcf.L;
/// M
pub const M = keycodes.kcf.SCLN;
/// ù
pub const UGRV = keycodes.kcf.QUOT;
/// µ
pub const MICR = keycodes.kcf.NUHS;
/// <
pub const LABK = keycodes.kcf.NUBS;
/// W
pub const W = keycodes.kcf.Z;
/// X
pub const X = keycodes.kcf.X;
/// C
pub const C = keycodes.kcf.C;
/// V
pub const V = keycodes.kcf.V;
/// B
pub const B = keycodes.kcf.B;
/// N
pub const N = keycodes.kcf.N;
/// ,
pub const COMM = keycodes.kcf.M;
/// ;
pub const SCLN = keycodes.kcf.COMM;
/// :
pub const COLN = keycodes.kcf.DOT;
/// =
pub const EQL = keycodes.kcf.SLSH;
// Shifted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ³ │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ ° │ _ │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │   │   │   │   │   │   │   │   │ ¨ │ * │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │   │   │   │   │   │   │   │   │   │   │ % │ £ │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ > │   │   │   │   │   │   │ ? │ . │ / │ + │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ³
pub const SUP3 = L_SFT(SUP2);
/// 1
pub const N1 = L_SFT(AMPR);
/// 2
pub const N2 = L_SFT(EACU);
/// 3
pub const N3 = L_SFT(DQUO);
/// 4
pub const N4 = L_SFT(QUOT);
/// 5
pub const N5 = L_SFT(LPRN);
/// 6
pub const N6 = L_SFT(SECT);
/// 7
pub const N7 = L_SFT(EGRV);
/// 8
pub const N8 = L_SFT(EXLM);
/// 9
pub const N9 = L_SFT(CCED);
/// 0
pub const N0 = L_SFT(AGRV);
/// °
pub const DEG = L_SFT(RPRN);
/// _
pub const UNDS = L_SFT(MINS);
/// ¨ (dead)
pub const DIAE = DEAD(L_SFT(DCIR));
/// *
pub const ASTR = L_SFT(DLR);
/// %
pub const PERC = L_SFT(UGRV);
/// £
pub const PND = L_SFT(MICR);
/// >
pub const RABK = L_SFT(LABK);
/// ?
pub const QUES = L_SFT(COMM);
/// .
pub const DOT = L_SFT(SCLN);
/// /
pub const SLSH = L_SFT(COLN);
/// +
pub const PLUS = L_SFT(EQL);
// AltGr symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │   │ | │ @ │ # │   │   │ ^ │   │   │ { │ } │   │   │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │ € │   │   │   │   │   │   │   │ [ │ ] │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │   │   │   │   │   │   │   │   │   │   │ ´ │ ` │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ \ │   │   │   │   │   │   │   │   │   │ ~ │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// |
pub const PIPE = R_ALT(AMPR);
/// @
pub const AT = R_ALT(EACU);
/// #
pub const HASH = R_ALT(DQUO);
/// ^
pub const CIRC = R_ALT(SECT);
/// {
pub const LCBR = R_ALT(CCED);
/// }
pub const RCBR = R_ALT(AGRV);
/// €
pub const EURO = R_ALT(E);
/// [
pub const LBRC = R_ALT(DCIR);
/// ]
pub const RBRC = R_ALT(DLR);
/// ´ (dead)
pub const ACUT = DEAD(R_ALT(UGRV));
/// ` (dead)
pub const GRV = DEAD(R_ALT(MICR));
/// (backslash)
pub const BSLS = R_ALT(LABK);
/// ~
pub const TILD = R_ALT(EQL);

// Label lookup table
pub const _labels = [_]zkc_core.LabelEntry{
    .{ .value = SUP2, .label = "SUP2", .short_label = "SUP2" },
    .{ .value = AMPR, .label = "AMPR", .short_label = "AMPR" },
    .{ .value = EACU, .label = "EACU", .short_label = "EACU" },
    .{ .value = DQUO, .label = "DQUO", .short_label = "DQUO" },
    .{ .value = QUOT, .label = "QUOT", .short_label = "QUOT" },
    .{ .value = LPRN, .label = "LPRN", .short_label = "LPRN" },
    .{ .value = SECT, .label = "SECT", .short_label = "SECT" },
    .{ .value = EGRV, .label = "EGRV", .short_label = "EGRV" },
    .{ .value = EXLM, .label = "EXLM", .short_label = "EXLM" },
    .{ .value = CCED, .label = "CCED", .short_label = "CCED" },
    .{ .value = AGRV, .label = "AGRV", .short_label = "AGRV" },
    .{ .value = RPRN, .label = "RPRN", .short_label = "RPRN" },
    .{ .value = MINS, .label = "MINS", .short_label = "MINS" },
    .{ .value = A, .label = "A", .short_label = "A" },
    .{ .value = Z, .label = "Z", .short_label = "Z" },
    .{ .value = E, .label = "E", .short_label = "E" },
    .{ .value = R, .label = "R", .short_label = "R" },
    .{ .value = T, .label = "T", .short_label = "T" },
    .{ .value = Y, .label = "Y", .short_label = "Y" },
    .{ .value = U, .label = "U", .short_label = "U" },
    .{ .value = I, .label = "I", .short_label = "I" },
    .{ .value = O, .label = "O", .short_label = "O" },
    .{ .value = P, .label = "P", .short_label = "P" },
    .{ .value = DCIR, .label = "DCIR", .short_label = "DCIR" },
    .{ .value = DLR, .label = "DLR", .short_label = "DLR" },
    .{ .value = Q, .label = "Q", .short_label = "Q" },
    .{ .value = S, .label = "S", .short_label = "S" },
    .{ .value = D, .label = "D", .short_label = "D" },
    .{ .value = F, .label = "F", .short_label = "F" },
    .{ .value = G, .label = "G", .short_label = "G" },
    .{ .value = H, .label = "H", .short_label = "H" },
    .{ .value = J, .label = "J", .short_label = "J" },
    .{ .value = K, .label = "K", .short_label = "K" },
    .{ .value = L, .label = "L", .short_label = "L" },
    .{ .value = M, .label = "M", .short_label = "M" },
    .{ .value = UGRV, .label = "UGRV", .short_label = "UGRV" },
    .{ .value = MICR, .label = "MICR", .short_label = "MICR" },
    .{ .value = LABK, .label = "LABK", .short_label = "LABK" },
    .{ .value = W, .label = "W", .short_label = "W" },
    .{ .value = X, .label = "X", .short_label = "X" },
    .{ .value = C, .label = "C", .short_label = "C" },
    .{ .value = V, .label = "V", .short_label = "V" },
    .{ .value = B, .label = "B", .short_label = "B" },
    .{ .value = N, .label = "N", .short_label = "N" },
    .{ .value = COMM, .label = "COMM", .short_label = "COMM" },
    .{ .value = SCLN, .label = "SCLN", .short_label = "SCLN" },
    .{ .value = COLN, .label = "COLN", .short_label = "COLN" },
    .{ .value = EQL, .label = "EQL", .short_label = "EQL" },
    .{ .value = SUP3, .label = "SUP3", .short_label = "SUP3" },
    .{ .value = N1, .label = "1", .short_label = "1" },
    .{ .value = N2, .label = "2", .short_label = "2" },
    .{ .value = N3, .label = "3", .short_label = "3" },
    .{ .value = N4, .label = "4", .short_label = "4" },
    .{ .value = N5, .label = "5", .short_label = "5" },
    .{ .value = N6, .label = "6", .short_label = "6" },
    .{ .value = N7, .label = "7", .short_label = "7" },
    .{ .value = N8, .label = "8", .short_label = "8" },
    .{ .value = N9, .label = "9", .short_label = "9" },
    .{ .value = N0, .label = "0", .short_label = "0" },
    .{ .value = DEG, .label = "DEG", .short_label = "DEG" },
    .{ .value = UNDS, .label = "UNDS", .short_label = "UNDS" },
    .{ .value = DIAE, .label = "DIAE", .short_label = "DIAE" },
    .{ .value = ASTR, .label = "ASTR", .short_label = "ASTR" },
    .{ .value = PERC, .label = "PERC", .short_label = "PERC" },
    .{ .value = PND, .label = "PND", .short_label = "PND" },
    .{ .value = RABK, .label = "RABK", .short_label = "RABK" },
    .{ .value = QUES, .label = "QUES", .short_label = "QUES" },
    .{ .value = DOT, .label = "DOT", .short_label = "DOT" },
    .{ .value = SLSH, .label = "SLSH", .short_label = "SLSH" },
    .{ .value = PLUS, .label = "PLUS", .short_label = "PLUS" },
    .{ .value = PIPE, .label = "PIPE", .short_label = "PIPE" },
    .{ .value = AT, .label = "AT", .short_label = "AT" },
    .{ .value = HASH, .label = "HASH", .short_label = "HASH" },
    .{ .value = CIRC, .label = "CIRC", .short_label = "CIRC" },
    .{ .value = LCBR, .label = "LCBR", .short_label = "LCBR" },
    .{ .value = RCBR, .label = "RCBR", .short_label = "RCBR" },
    .{ .value = EURO, .label = "EURO", .short_label = "EURO" },
    .{ .value = LBRC, .label = "LBRC", .short_label = "LBRC" },
    .{ .value = RBRC, .label = "RBRC", .short_label = "RBRC" },
    .{ .value = ACUT, .label = "ACUT", .short_label = "ACUT" },
    .{ .value = GRV, .label = "GRV", .short_label = "GRV" },
    .{ .value = BSLS, .label = "BSLS", .short_label = "BSLS" },
    .{ .value = TILD, .label = "TILD", .short_label = "TILD" },
};

pub fn getLabel(keycode: core.KeyCodeFire, shortest: bool) ?[]const u8 {
    return zkc_core.getLabel(&_labels, keycode, shortest);
}
