// Copyright 2026 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by zkeycodes from QMK hjson keycode files
const zkc_core = @import("../src/core.zig");
const core = @import("zigmkay").core;
const L_SFT = zkc_core.L_SFT;
const L_ALT = zkc_core.L_ALT;
const R_ALT = zkc_core.R_ALT;
const R_CTL = zkc_core.R_CTL;
const DEAD = zkc_core.DEAD;
pub const keycodes = @import("keycodes.zig");

pub const QMK_BEPO_KEYCODES_VERSION = "0.0.1";
pub const QMK_BEPO_KEYCODES_VERSION_BCD = @as(c_int, 0x00000001);
pub const QMK_BEPO_KEYCODES_VERSION_MAJOR = @as(c_int, 0);
pub const QMK_BEPO_KEYCODES_VERSION_MINOR = @as(c_int, 0);
pub const QMK_BEPO_KEYCODES_VERSION_PATCH = @as(c_int, 1);

//
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ $ │ " │ « │ » │ ( │ ) │ @ │ + │ - │ / │ * │ = │ % │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ B │ É │ P │ O │ È │ ^ │ V │ D │ L │ J │ Z │ W │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │ A │ U │ I │ E │ , │ C │ T │ S │ R │ N │ M │ Ç │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ Ê │ À │ Y │ X │ . │ K │ ' │ Q │ G │ H │ F │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// $
pub const DLR = keycodes.kcf.GRV;
/// "
pub const DQUO = keycodes.kcf.N1;
/// «
pub const LDAQ = keycodes.kcf.N2;
/// »
pub const RDAQ = keycodes.kcf.N3;
/// (
pub const LPRN = keycodes.kcf.N4;
/// )
pub const RPRN = keycodes.kcf.N5;
/// @
pub const AT = keycodes.kcf.N6;
/// +
pub const PLUS = keycodes.kcf.N7;
/// -
pub const MINS = keycodes.kcf.N8;
/// /
pub const SLSH = keycodes.kcf.N9;
/// *
pub const ASTR = keycodes.kcf.N0;
/// =
pub const EQL = keycodes.kcf.MINS;
/// %
pub const PERC = keycodes.kcf.EQL;
/// B
pub const B = keycodes.kcf.Q;
/// É
pub const EACU = keycodes.kcf.W;
/// P
pub const P = keycodes.kcf.E;
/// O
pub const O = keycodes.kcf.R;
/// È
pub const EGRV = keycodes.kcf.T;
/// ^ (dead)
pub const DCIR = DEAD(keycodes.kcf.Y);
/// V
pub const V = keycodes.kcf.U;
/// D
pub const D = keycodes.kcf.I;
/// L
pub const L = keycodes.kcf.O;
/// J
pub const J = keycodes.kcf.P;
/// Z
pub const Z = keycodes.kcf.LBRC;
/// W
pub const W = keycodes.kcf.RBRC;
/// A
pub const A = keycodes.kcf.A;
/// U
pub const U = keycodes.kcf.S;
/// I
pub const I = keycodes.kcf.D;
/// E
pub const E = keycodes.kcf.F;
/// ,
pub const COMM = keycodes.kcf.G;
/// C
pub const C = keycodes.kcf.H;
/// T
pub const T = keycodes.kcf.J;
/// S
pub const S = keycodes.kcf.K;
/// R
pub const R = keycodes.kcf.L;
/// N
pub const N = keycodes.kcf.SCLN;
/// M
pub const M = keycodes.kcf.QUOT;
/// Ç
pub const CCED = keycodes.kcf.BSLS;
/// Ê
pub const ECIR = keycodes.kcf.NUBS;
/// À
pub const AGRV = keycodes.kcf.Z;
/// Y
pub const Y = keycodes.kcf.X;
/// X
pub const X = keycodes.kcf.C;
/// .
pub const DOT = keycodes.kcf.V;
/// K
pub const K = keycodes.kcf.B;
/// '
pub const QUOT = keycodes.kcf.N;
/// Q
pub const Q = keycodes.kcf.M;
/// G
pub const G = keycodes.kcf.COMM;
/// H
pub const H = keycodes.kcf.DOT;
/// F
pub const F = keycodes.kcf.SLSH;
// Shifted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ # │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ ° │ ` │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │   │   │   │ ! │   │   │   │   │   │   │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │   │   │   │   │ ; │   │   │   │   │   │   │   │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │   │   │   │   │ : │   │ ? │   │   │   │   │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// #
pub const HASH = L_SFT(DLR);
/// 1
pub const N1 = L_SFT(DQUO);
/// 2
pub const N2 = L_SFT(LDAQ);
/// 3
pub const N3 = L_SFT(RDAQ);
/// 4
pub const N4 = L_SFT(LPRN);
/// 5
pub const N5 = L_SFT(RPRN);
/// 6
pub const N6 = L_SFT(AT);
/// 7
pub const N7 = L_SFT(PLUS);
/// 8
pub const N8 = L_SFT(MINS);
/// 9
pub const N9 = L_SFT(SLSH);
/// 0
pub const N0 = L_SFT(ASTR);
/// °
pub const DEG = L_SFT(EQL);
/// `
pub const GRV = L_SFT(PERC);
/// !
pub const EXLM = L_SFT(DCIR);
/// ;
pub const SCLN = L_SFT(COMM);
/// :
pub const COLN = L_SFT(DOT);
/// ?
pub const QUES = L_SFT(QUOT);
/// (non-breaking space)
pub const NBSP = L_SFT(keycodes.kcf.SPC);
// AltGr symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ – │ — │ < │ > │ [ │ ] │ ^ │ ± │ − │ ÷ │ × │ ≠ │ ‰ │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ | │ ´ │ & │ Œ │ ` │ ¡ │ ˇ │ Ð │ / │ Ĳ │ Ə │ ˘ │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │ Æ │ Ù │ ¨ │ € │   │ © │ Þ │ ẞ │ ® │ ~ │ ¯ │ ¸ │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │   │ \ │ { │ } │ … │ ~ │ ¿ │ ° │   │ † │ ˛ │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │           _            │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// –
pub const NDSH = R_ALT(DLR);
/// —
pub const MDSH = R_ALT(DQUO);
/// <
pub const LABK = R_ALT(LDAQ);
/// >
pub const RABK = R_ALT(RDAQ);
/// [
pub const LBRC = R_ALT(LPRN);
/// ]
pub const RBRC = R_ALT(RPRN);
/// ^
pub const CIRC = R_ALT(AT);
/// ±
pub const PLMN = R_ALT(PLUS);
/// −
pub const MMNS = R_ALT(MINS);
/// ÷
pub const DIV = R_ALT(SLSH);
/// ×
pub const MUL = R_ALT(ASTR);
/// ≠
pub const NEQL = R_ALT(EQL);
/// ‰
pub const PERM = R_ALT(PERC);
/// |
pub const PIPE = R_ALT(B);
/// ´ (dead)
pub const ACUT = DEAD(R_ALT(EACU));
/// &
pub const AMPR = R_ALT(P);
/// Œ
pub const OE = R_ALT(O);
/// ` (dead)
pub const DGRV = DEAD(R_ALT(EGRV));
/// ¡
pub const IEXL = R_ALT(DCIR);
/// ˇ (dead)
pub const CARN = DEAD(R_ALT(V));
/// Ð
pub const ETH = R_ALT(D);
/// / (dead)
pub const DSLS = DEAD(R_ALT(L));
/// Ĳ
pub const IJ = R_ALT(J);
/// Ə
pub const SCHW = R_ALT(Z);
/// ˘ (dead)
pub const BREV = DEAD(R_ALT(W));
/// Æ
pub const AE = R_ALT(A);
/// Ù
pub const UGRV = R_ALT(U);
/// ¨ (dead)
pub const DIAE = DEAD(R_ALT(I));
/// €
pub const EURO = R_ALT(E);
/// ©
pub const COPY = R_ALT(C);
/// Þ
pub const THRN = R_ALT(T);
/// ẞ
pub const SS = R_ALT(S);
/// ®
pub const REGD = R_ALT(R);
/// ~ (dead)
pub const DTIL = DEAD(R_ALT(N));
/// ¯ (dead)
pub const MACR = DEAD(R_ALT(M));
/// ¸ (dead)
pub const CEDL = DEAD(R_ALT(CCED));
/// (backslash)
pub const BSLS = R_ALT(AGRV);
/// {
pub const LCBR = R_ALT(Y);
/// }
pub const RCBR = R_ALT(X);
/// …
pub const ELLP = R_ALT(DOT);
/// ~
pub const TILD = R_ALT(K);
/// ¿
pub const IQUE = R_ALT(QUES);
/// ° (dead)
pub const RNGA = DEAD(R_ALT(Q));
/// µ (dead Greek key)
pub const DGRK = R_ALT(G);
/// †
pub const DAGG = R_ALT(H);
/// ˛ (dead)
pub const OGON = DEAD(R_ALT(F));
/// _
pub const UNDS = R_ALT(keycodes.kcf.SPC);
// Shift+AltGr symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ¶ │ „ │ “ │ ” │ ≤ │ ≥ │   │ ¬ │ ¼ │ ½ │ ¾ │ ′ │ ″ │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ ¦ │ ˝ │ § │   │   │   │   │   │   │   │   │   │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │   │   │ ˙ │ ¤ │ ̛  │ ſ │   │   │ ™ │   │ º │ , │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │   │   │ ‘ │ ’ │ · │ ⌨ │ ̉  │ ̣  │   │ ‡ │ ª │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ¶
pub const PARA = L_SFT(R_ALT(DLR));
/// „
pub const DLQU = L_SFT(R_ALT(DQUO));
/// “
pub const LDQU = L_SFT(R_ALT(LDAQ));
/// ”
pub const RDQU = L_SFT(R_ALT(RDAQ));
/// ≤
pub const LEQL = L_SFT(R_ALT(LPRN));
/// ≥
pub const GEQL = L_SFT(R_ALT(RPRN));
/// ¬
pub const NOT = L_SFT(R_ALT(PLUS));
/// ¼
pub const QRTR = L_SFT(R_ALT(MINS));
/// ½
pub const HALF = L_SFT(R_ALT(SLSH));
/// ¾
pub const TQTR = L_SFT(R_ALT(ASTR));
/// ′
pub const PRIM = L_SFT(R_ALT(EQL));
/// ″
pub const DPRM = L_SFT(R_ALT(PERC));
/// ¦
pub const BRKP = L_SFT(R_ALT(B));
/// ˝ (dead)
pub const DACU = DEAD(L_SFT(R_ALT(EACU)));
/// §
pub const SECT = L_SFT(R_ALT(P));
/// ˙ (dead)
pub const DOTA = DEAD(L_SFT(R_ALT(I)));
/// ¤ (dead)
pub const CURR = DEAD(L_SFT(R_ALT(E)));
/// ̛ (dead)
pub const HORN = DEAD(L_SFT(R_ALT(COMM)));
/// ſ
pub const LNGS = L_SFT(R_ALT(C));
/// ™
pub const TM = L_SFT(R_ALT(R));
/// º
pub const MORD = L_SFT(R_ALT(M));
/// , (dead)
pub const DCMM = DEAD(L_SFT(R_ALT(CCED)));
/// ‘
pub const LSQU = L_SFT(R_ALT(Y));
/// ’
pub const RSQU = L_SFT(R_ALT(X));
/// ·
pub const MDDT = L_SFT(R_ALT(DOT));
/// ⌨
pub const KEYB = L_SFT(R_ALT(K));
/// ̉ (dead)
pub const HOKA = DEAD(L_SFT(R_ALT(QUOT)));
/// ̣ (dead)
pub const DOTB = DEAD(L_SFT(R_ALT(Q)));
/// ‡
pub const DDAG = L_SFT(R_ALT(H));
/// ª
pub const FORD = L_SFT(R_ALT(F));
/// (narrow non-breaking space)
pub const NNBS = L_SFT(R_ALT(keycodes.kcf.SPC));

// Label lookup table
pub const _labels = [_]zkc_core.LabelEntry{
    .{ .value = DLR, .label = "DLR", .short_label = "DLR" },
    .{ .value = DQUO, .label = "DQUO", .short_label = "DQUO" },
    .{ .value = LDAQ, .label = "LDAQ", .short_label = "LDAQ" },
    .{ .value = RDAQ, .label = "RDAQ", .short_label = "RDAQ" },
    .{ .value = LPRN, .label = "LPRN", .short_label = "LPRN" },
    .{ .value = RPRN, .label = "RPRN", .short_label = "RPRN" },
    .{ .value = AT, .label = "AT", .short_label = "AT" },
    .{ .value = PLUS, .label = "PLUS", .short_label = "PLUS" },
    .{ .value = MINS, .label = "MINS", .short_label = "MINS" },
    .{ .value = SLSH, .label = "SLSH", .short_label = "SLSH" },
    .{ .value = ASTR, .label = "ASTR", .short_label = "ASTR" },
    .{ .value = EQL, .label = "EQL", .short_label = "EQL" },
    .{ .value = PERC, .label = "PERC", .short_label = "PERC" },
    .{ .value = B, .label = "B", .short_label = "B" },
    .{ .value = EACU, .label = "EACU", .short_label = "EACU" },
    .{ .value = P, .label = "P", .short_label = "P" },
    .{ .value = O, .label = "O", .short_label = "O" },
    .{ .value = EGRV, .label = "EGRV", .short_label = "EGRV" },
    .{ .value = DCIR, .label = "DCIR", .short_label = "DCIR" },
    .{ .value = V, .label = "V", .short_label = "V" },
    .{ .value = D, .label = "D", .short_label = "D" },
    .{ .value = L, .label = "L", .short_label = "L" },
    .{ .value = J, .label = "J", .short_label = "J" },
    .{ .value = Z, .label = "Z", .short_label = "Z" },
    .{ .value = W, .label = "W", .short_label = "W" },
    .{ .value = A, .label = "A", .short_label = "A" },
    .{ .value = U, .label = "U", .short_label = "U" },
    .{ .value = I, .label = "I", .short_label = "I" },
    .{ .value = E, .label = "E", .short_label = "E" },
    .{ .value = COMM, .label = "COMM", .short_label = "COMM" },
    .{ .value = C, .label = "C", .short_label = "C" },
    .{ .value = T, .label = "T", .short_label = "T" },
    .{ .value = S, .label = "S", .short_label = "S" },
    .{ .value = R, .label = "R", .short_label = "R" },
    .{ .value = N, .label = "N", .short_label = "N" },
    .{ .value = M, .label = "M", .short_label = "M" },
    .{ .value = CCED, .label = "CCED", .short_label = "CCED" },
    .{ .value = ECIR, .label = "ECIR", .short_label = "ECIR" },
    .{ .value = AGRV, .label = "AGRV", .short_label = "AGRV" },
    .{ .value = Y, .label = "Y", .short_label = "Y" },
    .{ .value = X, .label = "X", .short_label = "X" },
    .{ .value = DOT, .label = "DOT", .short_label = "DOT" },
    .{ .value = K, .label = "K", .short_label = "K" },
    .{ .value = QUOT, .label = "QUOT", .short_label = "QUOT" },
    .{ .value = Q, .label = "Q", .short_label = "Q" },
    .{ .value = G, .label = "G", .short_label = "G" },
    .{ .value = H, .label = "H", .short_label = "H" },
    .{ .value = F, .label = "F", .short_label = "F" },
    .{ .value = HASH, .label = "HASH", .short_label = "HASH" },
    .{ .value = N1, .label = "1", .short_label = "1" },
    .{ .value = N2, .label = "2", .short_label = "2" },
    .{ .value = N3, .label = "3", .short_label = "3" },
    .{ .value = N4, .label = "4", .short_label = "4" },
    .{ .value = N5, .label = "5", .short_label = "5" },
    .{ .value = N6, .label = "6", .short_label = "6" },
    .{ .value = N7, .label = "7", .short_label = "7" },
    .{ .value = N8, .label = "8", .short_label = "8" },
    .{ .value = N9, .label = "9", .short_label = "9" },
    .{ .value = N0, .label = "0", .short_label = "0" },
    .{ .value = DEG, .label = "DEG", .short_label = "DEG" },
    .{ .value = GRV, .label = "GRV", .short_label = "GRV" },
    .{ .value = EXLM, .label = "EXLM", .short_label = "EXLM" },
    .{ .value = SCLN, .label = "SCLN", .short_label = "SCLN" },
    .{ .value = COLN, .label = "COLN", .short_label = "COLN" },
    .{ .value = QUES, .label = "QUES", .short_label = "QUES" },
    .{ .value = NBSP, .label = "NBSP", .short_label = "NBSP" },
    .{ .value = NDSH, .label = "NDSH", .short_label = "NDSH" },
    .{ .value = MDSH, .label = "MDSH", .short_label = "MDSH" },
    .{ .value = LABK, .label = "LABK", .short_label = "LABK" },
    .{ .value = RABK, .label = "RABK", .short_label = "RABK" },
    .{ .value = LBRC, .label = "LBRC", .short_label = "LBRC" },
    .{ .value = RBRC, .label = "RBRC", .short_label = "RBRC" },
    .{ .value = CIRC, .label = "CIRC", .short_label = "CIRC" },
    .{ .value = PLMN, .label = "PLMN", .short_label = "PLMN" },
    .{ .value = MMNS, .label = "MMNS", .short_label = "MMNS" },
    .{ .value = DIV, .label = "DIV", .short_label = "DIV" },
    .{ .value = MUL, .label = "MUL", .short_label = "MUL" },
    .{ .value = NEQL, .label = "NEQL", .short_label = "NEQL" },
    .{ .value = PERM, .label = "PERM", .short_label = "PERM" },
    .{ .value = PIPE, .label = "PIPE", .short_label = "PIPE" },
    .{ .value = ACUT, .label = "ACUT", .short_label = "ACUT" },
    .{ .value = AMPR, .label = "AMPR", .short_label = "AMPR" },
    .{ .value = OE, .label = "OE", .short_label = "OE" },
    .{ .value = DGRV, .label = "DGRV", .short_label = "DGRV" },
    .{ .value = IEXL, .label = "IEXL", .short_label = "IEXL" },
    .{ .value = CARN, .label = "CARN", .short_label = "CARN" },
    .{ .value = ETH, .label = "ETH", .short_label = "ETH" },
    .{ .value = DSLS, .label = "DSLS", .short_label = "DSLS" },
    .{ .value = IJ, .label = "IJ", .short_label = "IJ" },
    .{ .value = SCHW, .label = "SCHW", .short_label = "SCHW" },
    .{ .value = BREV, .label = "BREV", .short_label = "BREV" },
    .{ .value = AE, .label = "AE", .short_label = "AE" },
    .{ .value = UGRV, .label = "UGRV", .short_label = "UGRV" },
    .{ .value = DIAE, .label = "DIAE", .short_label = "DIAE" },
    .{ .value = EURO, .label = "EURO", .short_label = "EURO" },
    .{ .value = COPY, .label = "COPY", .short_label = "COPY" },
    .{ .value = THRN, .label = "THRN", .short_label = "THRN" },
    .{ .value = SS, .label = "SS", .short_label = "SS" },
    .{ .value = REGD, .label = "REGD", .short_label = "REGD" },
    .{ .value = DTIL, .label = "DTIL", .short_label = "DTIL" },
    .{ .value = MACR, .label = "MACR", .short_label = "MACR" },
    .{ .value = CEDL, .label = "CEDL", .short_label = "CEDL" },
    .{ .value = BSLS, .label = "BSLS", .short_label = "BSLS" },
    .{ .value = LCBR, .label = "LCBR", .short_label = "LCBR" },
    .{ .value = RCBR, .label = "RCBR", .short_label = "RCBR" },
    .{ .value = ELLP, .label = "ELLP", .short_label = "ELLP" },
    .{ .value = TILD, .label = "TILD", .short_label = "TILD" },
    .{ .value = IQUE, .label = "IQUE", .short_label = "IQUE" },
    .{ .value = RNGA, .label = "RNGA", .short_label = "RNGA" },
    .{ .value = DGRK, .label = "DGRK", .short_label = "DGRK" },
    .{ .value = DAGG, .label = "DAGG", .short_label = "DAGG" },
    .{ .value = OGON, .label = "OGON", .short_label = "OGON" },
    .{ .value = UNDS, .label = "UNDS", .short_label = "UNDS" },
    .{ .value = PARA, .label = "PARA", .short_label = "PARA" },
    .{ .value = DLQU, .label = "DLQU", .short_label = "DLQU" },
    .{ .value = LDQU, .label = "LDQU", .short_label = "LDQU" },
    .{ .value = RDQU, .label = "RDQU", .short_label = "RDQU" },
    .{ .value = LEQL, .label = "LEQL", .short_label = "LEQL" },
    .{ .value = GEQL, .label = "GEQL", .short_label = "GEQL" },
    .{ .value = NOT, .label = "NOT", .short_label = "NOT" },
    .{ .value = QRTR, .label = "QRTR", .short_label = "QRTR" },
    .{ .value = HALF, .label = "HALF", .short_label = "HALF" },
    .{ .value = TQTR, .label = "TQTR", .short_label = "TQTR" },
    .{ .value = PRIM, .label = "PRIM", .short_label = "PRIM" },
    .{ .value = DPRM, .label = "DPRM", .short_label = "DPRM" },
    .{ .value = BRKP, .label = "BRKP", .short_label = "BRKP" },
    .{ .value = DACU, .label = "DACU", .short_label = "DACU" },
    .{ .value = SECT, .label = "SECT", .short_label = "SECT" },
    .{ .value = DOTA, .label = "DOTA", .short_label = "DOTA" },
    .{ .value = CURR, .label = "CURR", .short_label = "CURR" },
    .{ .value = HORN, .label = "HORN", .short_label = "HORN" },
    .{ .value = LNGS, .label = "LNGS", .short_label = "LNGS" },
    .{ .value = TM, .label = "TM", .short_label = "TM" },
    .{ .value = MORD, .label = "MORD", .short_label = "MORD" },
    .{ .value = DCMM, .label = "DCMM", .short_label = "DCMM" },
    .{ .value = LSQU, .label = "LSQU", .short_label = "LSQU" },
    .{ .value = RSQU, .label = "RSQU", .short_label = "RSQU" },
    .{ .value = MDDT, .label = "MDDT", .short_label = "MDDT" },
    .{ .value = KEYB, .label = "KEYB", .short_label = "KEYB" },
    .{ .value = HOKA, .label = "HOKA", .short_label = "HOKA" },
    .{ .value = DOTB, .label = "DOTB", .short_label = "DOTB" },
    .{ .value = DDAG, .label = "DDAG", .short_label = "DDAG" },
    .{ .value = FORD, .label = "FORD", .short_label = "FORD" },
    .{ .value = NNBS, .label = "NNBS", .short_label = "NNBS" },
};

pub fn getLabel(keycode: core.KeyCodeFire, shortest: bool) ?[]const u8 {
    return zkc_core.getLabel(&_labels, keycode, shortest);
}
