// Copyright 2026 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by zkeycodes from QMK hjson keycode files
const zkc_core = @import("../src/core.zig");
const core = @import("zigmkay").core;
const L_SFT = zkc_core.L_SFT;
const L_ALT = zkc_core.L_ALT;
const R_ALT = zkc_core.R_ALT;
const R_CTL = zkc_core.R_CTL;
const DEAD = zkc_core.DEAD;
pub const keycodes = @import("keycodes.zig");

pub const QMK_CANADIAN_MULTILINGUAL_KEYCODES_VERSION = "0.0.1";
pub const QMK_CANADIAN_MULTILINGUAL_KEYCODES_VERSION_BCD = @as(c_int, 0x00000001);
pub const QMK_CANADIAN_MULTILINGUAL_KEYCODES_VERSION_MAJOR = @as(c_int, 0);
pub const QMK_CANADIAN_MULTILINGUAL_KEYCODES_VERSION_MINOR = @as(c_int, 0);
pub const QMK_CANADIAN_MULTILINGUAL_KEYCODES_VERSION_PATCH = @as(c_int, 1);

//
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ / │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ - │ = │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │ ^ │ Ç │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ ; │ È │ À │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ Ù │ Z │ X │ C │ V │ B │ N │ M │ , │ . │ É │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// /
pub const SLSH = keycodes.kcf.GRV;
/// 1
pub const N1 = keycodes.kcf.N1;
/// 2
pub const N2 = keycodes.kcf.N2;
/// 3
pub const N3 = keycodes.kcf.N3;
/// 4
pub const N4 = keycodes.kcf.N4;
/// 5
pub const N5 = keycodes.kcf.N5;
/// 6
pub const N6 = keycodes.kcf.N6;
/// 7
pub const N7 = keycodes.kcf.N7;
/// 8
pub const N8 = keycodes.kcf.N8;
/// 9
pub const N9 = keycodes.kcf.N9;
/// 0
pub const N0 = keycodes.kcf.N0;
/// -
pub const MINS = keycodes.kcf.MINS;
/// =
pub const EQL = keycodes.kcf.EQL;
/// Q
pub const Q = keycodes.kcf.Q;
/// W
pub const W = keycodes.kcf.W;
/// E
pub const E = keycodes.kcf.E;
/// R
pub const R = keycodes.kcf.R;
/// T
pub const T = keycodes.kcf.T;
/// Y
pub const Y = keycodes.kcf.Y;
/// U
pub const U = keycodes.kcf.U;
/// I
pub const I = keycodes.kcf.I;
/// O
pub const O = keycodes.kcf.O;
/// P
pub const P = keycodes.kcf.P;
/// ^ (dead)
pub const CIRC = DEAD(keycodes.kcf.LBRC);
/// Ç
pub const CCED = keycodes.kcf.RBRC;
/// A
pub const A = keycodes.kcf.A;
/// S
pub const S = keycodes.kcf.S;
/// D
pub const D = keycodes.kcf.D;
/// F
pub const F = keycodes.kcf.F;
/// G
pub const G = keycodes.kcf.G;
/// H
pub const H = keycodes.kcf.H;
/// J
pub const J = keycodes.kcf.J;
/// K
pub const K = keycodes.kcf.K;
/// L
pub const L = keycodes.kcf.L;
/// ;
pub const SCLN = keycodes.kcf.SCLN;
/// É
pub const EGRV = keycodes.kcf.QUOT;
/// À
pub const AGRV = keycodes.kcf.NUHS;
/// Ù
pub const UGRV = keycodes.kcf.NUBS;
/// Z
pub const Z = keycodes.kcf.Z;
/// X
pub const X = keycodes.kcf.X;
/// C
pub const C = keycodes.kcf.C;
/// V
pub const V = keycodes.kcf.V;
/// B
pub const B = keycodes.kcf.B;
/// N
pub const N = keycodes.kcf.N;
/// M
pub const M = keycodes.kcf.M;
/// ,
pub const COMM = keycodes.kcf.COMM;
/// .
pub const DOT = keycodes.kcf.DOT;
/// É
pub const EACU = keycodes.kcf.SLSH;
// Shifted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ \ │ ! │ @ │ # │ $ │ % │ ? │ & │ * │ ( │ ) │ _ │ + │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │   │   │   │   │   │   │   │   │ ¨ │   │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │   │   │   │   │   │   │   │   │   │ : │   │   │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │   │   │   │   │   │   │   │   │ ' │ " │   │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// (backslash)
pub const BSLS = L_SFT(SLSH);
/// !
pub const EXLM = L_SFT(N1);
/// @
pub const AT = L_SFT(N2);
/// #
pub const HASH = L_SFT(N3);
/// $
pub const DLR = L_SFT(N4);
/// %
pub const PERC = L_SFT(N5);
/// ?
pub const QUES = L_SFT(N6);
/// &
pub const AMPR = L_SFT(N7);
/// *
pub const ASTR = L_SFT(N8);
/// (
pub const LPRN = L_SFT(N9);
/// )
pub const RPRN = L_SFT(N0);
/// _
pub const UNDS = L_SFT(MINS);
/// +
pub const PLUS = L_SFT(EQL);
/// ¨ (dead)
pub const DIAE = DEAD(L_SFT(CIRC));
/// :
pub const COLN = L_SFT(SCLN);
/// '
pub const QUOT = L_SFT(COMM);
/// "
pub const DQUO = L_SFT(DOT);
// AltGr symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ | │   │   │   │ ¤ │   │   │ { │ } │ [ │ ] │   │ ¬ │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │ € │   │   │   │   │   │   │   │ ` │ ~ │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │   │   │   │   │   │   │   │   │   │ ° │   │   │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │   │ « │ » │   │   │   │   │   │ < │ > │   │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// |
pub const PIPE = R_ALT(SLSH);
/// ¤
pub const CURR = R_ALT(N4);
/// {
pub const LCBR = R_ALT(N7);
/// }
pub const RCBR = R_ALT(N8);
/// [
pub const LBRC = R_ALT(N9);
/// ]
pub const RBRC = R_ALT(N0);
/// ¬
pub const NOT = R_ALT(EQL);
/// €
pub const EURO = R_ALT(E);
/// ` (dead)
pub const GRV = DEAD(R_ALT(CIRC));
/// ~ (dead)
pub const DTIL = DEAD(R_ALT(CCED));
/// °
pub const DEG = R_ALT(SCLN);
/// «
pub const LDAQ = R_ALT(Z);
/// »
pub const RDAQ = R_ALT(X);
/// <
pub const LABK = R_ALT(COMM);
/// >
pub const RABK = R_ALT(DOT);
// Right Ctrl symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │   │ ¹ │ ² │ ³ │ ¼ │ ½ │ ¾ │   │   │   │   │   │ ¸ │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ Ω │ Ł │ Œ │ ¶ │ Ŧ │ ← │ ↓ │ → │ Ø │ Þ │   │ ~ │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │ Æ │ ß │ Ð │   │ Ŋ │ Ħ │ Ĳ │ ĸ │ Ŀ │ ´ │   │   │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │   │   │   │ ¢ │ “ │ ” │ ŉ │ μ │ ― │ ˙ │   │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ¹
pub const SUP1 = R_CTL(N1);
/// ²
pub const SUP2 = R_CTL(N2);
/// ³
pub const SUP3 = R_CTL(N3);
/// ¼
pub const QRTR = R_CTL(N4);
/// ½
pub const HALF = R_CTL(N5);
/// ¾
pub const TQTR = R_CTL(N6);
/// ¸ (dead)
pub const CEDL = DEAD(R_CTL(EQL));
/// Ω
pub const OMEG = R_CTL(Q);
/// Ł
pub const LSTR = R_CTL(W);
/// Œ
pub const OE = R_CTL(E);
/// ¶
pub const PARA = R_CTL(R);
/// Ŧ
pub const TSTR = R_CTL(T);
/// ←
pub const LARR = R_CTL(Y);
/// ↓
pub const DARR = R_CTL(U);
/// →
pub const RARR = R_CTL(I);
/// Ø
pub const OSTR = R_CTL(O);
/// Þ
pub const THRN = R_CTL(P);
/// ~
pub const TILD = R_CTL(CCED);
/// Æ
pub const AE = R_CTL(A);
/// ß
pub const SS = R_CTL(S);
/// Ð
pub const ETH = R_CTL(D);
/// Ŋ
pub const ENG = R_CTL(G);
/// Ħ
pub const HSTR = R_CTL(H);
/// Ĳ
pub const IJ = R_CTL(J);
/// ĸ
pub const KRA = R_CTL(K);
/// Ŀ
pub const LMDT = R_CTL(L);
/// ´ (dead)
pub const ACUT = DEAD(R_CTL(SCLN));
/// ¢
pub const CENT = R_CTL(C);
/// “
pub const LDQU = R_CTL(V);
/// ”
pub const RDQU = R_CTL(B);
/// ŉ
pub const APSN = R_CTL(N);
/// μ
pub const MICR = R_CTL(M);
/// ―
pub const HRZB = R_CTL(COMM);
/// ˙ (dead)
pub const DOTA = DEAD(R_CTL(DOT));
// Shift+Right Ctrl symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ - │ ¡ │   │ £ │   │ ⅜ │ ⅝ │ ⅞ │ ™ │ ± │   │ ¿ │ ˛ │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │   │ ® │   │ ¥ │ ↑ │ ı │   │   │ ° │ ¯ │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │   │ § │   │ ª │   │   │   │   │   │ ˝ │ ˇ │ ˘ │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ ¦ │   │   │ © │ ‘ │ ’ │ ♪ │ º │ × │ ÷ │   │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ­ (soft hyphen)
pub const SHYP = R_CTL(L_SFT(SLSH));
/// ¡
pub const IEXL = R_CTL(L_SFT(N1));
/// £
pub const PND = R_CTL(L_SFT(N3));
/// ⅜
pub const TEIG = R_CTL(L_SFT(N5));
/// ⅝
pub const FEIG = R_CTL(L_SFT(N6));
/// ⅞
pub const SEIG = R_CTL(L_SFT(N7));
/// ™
pub const TM = R_CTL(L_SFT(N8));
/// ±
pub const PLMN = R_CTL(L_SFT(N9));
/// ¿
pub const IQUE = R_CTL(L_SFT(MINS));
/// ˛ (dead)
pub const OGON = DEAD(R_CTL(L_SFT(EQL)));
/// ®
pub const REGD = R_CTL(L_SFT(R));
/// ¥
pub const YEN = R_CTL(L_SFT(Y));
/// ↑
pub const UARR = R_CTL(L_SFT(U));
/// ı
pub const DLSI = R_CTL(L_SFT(I));
/// ° (dead)
pub const RNGA = DEAD(R_CTL(L_SFT(CIRC)));
/// ¯ (dead)
pub const MACR = DEAD(R_CTL(L_SFT(CCED)));
/// §
pub const SECT = R_CTL(L_SFT(S));
/// ª
pub const FORD = R_CTL(L_SFT(F));
/// ˝ (dead)
pub const DACU = DEAD(R_CTL(L_SFT(SCLN)));
/// ˇ (dead)
pub const CARN = DEAD(R_CTL(L_SFT(EGRV)));
/// ˘ (dead)
pub const BREV = DEAD(R_CTL(L_SFT(AGRV)));
/// ¦
pub const BRKP = R_CTL(L_SFT(UGRV));
/// ©
pub const COPY = R_CTL(L_SFT(C));
/// ‘
pub const LSQU = R_CTL(L_SFT(V));
/// ’
pub const RSQU = R_CTL(L_SFT(B));
/// ♪
pub const ENOT = R_CTL(L_SFT(N));
/// º
pub const MORD = R_CTL(L_SFT(M));
/// ×
pub const MUL = R_CTL(L_SFT(COMM));
/// ÷
pub const DIV = R_CTL(L_SFT(DOT));

// Label lookup table
pub const _labels = [_]zkc_core.LabelEntry{
    .{ .value = SLSH, .label = "SLSH", .short_label = "SLSH" },
    .{ .value = N1, .label = "1", .short_label = "1" },
    .{ .value = N2, .label = "2", .short_label = "2" },
    .{ .value = N3, .label = "3", .short_label = "3" },
    .{ .value = N4, .label = "4", .short_label = "4" },
    .{ .value = N5, .label = "5", .short_label = "5" },
    .{ .value = N6, .label = "6", .short_label = "6" },
    .{ .value = N7, .label = "7", .short_label = "7" },
    .{ .value = N8, .label = "8", .short_label = "8" },
    .{ .value = N9, .label = "9", .short_label = "9" },
    .{ .value = N0, .label = "0", .short_label = "0" },
    .{ .value = MINS, .label = "MINS", .short_label = "MINS" },
    .{ .value = EQL, .label = "EQL", .short_label = "EQL" },
    .{ .value = Q, .label = "Q", .short_label = "Q" },
    .{ .value = W, .label = "W", .short_label = "W" },
    .{ .value = E, .label = "E", .short_label = "E" },
    .{ .value = R, .label = "R", .short_label = "R" },
    .{ .value = T, .label = "T", .short_label = "T" },
    .{ .value = Y, .label = "Y", .short_label = "Y" },
    .{ .value = U, .label = "U", .short_label = "U" },
    .{ .value = I, .label = "I", .short_label = "I" },
    .{ .value = O, .label = "O", .short_label = "O" },
    .{ .value = P, .label = "P", .short_label = "P" },
    .{ .value = CIRC, .label = "CIRC", .short_label = "CIRC" },
    .{ .value = CCED, .label = "CCED", .short_label = "CCED" },
    .{ .value = A, .label = "A", .short_label = "A" },
    .{ .value = S, .label = "S", .short_label = "S" },
    .{ .value = D, .label = "D", .short_label = "D" },
    .{ .value = F, .label = "F", .short_label = "F" },
    .{ .value = G, .label = "G", .short_label = "G" },
    .{ .value = H, .label = "H", .short_label = "H" },
    .{ .value = J, .label = "J", .short_label = "J" },
    .{ .value = K, .label = "K", .short_label = "K" },
    .{ .value = L, .label = "L", .short_label = "L" },
    .{ .value = SCLN, .label = "SCLN", .short_label = "SCLN" },
    .{ .value = EGRV, .label = "EGRV", .short_label = "EGRV" },
    .{ .value = AGRV, .label = "AGRV", .short_label = "AGRV" },
    .{ .value = UGRV, .label = "UGRV", .short_label = "UGRV" },
    .{ .value = Z, .label = "Z", .short_label = "Z" },
    .{ .value = X, .label = "X", .short_label = "X" },
    .{ .value = C, .label = "C", .short_label = "C" },
    .{ .value = V, .label = "V", .short_label = "V" },
    .{ .value = B, .label = "B", .short_label = "B" },
    .{ .value = N, .label = "N", .short_label = "N" },
    .{ .value = M, .label = "M", .short_label = "M" },
    .{ .value = COMM, .label = "COMM", .short_label = "COMM" },
    .{ .value = DOT, .label = "DOT", .short_label = "DOT" },
    .{ .value = EACU, .label = "EACU", .short_label = "EACU" },
    .{ .value = BSLS, .label = "BSLS", .short_label = "BSLS" },
    .{ .value = EXLM, .label = "EXLM", .short_label = "EXLM" },
    .{ .value = AT, .label = "AT", .short_label = "AT" },
    .{ .value = HASH, .label = "HASH", .short_label = "HASH" },
    .{ .value = DLR, .label = "DLR", .short_label = "DLR" },
    .{ .value = PERC, .label = "PERC", .short_label = "PERC" },
    .{ .value = QUES, .label = "QUES", .short_label = "QUES" },
    .{ .value = AMPR, .label = "AMPR", .short_label = "AMPR" },
    .{ .value = ASTR, .label = "ASTR", .short_label = "ASTR" },
    .{ .value = LPRN, .label = "LPRN", .short_label = "LPRN" },
    .{ .value = RPRN, .label = "RPRN", .short_label = "RPRN" },
    .{ .value = UNDS, .label = "UNDS", .short_label = "UNDS" },
    .{ .value = PLUS, .label = "PLUS", .short_label = "PLUS" },
    .{ .value = DIAE, .label = "DIAE", .short_label = "DIAE" },
    .{ .value = COLN, .label = "COLN", .short_label = "COLN" },
    .{ .value = QUOT, .label = "QUOT", .short_label = "QUOT" },
    .{ .value = DQUO, .label = "DQUO", .short_label = "DQUO" },
    .{ .value = PIPE, .label = "PIPE", .short_label = "PIPE" },
    .{ .value = CURR, .label = "CURR", .short_label = "CURR" },
    .{ .value = LCBR, .label = "LCBR", .short_label = "LCBR" },
    .{ .value = RCBR, .label = "RCBR", .short_label = "RCBR" },
    .{ .value = LBRC, .label = "LBRC", .short_label = "LBRC" },
    .{ .value = RBRC, .label = "RBRC", .short_label = "RBRC" },
    .{ .value = NOT, .label = "NOT", .short_label = "NOT" },
    .{ .value = EURO, .label = "EURO", .short_label = "EURO" },
    .{ .value = GRV, .label = "GRV", .short_label = "GRV" },
    .{ .value = DTIL, .label = "DTIL", .short_label = "DTIL" },
    .{ .value = DEG, .label = "DEG", .short_label = "DEG" },
    .{ .value = LDAQ, .label = "LDAQ", .short_label = "LDAQ" },
    .{ .value = RDAQ, .label = "RDAQ", .short_label = "RDAQ" },
    .{ .value = LABK, .label = "LABK", .short_label = "LABK" },
    .{ .value = RABK, .label = "RABK", .short_label = "RABK" },
    .{ .value = SUP1, .label = "SUP1", .short_label = "SUP1" },
    .{ .value = SUP2, .label = "SUP2", .short_label = "SUP2" },
    .{ .value = SUP3, .label = "SUP3", .short_label = "SUP3" },
    .{ .value = QRTR, .label = "QRTR", .short_label = "QRTR" },
    .{ .value = HALF, .label = "HALF", .short_label = "HALF" },
    .{ .value = TQTR, .label = "TQTR", .short_label = "TQTR" },
    .{ .value = CEDL, .label = "CEDL", .short_label = "CEDL" },
    .{ .value = OMEG, .label = "OMEG", .short_label = "OMEG" },
    .{ .value = LSTR, .label = "LSTR", .short_label = "LSTR" },
    .{ .value = OE, .label = "OE", .short_label = "OE" },
    .{ .value = PARA, .label = "PARA", .short_label = "PARA" },
    .{ .value = TSTR, .label = "TSTR", .short_label = "TSTR" },
    .{ .value = LARR, .label = "LARR", .short_label = "LARR" },
    .{ .value = DARR, .label = "DARR", .short_label = "DARR" },
    .{ .value = RARR, .label = "RARR", .short_label = "RARR" },
    .{ .value = OSTR, .label = "OSTR", .short_label = "OSTR" },
    .{ .value = THRN, .label = "THRN", .short_label = "THRN" },
    .{ .value = TILD, .label = "TILD", .short_label = "TILD" },
    .{ .value = AE, .label = "AE", .short_label = "AE" },
    .{ .value = SS, .label = "SS", .short_label = "SS" },
    .{ .value = ETH, .label = "ETH", .short_label = "ETH" },
    .{ .value = ENG, .label = "ENG", .short_label = "ENG" },
    .{ .value = HSTR, .label = "HSTR", .short_label = "HSTR" },
    .{ .value = IJ, .label = "IJ", .short_label = "IJ" },
    .{ .value = KRA, .label = "KRA", .short_label = "KRA" },
    .{ .value = LMDT, .label = "LMDT", .short_label = "LMDT" },
    .{ .value = ACUT, .label = "ACUT", .short_label = "ACUT" },
    .{ .value = CENT, .label = "CENT", .short_label = "CENT" },
    .{ .value = LDQU, .label = "LDQU", .short_label = "LDQU" },
    .{ .value = RDQU, .label = "RDQU", .short_label = "RDQU" },
    .{ .value = APSN, .label = "APSN", .short_label = "APSN" },
    .{ .value = MICR, .label = "MICR", .short_label = "MICR" },
    .{ .value = HRZB, .label = "HRZB", .short_label = "HRZB" },
    .{ .value = DOTA, .label = "DOTA", .short_label = "DOTA" },
    .{ .value = SHYP, .label = "SHYP", .short_label = "SHYP" },
    .{ .value = IEXL, .label = "IEXL", .short_label = "IEXL" },
    .{ .value = PND, .label = "PND", .short_label = "PND" },
    .{ .value = TEIG, .label = "TEIG", .short_label = "TEIG" },
    .{ .value = FEIG, .label = "FEIG", .short_label = "FEIG" },
    .{ .value = SEIG, .label = "SEIG", .short_label = "SEIG" },
    .{ .value = TM, .label = "TM", .short_label = "TM" },
    .{ .value = PLMN, .label = "PLMN", .short_label = "PLMN" },
    .{ .value = IQUE, .label = "IQUE", .short_label = "IQUE" },
    .{ .value = OGON, .label = "OGON", .short_label = "OGON" },
    .{ .value = REGD, .label = "REGD", .short_label = "REGD" },
    .{ .value = YEN, .label = "YEN", .short_label = "YEN" },
    .{ .value = UARR, .label = "UARR", .short_label = "UARR" },
    .{ .value = DLSI, .label = "DLSI", .short_label = "DLSI" },
    .{ .value = RNGA, .label = "RNGA", .short_label = "RNGA" },
    .{ .value = MACR, .label = "MACR", .short_label = "MACR" },
    .{ .value = SECT, .label = "SECT", .short_label = "SECT" },
    .{ .value = FORD, .label = "FORD", .short_label = "FORD" },
    .{ .value = DACU, .label = "DACU", .short_label = "DACU" },
    .{ .value = CARN, .label = "CARN", .short_label = "CARN" },
    .{ .value = BREV, .label = "BREV", .short_label = "BREV" },
    .{ .value = BRKP, .label = "BRKP", .short_label = "BRKP" },
    .{ .value = COPY, .label = "COPY", .short_label = "COPY" },
    .{ .value = LSQU, .label = "LSQU", .short_label = "LSQU" },
    .{ .value = RSQU, .label = "RSQU", .short_label = "RSQU" },
    .{ .value = ENOT, .label = "ENOT", .short_label = "ENOT" },
    .{ .value = MORD, .label = "MORD", .short_label = "MORD" },
    .{ .value = MUL, .label = "MUL", .short_label = "MUL" },
    .{ .value = DIV, .label = "DIV", .short_label = "DIV" },
};

pub fn getLabel(keycode: core.KeyCodeFire, shortest: bool) ?[]const u8 {
    return zkc_core.getLabel(&_labels, keycode, shortest);
}
