// Copyright 2026 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by zkeycodes from QMK hjson keycode files
const zkc_core = @import("../src/core.zig");
const core = @import("zigmkay").core;
const L_SFT = zkc_core.L_SFT;
const L_ALT = zkc_core.L_ALT;
const R_ALT = zkc_core.R_ALT;
const R_CTL = zkc_core.R_CTL;
const DEAD = zkc_core.DEAD;
pub const keycodes = @import("keycodes.zig");

pub const QMK_CZECH_MAC_ISO_KEYCODES_VERSION = "0.0.1";
pub const QMK_CZECH_MAC_ISO_KEYCODES_VERSION_BCD = @as(c_int, 0x00000001);
pub const QMK_CZECH_MAC_ISO_KEYCODES_VERSION_MAJOR = @as(c_int, 0);
pub const QMK_CZECH_MAC_ISO_KEYCODES_VERSION_MINOR = @as(c_int, 0);
pub const QMK_CZECH_MAC_ISO_KEYCODES_VERSION_PATCH = @as(c_int, 1);

//
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
// │   │ + │ ě │ š │ č │ ř │ ž │ ý │ á │ í │ é │ = │ ' │     │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
// │     │ Q │ W │ E │ R │ T │ Z │ U │ I │ O │ P │ ú │ ) │   │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐  │
// │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ ů │ § │ ¨ │  │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴──┤
// │    │ \ │ Y │ X │ C │ V │ B │ N │ M │ , │ . │ - │        │
// ├────┴┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
// │     │    │     │                       │     │    │     │
// └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
//
/// +
pub const PLUS = keycodes.kcf.N1;
/// ě
pub const ECAR = keycodes.kcf.N2;
/// š
pub const SCAR = keycodes.kcf.N3;
/// č
pub const CCAR = keycodes.kcf.N4;
/// ř
pub const RCAR = keycodes.kcf.N5;
/// ž
pub const ZCAR = keycodes.kcf.N6;
/// ý
pub const YACU = keycodes.kcf.N7;
/// á
pub const AACU = keycodes.kcf.N8;
/// í
pub const IACU = keycodes.kcf.N9;
/// é
pub const EACU = keycodes.kcf.N0;
/// =
pub const EQL = keycodes.kcf.MINS;
/// ' (dead)
pub const ACUT = DEAD(keycodes.kcf.EQL);
/// Q
pub const Q = keycodes.kcf.Q;
/// W
pub const W = keycodes.kcf.W;
/// E
pub const E = keycodes.kcf.E;
/// R
pub const R = keycodes.kcf.R;
/// T
pub const T = keycodes.kcf.T;
/// Z
pub const Z = keycodes.kcf.Y;
/// U
pub const U = keycodes.kcf.U;
/// I
pub const I = keycodes.kcf.I;
/// O
pub const O = keycodes.kcf.O;
/// P
pub const P = keycodes.kcf.P;
/// ú
pub const UACU = keycodes.kcf.LBRC;
/// )
pub const RPRN = keycodes.kcf.RBRC;
/// A
pub const A = keycodes.kcf.A;
/// S
pub const S = keycodes.kcf.S;
/// D
pub const D = keycodes.kcf.D;
/// F
pub const F = keycodes.kcf.F;
/// G
pub const G = keycodes.kcf.G;
/// H
pub const H = keycodes.kcf.H;
/// J
pub const J = keycodes.kcf.J;
/// K
pub const K = keycodes.kcf.K;
/// L
pub const L = keycodes.kcf.L;
/// ů
pub const URNG = keycodes.kcf.SCLN;
/// §
pub const SECT = keycodes.kcf.QUOT;
/// ¨ (dead)
pub const DIAE = DEAD(keycodes.kcf.NUHS);
/// (backslash)
pub const BSLS = keycodes.kcf.NUBS;
/// Y
pub const Y = keycodes.kcf.Z;
/// X
pub const X = keycodes.kcf.X;
/// C
pub const C = keycodes.kcf.C;
/// V
pub const V = keycodes.kcf.V;
/// B
pub const B = keycodes.kcf.B;
/// N
pub const N = keycodes.kcf.N;
/// M
pub const M = keycodes.kcf.M;
/// ,
pub const COMM = keycodes.kcf.COMM;
/// .
pub const DOT = keycodes.kcf.DOT;
/// -
pub const MINS = keycodes.kcf.SLSH;
// Shifted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
// │   │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ % │ ˇ │     │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
// │     │   │   │   │   │   │   │   │   │   │   │ / │ ( │   │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐  │
// │      │   │   │   │   │   │   │   │   │   │ " │ ! │ ` │  │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴──┤
// │    │ | │   │   │   │   │   │   │   │ ? │ : │ _ │        │
// ├────┴┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
// │     │    │     │                       │     │    │     │
// └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
//
/// 1
pub const N1 = L_SFT(PLUS);
/// 2
pub const N2 = L_SFT(ECAR);
/// 3
pub const N3 = L_SFT(SCAR);
/// 4
pub const N4 = L_SFT(CCAR);
/// 5
pub const N5 = L_SFT(RCAR);
/// 6
pub const N6 = L_SFT(ZCAR);
/// 7
pub const N7 = L_SFT(YACU);
/// 8
pub const N8 = L_SFT(AACU);
/// 9
pub const N9 = L_SFT(IACU);
/// 0
pub const N0 = L_SFT(EACU);
/// %
pub const PERC = L_SFT(EQL);
/// ˇ (dead)
pub const CARN = DEAD(L_SFT(ACUT));
/// /
pub const SLSH = L_SFT(UACU);
/// (
pub const LPRN = L_SFT(RPRN);
/// "
pub const DQUO = L_SFT(URNG);
/// !
pub const EXLM = L_SFT(SECT);
/// `
pub const GRV = L_SFT(DIAE);
/// |
pub const PIPE = L_SFT(BSLS);
/// ?
pub const QUES = L_SFT(COMM);
/// :
pub const COLN = L_SFT(DOT);
/// _
pub const UNDS = L_SFT(MINS);
// Alted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
// │   │   │ @ │ # │ $ │ ~ │ ^ │ & │ * │ { │ } │ ° │ ^ │     │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
// │     │   │ ė │ ę │ € │   │ ż │   │   │   │   │ [ │ ] │   │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐  │
// │      │ ą │ ß │ ∂ │   │   │ ‘ │ ’ │   │ ł │ ; │ ' │   │  │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴──┤
// │    │   │   │   │   │   │   │ ‚ │   │ < │ > │ – │        │
// ├────┴┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
// │     │    │     │                       │     │    │     │
// └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
//
/// @
pub const AT = L_ALT(ECAR);
/// #
pub const HASH = L_ALT(SCAR);
/// $
pub const DLR = L_ALT(CCAR);
/// ~
pub const TILD = L_ALT(RCAR);
/// ^
pub const CIRC = L_ALT(ZCAR);
/// &
pub const AMPR = L_ALT(YACU);
/// *
pub const ASTR = L_ALT(AACU);
/// {
pub const LCBR = L_ALT(IACU);
/// }
pub const RCBR = L_ALT(EACU);
/// ° (dead)
pub const RNGA = DEAD(L_ALT(EQL));
/// ^ (dead)
pub const DCIR = DEAD(L_ALT(ACUT));
/// ė
pub const LEDT = L_ALT(W);
/// ę
pub const LEOG = L_ALT(E);
/// €
pub const EURO = L_ALT(R);
/// ż
pub const LZDT = L_ALT(Z);
/// [
pub const LBRC = L_ALT(UACU);
/// ]
pub const RBRC = L_ALT(RPRN);
/// ą
pub const LAOG = L_ALT(A);
/// ß
pub const SS = L_ALT(S);
/// ∂
pub const PDIF = L_ALT(D);
/// ‘
pub const LSQU = L_ALT(H);
/// ’
pub const RSQU = L_ALT(J);
/// ł
pub const LLST = L_ALT(L);
/// ;
pub const SCLN = L_ALT(URNG);
/// '
pub const QUOT = L_ALT(SECT);
/// ‚
pub const SLQU = L_ALT(N);
/// <
pub const LABK = L_ALT(COMM);
/// >
pub const RABK = L_ALT(DOT);
/// –
pub const NDSH = L_ALT(MINS);
// Shift+Alted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
// │   │ ¬ │ • │ ≠ │ £ │ ◊ │ † │ ¶ │ ÷ │ « │ » │ , │ - │     │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
// │     │   │ Ė │ Ę │ ® │ ™ │ Ż │   │   │   │   │ ‹ │ › │   │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐  │
// │      │ Ą │ ∑ │ ∆ │   │   │ “ │ ” │   │ Ł │ … │ ~ │ " │  │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴──┤
// │    │   │   │   │ © │ √ │   │ „ │   │ ≤ │ ≥ │ — │        │
// ├────┴┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
// │     │    │     │                       │     │    │     │
// └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
//
/// ¬
pub const NOT = L_SFT(L_ALT(N1));
/// •
pub const BULT = L_SFT(L_ALT(N2));
/// ≠
pub const NEQL = L_SFT(L_ALT(N3));
/// £
pub const PND = L_SFT(L_ALT(N4));
/// ◊
pub const LOZN = L_SFT(L_ALT(N5));
/// †
pub const DAGG = L_SFT(L_ALT(N6));
/// ¶
pub const PARA = L_SFT(L_ALT(N7));
/// ÷
pub const DIV = L_SFT(L_ALT(N8));
/// «
pub const LDAQ = L_SFT(L_ALT(N9));
/// »
pub const RDAQ = L_SFT(L_ALT(N0));
/// , (dead)
pub const DCOM = DEAD(L_SFT(L_ALT(EQL)));
/// - (dead)
pub const DHPN = DEAD(L_SFT(L_ALT(ACUT)));
/// Ė
pub const CEDT = L_SFT(L_ALT(W));
/// Ę
pub const CEOG = L_SFT(L_ALT(E));
/// ®
pub const REGD = L_SFT(L_ALT(R));
/// ™
pub const TM = L_SFT(L_ALT(T));
/// Ż
pub const CZDT = L_SFT(L_ALT(Z));
/// ‹
pub const LSAQ = L_SFT(L_ALT(UACU));
/// ›
pub const RSAQ = L_SFT(L_ALT(RPRN));
/// Ą
pub const CAOG = L_SFT(L_ALT(A));
/// ∑
pub const NARS = L_SFT(L_ALT(S));
/// ∆
pub const INCR = L_SFT(L_ALT(D));
/// “
pub const LDQU = L_SFT(L_ALT(H));
/// ”
pub const RDQU = L_SFT(L_ALT(J));
/// Ł
pub const CLST = L_SFT(L_ALT(L));
/// …
pub const ELLP = L_SFT(L_ALT(URNG));
/// ~ (dead)
pub const DTIL = DEAD(L_SFT(L_ALT(SECT)));
/// " (dead)
pub const DDQT = DEAD(L_SFT(L_ALT(DIAE)));
/// ©
pub const COPY = L_SFT(L_ALT(C));
/// √
pub const SQRT = L_SFT(L_ALT(V));
/// „
pub const DLQU = L_SFT(L_ALT(N));
/// ≤
pub const LEQL = L_SFT(L_ALT(COMM));
/// ≥
pub const GEQL = L_SFT(L_ALT(DOT));
/// —
pub const MDSH = L_SFT(L_ALT(MINS));

// Label lookup table
pub const _labels = [_]zkc_core.LabelEntry{
    .{ .value = PLUS, .label = "PLUS", .short_label = "PLUS" },
    .{ .value = ECAR, .label = "ECAR", .short_label = "ECAR" },
    .{ .value = SCAR, .label = "SCAR", .short_label = "SCAR" },
    .{ .value = CCAR, .label = "CCAR", .short_label = "CCAR" },
    .{ .value = RCAR, .label = "RCAR", .short_label = "RCAR" },
    .{ .value = ZCAR, .label = "ZCAR", .short_label = "ZCAR" },
    .{ .value = YACU, .label = "YACU", .short_label = "YACU" },
    .{ .value = AACU, .label = "AACU", .short_label = "AACU" },
    .{ .value = IACU, .label = "IACU", .short_label = "IACU" },
    .{ .value = EACU, .label = "EACU", .short_label = "EACU" },
    .{ .value = EQL, .label = "EQL", .short_label = "EQL" },
    .{ .value = ACUT, .label = "ACUT", .short_label = "ACUT" },
    .{ .value = Q, .label = "Q", .short_label = "Q" },
    .{ .value = W, .label = "W", .short_label = "W" },
    .{ .value = E, .label = "E", .short_label = "E" },
    .{ .value = R, .label = "R", .short_label = "R" },
    .{ .value = T, .label = "T", .short_label = "T" },
    .{ .value = Z, .label = "Z", .short_label = "Z" },
    .{ .value = U, .label = "U", .short_label = "U" },
    .{ .value = I, .label = "I", .short_label = "I" },
    .{ .value = O, .label = "O", .short_label = "O" },
    .{ .value = P, .label = "P", .short_label = "P" },
    .{ .value = UACU, .label = "UACU", .short_label = "UACU" },
    .{ .value = RPRN, .label = "RPRN", .short_label = "RPRN" },
    .{ .value = A, .label = "A", .short_label = "A" },
    .{ .value = S, .label = "S", .short_label = "S" },
    .{ .value = D, .label = "D", .short_label = "D" },
    .{ .value = F, .label = "F", .short_label = "F" },
    .{ .value = G, .label = "G", .short_label = "G" },
    .{ .value = H, .label = "H", .short_label = "H" },
    .{ .value = J, .label = "J", .short_label = "J" },
    .{ .value = K, .label = "K", .short_label = "K" },
    .{ .value = L, .label = "L", .short_label = "L" },
    .{ .value = URNG, .label = "URNG", .short_label = "URNG" },
    .{ .value = SECT, .label = "SECT", .short_label = "SECT" },
    .{ .value = DIAE, .label = "DIAE", .short_label = "DIAE" },
    .{ .value = BSLS, .label = "BSLS", .short_label = "BSLS" },
    .{ .value = Y, .label = "Y", .short_label = "Y" },
    .{ .value = X, .label = "X", .short_label = "X" },
    .{ .value = C, .label = "C", .short_label = "C" },
    .{ .value = V, .label = "V", .short_label = "V" },
    .{ .value = B, .label = "B", .short_label = "B" },
    .{ .value = N, .label = "N", .short_label = "N" },
    .{ .value = M, .label = "M", .short_label = "M" },
    .{ .value = COMM, .label = "COMM", .short_label = "COMM" },
    .{ .value = DOT, .label = "DOT", .short_label = "DOT" },
    .{ .value = MINS, .label = "MINS", .short_label = "MINS" },
    .{ .value = N1, .label = "1", .short_label = "1" },
    .{ .value = N2, .label = "2", .short_label = "2" },
    .{ .value = N3, .label = "3", .short_label = "3" },
    .{ .value = N4, .label = "4", .short_label = "4" },
    .{ .value = N5, .label = "5", .short_label = "5" },
    .{ .value = N6, .label = "6", .short_label = "6" },
    .{ .value = N7, .label = "7", .short_label = "7" },
    .{ .value = N8, .label = "8", .short_label = "8" },
    .{ .value = N9, .label = "9", .short_label = "9" },
    .{ .value = N0, .label = "0", .short_label = "0" },
    .{ .value = PERC, .label = "PERC", .short_label = "PERC" },
    .{ .value = CARN, .label = "CARN", .short_label = "CARN" },
    .{ .value = SLSH, .label = "SLSH", .short_label = "SLSH" },
    .{ .value = LPRN, .label = "LPRN", .short_label = "LPRN" },
    .{ .value = DQUO, .label = "DQUO", .short_label = "DQUO" },
    .{ .value = EXLM, .label = "EXLM", .short_label = "EXLM" },
    .{ .value = GRV, .label = "GRV", .short_label = "GRV" },
    .{ .value = PIPE, .label = "PIPE", .short_label = "PIPE" },
    .{ .value = QUES, .label = "QUES", .short_label = "QUES" },
    .{ .value = COLN, .label = "COLN", .short_label = "COLN" },
    .{ .value = UNDS, .label = "UNDS", .short_label = "UNDS" },
    .{ .value = AT, .label = "AT", .short_label = "AT" },
    .{ .value = HASH, .label = "HASH", .short_label = "HASH" },
    .{ .value = DLR, .label = "DLR", .short_label = "DLR" },
    .{ .value = TILD, .label = "TILD", .short_label = "TILD" },
    .{ .value = CIRC, .label = "CIRC", .short_label = "CIRC" },
    .{ .value = AMPR, .label = "AMPR", .short_label = "AMPR" },
    .{ .value = ASTR, .label = "ASTR", .short_label = "ASTR" },
    .{ .value = LCBR, .label = "LCBR", .short_label = "LCBR" },
    .{ .value = RCBR, .label = "RCBR", .short_label = "RCBR" },
    .{ .value = RNGA, .label = "RNGA", .short_label = "RNGA" },
    .{ .value = DCIR, .label = "DCIR", .short_label = "DCIR" },
    .{ .value = LEDT, .label = "LEDT", .short_label = "LEDT" },
    .{ .value = LEOG, .label = "LEOG", .short_label = "LEOG" },
    .{ .value = EURO, .label = "EURO", .short_label = "EURO" },
    .{ .value = LZDT, .label = "LZDT", .short_label = "LZDT" },
    .{ .value = LBRC, .label = "LBRC", .short_label = "LBRC" },
    .{ .value = RBRC, .label = "RBRC", .short_label = "RBRC" },
    .{ .value = LAOG, .label = "LAOG", .short_label = "LAOG" },
    .{ .value = SS, .label = "SS", .short_label = "SS" },
    .{ .value = PDIF, .label = "PDIF", .short_label = "PDIF" },
    .{ .value = LSQU, .label = "LSQU", .short_label = "LSQU" },
    .{ .value = RSQU, .label = "RSQU", .short_label = "RSQU" },
    .{ .value = LLST, .label = "LLST", .short_label = "LLST" },
    .{ .value = SCLN, .label = "SCLN", .short_label = "SCLN" },
    .{ .value = QUOT, .label = "QUOT", .short_label = "QUOT" },
    .{ .value = SLQU, .label = "SLQU", .short_label = "SLQU" },
    .{ .value = LABK, .label = "LABK", .short_label = "LABK" },
    .{ .value = RABK, .label = "RABK", .short_label = "RABK" },
    .{ .value = NDSH, .label = "NDSH", .short_label = "NDSH" },
    .{ .value = NOT, .label = "NOT", .short_label = "NOT" },
    .{ .value = BULT, .label = "BULT", .short_label = "BULT" },
    .{ .value = NEQL, .label = "NEQL", .short_label = "NEQL" },
    .{ .value = PND, .label = "PND", .short_label = "PND" },
    .{ .value = LOZN, .label = "LOZN", .short_label = "LOZN" },
    .{ .value = DAGG, .label = "DAGG", .short_label = "DAGG" },
    .{ .value = PARA, .label = "PARA", .short_label = "PARA" },
    .{ .value = DIV, .label = "DIV", .short_label = "DIV" },
    .{ .value = LDAQ, .label = "LDAQ", .short_label = "LDAQ" },
    .{ .value = RDAQ, .label = "RDAQ", .short_label = "RDAQ" },
    .{ .value = DCOM, .label = "DCOM", .short_label = "DCOM" },
    .{ .value = DHPN, .label = "DHPN", .short_label = "DHPN" },
    .{ .value = CEDT, .label = "CEDT", .short_label = "CEDT" },
    .{ .value = CEOG, .label = "CEOG", .short_label = "CEOG" },
    .{ .value = REGD, .label = "REGD", .short_label = "REGD" },
    .{ .value = TM, .label = "TM", .short_label = "TM" },
    .{ .value = CZDT, .label = "CZDT", .short_label = "CZDT" },
    .{ .value = LSAQ, .label = "LSAQ", .short_label = "LSAQ" },
    .{ .value = RSAQ, .label = "RSAQ", .short_label = "RSAQ" },
    .{ .value = CAOG, .label = "CAOG", .short_label = "CAOG" },
    .{ .value = NARS, .label = "NARS", .short_label = "NARS" },
    .{ .value = INCR, .label = "INCR", .short_label = "INCR" },
    .{ .value = LDQU, .label = "LDQU", .short_label = "LDQU" },
    .{ .value = RDQU, .label = "RDQU", .short_label = "RDQU" },
    .{ .value = CLST, .label = "CLST", .short_label = "CLST" },
    .{ .value = ELLP, .label = "ELLP", .short_label = "ELLP" },
    .{ .value = DTIL, .label = "DTIL", .short_label = "DTIL" },
    .{ .value = DDQT, .label = "DDQT", .short_label = "DDQT" },
    .{ .value = COPY, .label = "COPY", .short_label = "COPY" },
    .{ .value = SQRT, .label = "SQRT", .short_label = "SQRT" },
    .{ .value = DLQU, .label = "DLQU", .short_label = "DLQU" },
    .{ .value = LEQL, .label = "LEQL", .short_label = "LEQL" },
    .{ .value = GEQL, .label = "GEQL", .short_label = "GEQL" },
    .{ .value = MDSH, .label = "MDSH", .short_label = "MDSH" },
};

pub fn getLabel(keycode: core.KeyCodeFire, shortest: bool) ?[]const u8 {
    return zkc_core.getLabel(&_labels, keycode, shortest);
}
