// Copyright 2026 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by zkeycodes from QMK hjson keycode files
const zkc_core = @import("../src/core.zig");
const core = @import("zigmkay").core;
const L_SFT = zkc_core.L_SFT;
const L_ALT = zkc_core.L_ALT;
const R_ALT = zkc_core.R_ALT;
const R_CTL = zkc_core.R_CTL;
const DEAD = zkc_core.DEAD;
pub const keycodes = @import("keycodes.zig");

pub const QMK_DVORAK_PROGRAMMER_KEYCODES_VERSION = "0.0.1";
pub const QMK_DVORAK_PROGRAMMER_KEYCODES_VERSION_BCD = @as(c_int, 0x00000001);
pub const QMK_DVORAK_PROGRAMMER_KEYCODES_VERSION_MAJOR = @as(c_int, 0);
pub const QMK_DVORAK_PROGRAMMER_KEYCODES_VERSION_MINOR = @as(c_int, 0);
pub const QMK_DVORAK_PROGRAMMER_KEYCODES_VERSION_PATCH = @as(c_int, 1);

//
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ $ │ & │ [ │ { │ } │ ( │ = │ * │ ) │ + │ ] │ ! │ # │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ ; │ , │ . │ P │ Y │ F │ G │ C │ R │ L │ / │ @ │  \  │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
// │      │ A │ O │ E │ U │ I │ D │ H │ T │ N │ S │ - │        │
// ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
// │        │ ' │ Q │ J │ K │ X │ B │ M │ W │ V │ Z │          │
// ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// $
pub const DLR = keycodes.kcf.GRV;
/// &
pub const AMPR = keycodes.kcf.N1;
/// [
pub const LBRC = keycodes.kcf.N2;
/// {
pub const LCBR = keycodes.kcf.N3;
/// }
pub const RCBR = keycodes.kcf.N4;
/// (
pub const LPRN = keycodes.kcf.N5;
/// =
pub const EQL = keycodes.kcf.N6;
/// *
pub const ASTR = keycodes.kcf.N7;
/// )
pub const RPRN = keycodes.kcf.N8;
/// +
pub const PLUS = keycodes.kcf.N9;
/// ]
pub const RBRC = keycodes.kcf.N0;
/// !
pub const EXLM = keycodes.kcf.MINS;
/// #
pub const HASH = keycodes.kcf.EQL;
/// ;
pub const SCLN = keycodes.kcf.Q;
/// ,
pub const COMM = keycodes.kcf.W;
/// .
pub const DOT = keycodes.kcf.E;
/// P
pub const P = keycodes.kcf.R;
/// Y
pub const Y = keycodes.kcf.T;
/// F
pub const F = keycodes.kcf.Y;
/// G
pub const G = keycodes.kcf.U;
/// C
pub const C = keycodes.kcf.I;
/// R
pub const R = keycodes.kcf.O;
/// L
pub const L = keycodes.kcf.P;
/// /
pub const SLSH = keycodes.kcf.LBRC;
/// @
pub const AT = keycodes.kcf.RBRC;
/// (backslash)
pub const BSLS = keycodes.kcf.BSLS;
/// A
pub const A = keycodes.kcf.A;
/// O
pub const O = keycodes.kcf.S;
/// E
pub const E = keycodes.kcf.D;
/// U
pub const U = keycodes.kcf.F;
/// I
pub const I = keycodes.kcf.G;
/// D
pub const D = keycodes.kcf.H;
/// H
pub const H = keycodes.kcf.J;
/// T
pub const T = keycodes.kcf.K;
/// N
pub const N = keycodes.kcf.L;
/// S
pub const S = keycodes.kcf.SCLN;
/// -
pub const MINS = keycodes.kcf.QUOT;
/// '
pub const QUOT = keycodes.kcf.Z;
/// Q
pub const Q = keycodes.kcf.X;
/// J
pub const J = keycodes.kcf.C;
/// K
pub const K = keycodes.kcf.V;
/// X
pub const X = keycodes.kcf.B;
/// B
pub const B = keycodes.kcf.N;
/// M
pub const M = keycodes.kcf.M;
/// W
pub const W = keycodes.kcf.COMM;
/// V
pub const V = keycodes.kcf.DOT;
/// Z
pub const Z = keycodes.kcf.SLSH;
// Shifted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ~ │ % │ 7 │ 5 │ 3 │ 1 │ 9 │ 0 │ 2 │ 4 │ 6 │ 8 │ ` │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ : │ < │ > │   │   │   │   │   │   │   │ ? │ ^ │  |  │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
// │      │   │   │   │   │   │   │   │   │   │   │ _ │        │
// ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
// │        │ " │   │   │   │   │   │   │   │   │   │          │
// ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ~
pub const TILD = L_SFT(DLR);
/// %
pub const PERC = L_SFT(AMPR);
/// 7
pub const N7 = L_SFT(LBRC);
/// 5
pub const N5 = L_SFT(LCBR);
/// 3
pub const N3 = L_SFT(RCBR);
/// 1
pub const N1 = L_SFT(LPRN);
/// 9
pub const N9 = L_SFT(EQL);
/// 0
pub const N0 = L_SFT(ASTR);
/// 2
pub const N2 = L_SFT(RPRN);
/// 4
pub const N4 = L_SFT(PLUS);
/// 6
pub const N6 = L_SFT(RBRC);
/// 8
pub const N8 = L_SFT(EXLM);
/// `
pub const GRV = L_SFT(HASH);
/// :
pub const COLN = L_SFT(SCLN);
/// <
pub const LABK = L_SFT(COMM);
/// >
pub const RABK = L_SFT(DOT);
/// ?
pub const QUES = L_SFT(SLSH);
/// ^
pub const CIRC = L_SFT(AT);
/// |
pub const PIPE = L_SFT(BSLS);
/// _
pub const UNDS = L_SFT(MINS);
/// "
pub const DQUO = L_SFT(QUOT);

// Label lookup table
pub const _labels = [_]zkc_core.LabelEntry{
    .{ .value = DLR, .label = "DLR", .short_label = "DLR" },
    .{ .value = AMPR, .label = "AMPR", .short_label = "AMPR" },
    .{ .value = LBRC, .label = "LBRC", .short_label = "LBRC" },
    .{ .value = LCBR, .label = "LCBR", .short_label = "LCBR" },
    .{ .value = RCBR, .label = "RCBR", .short_label = "RCBR" },
    .{ .value = LPRN, .label = "LPRN", .short_label = "LPRN" },
    .{ .value = EQL, .label = "EQL", .short_label = "EQL" },
    .{ .value = ASTR, .label = "ASTR", .short_label = "ASTR" },
    .{ .value = RPRN, .label = "RPRN", .short_label = "RPRN" },
    .{ .value = PLUS, .label = "PLUS", .short_label = "PLUS" },
    .{ .value = RBRC, .label = "RBRC", .short_label = "RBRC" },
    .{ .value = EXLM, .label = "EXLM", .short_label = "EXLM" },
    .{ .value = HASH, .label = "HASH", .short_label = "HASH" },
    .{ .value = SCLN, .label = "SCLN", .short_label = "SCLN" },
    .{ .value = COMM, .label = "COMM", .short_label = "COMM" },
    .{ .value = DOT, .label = "DOT", .short_label = "DOT" },
    .{ .value = P, .label = "P", .short_label = "P" },
    .{ .value = Y, .label = "Y", .short_label = "Y" },
    .{ .value = F, .label = "F", .short_label = "F" },
    .{ .value = G, .label = "G", .short_label = "G" },
    .{ .value = C, .label = "C", .short_label = "C" },
    .{ .value = R, .label = "R", .short_label = "R" },
    .{ .value = L, .label = "L", .short_label = "L" },
    .{ .value = SLSH, .label = "SLSH", .short_label = "SLSH" },
    .{ .value = AT, .label = "AT", .short_label = "AT" },
    .{ .value = BSLS, .label = "BSLS", .short_label = "BSLS" },
    .{ .value = A, .label = "A", .short_label = "A" },
    .{ .value = O, .label = "O", .short_label = "O" },
    .{ .value = E, .label = "E", .short_label = "E" },
    .{ .value = U, .label = "U", .short_label = "U" },
    .{ .value = I, .label = "I", .short_label = "I" },
    .{ .value = D, .label = "D", .short_label = "D" },
    .{ .value = H, .label = "H", .short_label = "H" },
    .{ .value = T, .label = "T", .short_label = "T" },
    .{ .value = N, .label = "N", .short_label = "N" },
    .{ .value = S, .label = "S", .short_label = "S" },
    .{ .value = MINS, .label = "MINS", .short_label = "MINS" },
    .{ .value = QUOT, .label = "QUOT", .short_label = "QUOT" },
    .{ .value = Q, .label = "Q", .short_label = "Q" },
    .{ .value = J, .label = "J", .short_label = "J" },
    .{ .value = K, .label = "K", .short_label = "K" },
    .{ .value = X, .label = "X", .short_label = "X" },
    .{ .value = B, .label = "B", .short_label = "B" },
    .{ .value = M, .label = "M", .short_label = "M" },
    .{ .value = W, .label = "W", .short_label = "W" },
    .{ .value = V, .label = "V", .short_label = "V" },
    .{ .value = Z, .label = "Z", .short_label = "Z" },
    .{ .value = TILD, .label = "TILD", .short_label = "TILD" },
    .{ .value = PERC, .label = "PERC", .short_label = "PERC" },
    .{ .value = N7, .label = "7", .short_label = "7" },
    .{ .value = N5, .label = "5", .short_label = "5" },
    .{ .value = N3, .label = "3", .short_label = "3" },
    .{ .value = N1, .label = "1", .short_label = "1" },
    .{ .value = N9, .label = "9", .short_label = "9" },
    .{ .value = N0, .label = "0", .short_label = "0" },
    .{ .value = N2, .label = "2", .short_label = "2" },
    .{ .value = N4, .label = "4", .short_label = "4" },
    .{ .value = N6, .label = "6", .short_label = "6" },
    .{ .value = N8, .label = "8", .short_label = "8" },
    .{ .value = GRV, .label = "GRV", .short_label = "GRV" },
    .{ .value = COLN, .label = "COLN", .short_label = "COLN" },
    .{ .value = LABK, .label = "LABK", .short_label = "LABK" },
    .{ .value = RABK, .label = "RABK", .short_label = "RABK" },
    .{ .value = QUES, .label = "QUES", .short_label = "QUES" },
    .{ .value = CIRC, .label = "CIRC", .short_label = "CIRC" },
    .{ .value = PIPE, .label = "PIPE", .short_label = "PIPE" },
    .{ .value = UNDS, .label = "UNDS", .short_label = "UNDS" },
    .{ .value = DQUO, .label = "DQUO", .short_label = "DQUO" },
};

pub fn getLabel(keycode: core.KeyCodeFire, shortest: bool) ?[]const u8 {
    return zkc_core.getLabel(&_labels, keycode, shortest);
}
