// Copyright 2026 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by zkeycodes from QMK hjson keycode files
const zkc_core = @import("../src/core.zig");
const core = @import("zigmkay").core;
const L_SFT = zkc_core.L_SFT;
const L_ALT = zkc_core.L_ALT;
const R_ALT = zkc_core.R_ALT;
const R_CTL = zkc_core.R_CTL;
const DEAD = zkc_core.DEAD;
pub const keycodes = @import("keycodes.zig");

pub const QMK_EURKEY_KEYCODES_VERSION = "0.0.1";
pub const QMK_EURKEY_KEYCODES_VERSION_BCD = @as(c_int, 0x00000001);
pub const QMK_EURKEY_KEYCODES_VERSION_MAJOR = @as(c_int, 0);
pub const QMK_EURKEY_KEYCODES_VERSION_MINOR = @as(c_int, 0);
pub const QMK_EURKEY_KEYCODES_VERSION_PATCH = @as(c_int, 1);

//
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ` │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ - │ = │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │ [ │ ] │  \  │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
// │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ ; │ ' │        │
// ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
// │        │ Z │ X │ C │ V │ B │ N │ M │ , │ . │ / │          │
// ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// `
pub const GRV = keycodes.kcf.GRV;
/// 1
pub const N1 = keycodes.kcf.N1;
/// 2
pub const N2 = keycodes.kcf.N2;
/// 3
pub const N3 = keycodes.kcf.N3;
/// 4
pub const N4 = keycodes.kcf.N4;
/// 5
pub const N5 = keycodes.kcf.N5;
/// 6
pub const N6 = keycodes.kcf.N6;
/// 7
pub const N7 = keycodes.kcf.N7;
/// 8
pub const N8 = keycodes.kcf.N8;
/// 9
pub const N9 = keycodes.kcf.N9;
/// 0
pub const N0 = keycodes.kcf.N0;
/// -
pub const MINS = keycodes.kcf.MINS;
/// =
pub const EQL = keycodes.kcf.EQL;
/// Q
pub const Q = keycodes.kcf.Q;
/// W
pub const W = keycodes.kcf.W;
/// E
pub const E = keycodes.kcf.E;
/// R
pub const R = keycodes.kcf.R;
/// T
pub const T = keycodes.kcf.T;
/// Y
pub const Y = keycodes.kcf.Y;
/// U
pub const U = keycodes.kcf.U;
/// I
pub const I = keycodes.kcf.I;
/// O
pub const O = keycodes.kcf.O;
/// P
pub const P = keycodes.kcf.P;
/// [
pub const LBRC = keycodes.kcf.LBRC;
/// ]
pub const RBRC = keycodes.kcf.RBRC;
/// (backslash)
pub const BSLS = keycodes.kcf.BSLS;
/// A
pub const A = keycodes.kcf.A;
/// S
pub const S = keycodes.kcf.S;
/// D
pub const D = keycodes.kcf.D;
/// F
pub const F = keycodes.kcf.F;
/// G
pub const G = keycodes.kcf.G;
/// H
pub const H = keycodes.kcf.H;
/// J
pub const J = keycodes.kcf.J;
/// K
pub const K = keycodes.kcf.K;
/// L
pub const L = keycodes.kcf.L;
/// ;
pub const SCLN = keycodes.kcf.SCLN;
/// '
pub const QUOT = keycodes.kcf.QUOT;
/// Z
pub const Z = keycodes.kcf.Z;
/// X
pub const X = keycodes.kcf.X;
/// C
pub const C = keycodes.kcf.C;
/// V
pub const V = keycodes.kcf.V;
/// B
pub const B = keycodes.kcf.B;
/// N
pub const N = keycodes.kcf.N;
/// M
pub const M = keycodes.kcf.M;
/// ,
pub const COMM = keycodes.kcf.COMM;
/// .
pub const DOT = keycodes.kcf.DOT;
/// /
pub const SLSH = keycodes.kcf.SLSH;
// Shifted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ~ │ ! │ @ │ # │ $ │ % │ ^ │ & │ * │ ( │ ) │ _ │ + │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │   │   │   │   │   │   │   │   │ { │ } │  |  │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
// │      │   │   │   │   │   │   │   │   │   │ : │ " │        │
// ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
// │        │   │   │   │   │   │   │   │ < │ > │ ? │          │
// ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ~
pub const TILD = L_SFT(GRV);
/// !
pub const EXLM = L_SFT(N1);
/// @
pub const AT = L_SFT(N2);
/// #
pub const HASH = L_SFT(N3);
/// $
pub const DLR = L_SFT(N4);
/// %
pub const PERC = L_SFT(N5);
/// ^
pub const CIRC = L_SFT(N6);
/// &
pub const AMPR = L_SFT(N7);
/// *
pub const ASTR = L_SFT(N8);
/// (
pub const LPRN = L_SFT(N9);
/// )
pub const RPRN = L_SFT(N0);
/// _
pub const UNDS = L_SFT(MINS);
/// +
pub const PLUS = L_SFT(EQL);
/// {
pub const LCBR = L_SFT(LBRC);
/// }
pub const RCBR = L_SFT(RBRC);
/// |
pub const PIPE = L_SFT(BSLS);
/// :
pub const COLN = L_SFT(SCLN);
/// "
pub const DQUO = L_SFT(QUOT);
/// <
pub const LABK = L_SFT(COMM);
/// >
pub const RABK = L_SFT(DOT);
/// ?
pub const QUES = L_SFT(SLSH);
// AltGr symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ` │ ¡ │ ª │ º │ £ │ € │ ^ │ ˚ │ „ │ “ │ ” │ – │ × │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ æ │ å │ ë │ ý │ þ │ ÿ │ ü │ ï │ ö │ œ │ « │ » │  ¬  │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
// │      │ ä │ ß │ ð │ è │ é │ ù │ ú │ ĳ │ ø │ ° │ ´ │        │
// ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
// │        │ à │ á │ ç │ ì │ í │ ñ │ μ │ ò │ ó │ ¿ │          │
// ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ` (dead)
pub const DGRV = DEAD(R_ALT(GRV));
/// ¡
pub const IEXL = R_ALT(N1);
/// ª
pub const FORD = R_ALT(N2);
/// º
pub const MORD = R_ALT(N3);
/// £
pub const PND = R_ALT(N4);
/// €
pub const EURO = R_ALT(N5);
/// ^ (dead)
pub const DCIR = DEAD(R_ALT(N6));
/// ˚ (dead)
pub const RNGA = DEAD(R_ALT(N7));
/// „
pub const DLQU = R_ALT(N8);
/// “
pub const LDQU = R_ALT(N9);
/// ”
pub const RDQU = R_ALT(N0);
/// –
pub const NDSH = R_ALT(MINS);
/// ×
pub const MUL = R_ALT(EQL);
/// æ
pub const AE = R_ALT(Q);
/// Å
pub const ARNG = R_ALT(W);
/// Ë
pub const EDIA = R_ALT(E);
/// Ý
pub const YACU = R_ALT(R);
/// Þ
pub const THRN = R_ALT(T);
/// Ÿ
pub const YDIA = R_ALT(Y);
/// Ü
pub const UDIA = R_ALT(U);
/// Ï
pub const IDIA = R_ALT(I);
/// Ö
pub const ODIA = R_ALT(O);
/// Œ
pub const OE = R_ALT(P);
/// «
pub const LDAQ = R_ALT(LBRC);
/// »
pub const RDAQ = R_ALT(RBRC);
/// ¬
pub const NOT = R_ALT(BSLS);
/// Ä
pub const ADIA = R_ALT(A);
/// ß
pub const SS = R_ALT(S);
/// Ð
pub const ETH = R_ALT(D);
/// È
pub const EGRV = R_ALT(F);
/// É
pub const EACU = R_ALT(G);
/// Ù
pub const UGRV = R_ALT(H);
/// Ú
pub const UACU = R_ALT(J);
/// Ĳ
pub const IJ = R_ALT(K);
/// Ø
pub const OSTR = R_ALT(L);
/// °
pub const DEG = R_ALT(SCLN);
/// ´ (dead)
pub const ACUT = DEAD(R_ALT(QUOT));
/// À
pub const AGRV = R_ALT(Z);
/// Á
pub const AACU = R_ALT(X);
/// Ç
pub const CCED = R_ALT(C);
/// Ì
pub const IGRV = R_ALT(V);
/// Í
pub const IACU = R_ALT(B);
/// Ñ
pub const NTIL = R_ALT(N);
/// μ (dead Greek key)
pub const DGRK = R_ALT(M);
/// Ò
pub const OGRV = R_ALT(COMM);
/// Ó
pub const OACU = R_ALT(DOT);
/// ¿
pub const IQUE = R_ALT(SLSH);
// Shift+AltGr symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ~ │ ¹ │ ² │ ³ │ ¥ │ ¢ │ ˇ │ ¯ │ ‚ │ ‘ │ ’ │ — │ ÷ │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │   │   │   │   │   │   │   │   │ ‹ │ › │  ¦  │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
// │      │   │ § │   │   │   │   │   │   │   │ · │ ¨ │        │
// ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
// │        │   │   │   │   │   │   │   │   │   │ … │          │
// ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ~ (dead)
pub const DTIL = DEAD(R_ALT(TILD));
/// ¹
pub const SUP1 = L_SFT(R_ALT(N1));
/// ²
pub const SUP2 = L_SFT(R_ALT(N2));
/// ³
pub const SUP3 = L_SFT(R_ALT(N3));
/// ¥
pub const YEN = R_ALT(DLR);
/// ¢
pub const CENT = L_SFT(EURO);
/// ˇ (dead)
pub const CARN = DEAD(L_SFT(DCIR));
/// ¯ (dead)
pub const MACR = DEAD(L_SFT(R_ALT(N7)));
/// ‚
pub const SLQU = L_SFT(DLQU);
/// ‘
pub const LSQU = L_SFT(LDQU);
/// ’
pub const RSQU = L_SFT(RDQU);
/// —
pub const MDSH = L_SFT(NDSH);
/// ÷
pub const DIV = L_SFT(MUL);
/// ‹
pub const LSAQ = L_SFT(LDAQ);
/// ›
pub const RSAQ = L_SFT(RDAQ);
/// ¦
pub const BRKP = L_SFT(R_ALT(BSLS));
/// §
pub const SECT = L_SFT(R_ALT(S));
/// ·
pub const MDDT = L_SFT(R_ALT(SCLN));
/// ¨ (dead)
pub const DIAE = DEAD(R_ALT(DQUO));
/// …
pub const ELLP = R_ALT(QUES);

// Label lookup table
pub const _labels = [_]zkc_core.LabelEntry{
    .{ .value = GRV, .label = "GRV", .short_label = "GRV" },
    .{ .value = N1, .label = "1", .short_label = "1" },
    .{ .value = N2, .label = "2", .short_label = "2" },
    .{ .value = N3, .label = "3", .short_label = "3" },
    .{ .value = N4, .label = "4", .short_label = "4" },
    .{ .value = N5, .label = "5", .short_label = "5" },
    .{ .value = N6, .label = "6", .short_label = "6" },
    .{ .value = N7, .label = "7", .short_label = "7" },
    .{ .value = N8, .label = "8", .short_label = "8" },
    .{ .value = N9, .label = "9", .short_label = "9" },
    .{ .value = N0, .label = "0", .short_label = "0" },
    .{ .value = MINS, .label = "MINS", .short_label = "MINS" },
    .{ .value = EQL, .label = "EQL", .short_label = "EQL" },
    .{ .value = Q, .label = "Q", .short_label = "Q" },
    .{ .value = W, .label = "W", .short_label = "W" },
    .{ .value = E, .label = "E", .short_label = "E" },
    .{ .value = R, .label = "R", .short_label = "R" },
    .{ .value = T, .label = "T", .short_label = "T" },
    .{ .value = Y, .label = "Y", .short_label = "Y" },
    .{ .value = U, .label = "U", .short_label = "U" },
    .{ .value = I, .label = "I", .short_label = "I" },
    .{ .value = O, .label = "O", .short_label = "O" },
    .{ .value = P, .label = "P", .short_label = "P" },
    .{ .value = LBRC, .label = "LBRC", .short_label = "LBRC" },
    .{ .value = RBRC, .label = "RBRC", .short_label = "RBRC" },
    .{ .value = BSLS, .label = "BSLS", .short_label = "BSLS" },
    .{ .value = A, .label = "A", .short_label = "A" },
    .{ .value = S, .label = "S", .short_label = "S" },
    .{ .value = D, .label = "D", .short_label = "D" },
    .{ .value = F, .label = "F", .short_label = "F" },
    .{ .value = G, .label = "G", .short_label = "G" },
    .{ .value = H, .label = "H", .short_label = "H" },
    .{ .value = J, .label = "J", .short_label = "J" },
    .{ .value = K, .label = "K", .short_label = "K" },
    .{ .value = L, .label = "L", .short_label = "L" },
    .{ .value = SCLN, .label = "SCLN", .short_label = "SCLN" },
    .{ .value = QUOT, .label = "QUOT", .short_label = "QUOT" },
    .{ .value = Z, .label = "Z", .short_label = "Z" },
    .{ .value = X, .label = "X", .short_label = "X" },
    .{ .value = C, .label = "C", .short_label = "C" },
    .{ .value = V, .label = "V", .short_label = "V" },
    .{ .value = B, .label = "B", .short_label = "B" },
    .{ .value = N, .label = "N", .short_label = "N" },
    .{ .value = M, .label = "M", .short_label = "M" },
    .{ .value = COMM, .label = "COMM", .short_label = "COMM" },
    .{ .value = DOT, .label = "DOT", .short_label = "DOT" },
    .{ .value = SLSH, .label = "SLSH", .short_label = "SLSH" },
    .{ .value = TILD, .label = "TILD", .short_label = "TILD" },
    .{ .value = EXLM, .label = "EXLM", .short_label = "EXLM" },
    .{ .value = AT, .label = "AT", .short_label = "AT" },
    .{ .value = HASH, .label = "HASH", .short_label = "HASH" },
    .{ .value = DLR, .label = "DLR", .short_label = "DLR" },
    .{ .value = PERC, .label = "PERC", .short_label = "PERC" },
    .{ .value = CIRC, .label = "CIRC", .short_label = "CIRC" },
    .{ .value = AMPR, .label = "AMPR", .short_label = "AMPR" },
    .{ .value = ASTR, .label = "ASTR", .short_label = "ASTR" },
    .{ .value = LPRN, .label = "LPRN", .short_label = "LPRN" },
    .{ .value = RPRN, .label = "RPRN", .short_label = "RPRN" },
    .{ .value = UNDS, .label = "UNDS", .short_label = "UNDS" },
    .{ .value = PLUS, .label = "PLUS", .short_label = "PLUS" },
    .{ .value = LCBR, .label = "LCBR", .short_label = "LCBR" },
    .{ .value = RCBR, .label = "RCBR", .short_label = "RCBR" },
    .{ .value = PIPE, .label = "PIPE", .short_label = "PIPE" },
    .{ .value = COLN, .label = "COLN", .short_label = "COLN" },
    .{ .value = DQUO, .label = "DQUO", .short_label = "DQUO" },
    .{ .value = LABK, .label = "LABK", .short_label = "LABK" },
    .{ .value = RABK, .label = "RABK", .short_label = "RABK" },
    .{ .value = QUES, .label = "QUES", .short_label = "QUES" },
    .{ .value = DGRV, .label = "DGRV", .short_label = "DGRV" },
    .{ .value = IEXL, .label = "IEXL", .short_label = "IEXL" },
    .{ .value = FORD, .label = "FORD", .short_label = "FORD" },
    .{ .value = MORD, .label = "MORD", .short_label = "MORD" },
    .{ .value = PND, .label = "PND", .short_label = "PND" },
    .{ .value = EURO, .label = "EURO", .short_label = "EURO" },
    .{ .value = DCIR, .label = "DCIR", .short_label = "DCIR" },
    .{ .value = RNGA, .label = "RNGA", .short_label = "RNGA" },
    .{ .value = DLQU, .label = "DLQU", .short_label = "DLQU" },
    .{ .value = LDQU, .label = "LDQU", .short_label = "LDQU" },
    .{ .value = RDQU, .label = "RDQU", .short_label = "RDQU" },
    .{ .value = NDSH, .label = "NDSH", .short_label = "NDSH" },
    .{ .value = MUL, .label = "MUL", .short_label = "MUL" },
    .{ .value = AE, .label = "AE", .short_label = "AE" },
    .{ .value = ARNG, .label = "ARNG", .short_label = "ARNG" },
    .{ .value = EDIA, .label = "EDIA", .short_label = "EDIA" },
    .{ .value = YACU, .label = "YACU", .short_label = "YACU" },
    .{ .value = THRN, .label = "THRN", .short_label = "THRN" },
    .{ .value = YDIA, .label = "YDIA", .short_label = "YDIA" },
    .{ .value = UDIA, .label = "UDIA", .short_label = "UDIA" },
    .{ .value = IDIA, .label = "IDIA", .short_label = "IDIA" },
    .{ .value = ODIA, .label = "ODIA", .short_label = "ODIA" },
    .{ .value = OE, .label = "OE", .short_label = "OE" },
    .{ .value = LDAQ, .label = "LDAQ", .short_label = "LDAQ" },
    .{ .value = RDAQ, .label = "RDAQ", .short_label = "RDAQ" },
    .{ .value = NOT, .label = "NOT", .short_label = "NOT" },
    .{ .value = ADIA, .label = "ADIA", .short_label = "ADIA" },
    .{ .value = SS, .label = "SS", .short_label = "SS" },
    .{ .value = ETH, .label = "ETH", .short_label = "ETH" },
    .{ .value = EGRV, .label = "EGRV", .short_label = "EGRV" },
    .{ .value = EACU, .label = "EACU", .short_label = "EACU" },
    .{ .value = UGRV, .label = "UGRV", .short_label = "UGRV" },
    .{ .value = UACU, .label = "UACU", .short_label = "UACU" },
    .{ .value = IJ, .label = "IJ", .short_label = "IJ" },
    .{ .value = OSTR, .label = "OSTR", .short_label = "OSTR" },
    .{ .value = DEG, .label = "DEG", .short_label = "DEG" },
    .{ .value = ACUT, .label = "ACUT", .short_label = "ACUT" },
    .{ .value = AGRV, .label = "AGRV", .short_label = "AGRV" },
    .{ .value = AACU, .label = "AACU", .short_label = "AACU" },
    .{ .value = CCED, .label = "CCED", .short_label = "CCED" },
    .{ .value = IGRV, .label = "IGRV", .short_label = "IGRV" },
    .{ .value = IACU, .label = "IACU", .short_label = "IACU" },
    .{ .value = NTIL, .label = "NTIL", .short_label = "NTIL" },
    .{ .value = DGRK, .label = "DGRK", .short_label = "DGRK" },
    .{ .value = OGRV, .label = "OGRV", .short_label = "OGRV" },
    .{ .value = OACU, .label = "OACU", .short_label = "OACU" },
    .{ .value = IQUE, .label = "IQUE", .short_label = "IQUE" },
    .{ .value = DTIL, .label = "DTIL", .short_label = "DTIL" },
    .{ .value = SUP1, .label = "SUP1", .short_label = "SUP1" },
    .{ .value = SUP2, .label = "SUP2", .short_label = "SUP2" },
    .{ .value = SUP3, .label = "SUP3", .short_label = "SUP3" },
    .{ .value = YEN, .label = "YEN", .short_label = "YEN" },
    .{ .value = CENT, .label = "CENT", .short_label = "CENT" },
    .{ .value = CARN, .label = "CARN", .short_label = "CARN" },
    .{ .value = MACR, .label = "MACR", .short_label = "MACR" },
    .{ .value = SLQU, .label = "SLQU", .short_label = "SLQU" },
    .{ .value = LSQU, .label = "LSQU", .short_label = "LSQU" },
    .{ .value = RSQU, .label = "RSQU", .short_label = "RSQU" },
    .{ .value = MDSH, .label = "MDSH", .short_label = "MDSH" },
    .{ .value = DIV, .label = "DIV", .short_label = "DIV" },
    .{ .value = LSAQ, .label = "LSAQ", .short_label = "LSAQ" },
    .{ .value = RSAQ, .label = "RSAQ", .short_label = "RSAQ" },
    .{ .value = BRKP, .label = "BRKP", .short_label = "BRKP" },
    .{ .value = SECT, .label = "SECT", .short_label = "SECT" },
    .{ .value = MDDT, .label = "MDDT", .short_label = "MDDT" },
    .{ .value = DIAE, .label = "DIAE", .short_label = "DIAE" },
    .{ .value = ELLP, .label = "ELLP", .short_label = "ELLP" },
};

pub fn getLabel(keycode: core.KeyCodeFire, shortest: bool) ?[]const u8 {
    return zkc_core.getLabel(&_labels, keycode, shortest);
}
