// Copyright 2026 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by zkeycodes from QMK hjson keycode files
const zkc_core = @import("../src/core.zig");
const core = @import("zigmkay").core;
const L_SFT = zkc_core.L_SFT;
const L_ALT = zkc_core.L_ALT;
const R_ALT = zkc_core.R_ALT;
const R_CTL = zkc_core.R_CTL;
const DEAD = zkc_core.DEAD;
pub const keycodes = @import("keycodes.zig");

pub const QMK_FARSI_KEYCODES_VERSION = "0.0.1";
pub const QMK_FARSI_KEYCODES_VERSION_BCD = @as(c_int, 0x00000001);
pub const QMK_FARSI_KEYCODES_VERSION_MAJOR = @as(c_int, 0);
pub const QMK_FARSI_KEYCODES_VERSION_MINOR = @as(c_int, 0);
pub const QMK_FARSI_KEYCODES_VERSION_PATCH = @as(c_int, 1);

//
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │   │ ۱ │ ۲ │ ۳ │ ۴ │ ۵ │ ۶ │ ۷ │ ۸ │ ۹ │ ۰ │ - │ = │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ ض │ ص │ ث │ ق │ ف │ غ │ ع │ ه │ خ │ ح │ ج │ چ │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │ ش │ س │ ی │ ب │ ل │ ا │ ت │ ن │ م │ ک │ گ │ \ │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ < │ ظ │ ط │ ز │ ر │ ذ │ د │ پ │ و │ . │ / │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// (zero-width joiner)
pub const ZWJ = keycodes.kcf.GRV;
/// ۱
pub const N1A = keycodes.kcf.N1;
/// ۲
pub const N2A = keycodes.kcf.N2;
/// ۳
pub const N3A = keycodes.kcf.N3;
/// ۴
pub const N4A = keycodes.kcf.N4;
/// ۵
pub const N5A = keycodes.kcf.N5;
/// ۶
pub const N6A = keycodes.kcf.N6;
/// ۷
pub const N7A = keycodes.kcf.N7;
/// ۸
pub const N8A = keycodes.kcf.N8;
/// ۹
pub const N9A = keycodes.kcf.N9;
/// ۰
pub const N0A = keycodes.kcf.N0;
/// -
pub const MINS = keycodes.kcf.MINS;
/// =
pub const EQL = keycodes.kcf.EQL;
/// ض
pub const ZAD = keycodes.kcf.Q;
/// ص
pub const SAD = keycodes.kcf.W;
/// ث
pub const SE = keycodes.kcf.E;
/// ق
pub const QAF = keycodes.kcf.R;
/// ف
pub const FE = keycodes.kcf.T;
/// غ
pub const GHYN = keycodes.kcf.Y;
/// ع
pub const EYN = keycodes.kcf.U;
/// ه
pub const HE = keycodes.kcf.I;
/// خ
pub const KHE = keycodes.kcf.O;
/// ح
pub const HEJ = keycodes.kcf.P;
/// ج
pub const JIM = keycodes.kcf.LBRC;
/// چ
pub const CHE = keycodes.kcf.RBRC;
/// ش
pub const SHIN = keycodes.kcf.A;
/// س
pub const SIN = keycodes.kcf.S;
/// ی
pub const YE = keycodes.kcf.D;
/// ب
pub const BE = keycodes.kcf.F;
/// ل
pub const LAM = keycodes.kcf.G;
/// ا
pub const ALEF = keycodes.kcf.H;
/// ت
pub const TE = keycodes.kcf.J;
/// ن
pub const NOON = keycodes.kcf.K;
/// م
pub const MIM = keycodes.kcf.L;
/// ک
pub const KAF = keycodes.kcf.SCLN;
/// گ
pub const GAF = keycodes.kcf.QUOT;
/// (backslash)
pub const BSLS = keycodes.kcf.BSLS;
/// <
pub const LT = keycodes.kcf.LT;
/// ظ
pub const ZA = keycodes.kcf.Z;
/// ط
pub const TA = keycodes.kcf.X;
/// ز
pub const ZE = keycodes.kcf.C;
/// ر
pub const RE = keycodes.kcf.V;
/// ذ
pub const ZAL = keycodes.kcf.B;
/// د
pub const DAL = keycodes.kcf.N;
/// پ
pub const PE = keycodes.kcf.M;
/// و
pub const WAW = keycodes.kcf.COMM;
/// .
pub const DOT = keycodes.kcf.DOT;
/// /
pub const SLSH = keycodes.kcf.SLSH;
///  
pub const SPC = keycodes.kcf.SPC;
// Shifted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ÷ │ ! │ ٬ │ ٫ │ ﷼ │ ٪ │ × │ ، │ * │ ) │ ( │ ـ │ + │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │  ْ │  ٌ │  ٍ │  ً │  ُ │  ِ │  َ │  ّ │ ] │ [ │ } │ { │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │ ؤ │ ئ │ ي │ إ │ أ │ آ │ ة │ » │ « │ : │ ؛ │ | │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ > │ ك │  ٓ │ ژ │ ٰ  │   │  ٔ │ ء │   │   │ ؟ │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ÷
pub const DIV = L_SFT(ZWJ);
/// !
pub const EXLM = L_SFT(N1A);
/// ٬
pub const THS = L_SFT(N2A);
/// ٫
pub const DECS = L_SFT(N3A);
/// ﷼
pub const RIAL = L_SFT(N4A);
/// ٪
pub const PRCA = L_SFT(N5A);
/// ×
pub const MUL = L_SFT(N6A);
/// ،
pub const COMA = L_SFT(N7A);
/// *
pub const ASTR = L_SFT(N8A);
/// )
pub const RPRN = L_SFT(N9A);
/// (
pub const LPRN = L_SFT(N0A);
/// ـ
pub const TATW = L_SFT(MINS);
/// +
pub const PLUS = L_SFT(EQL);
/// ْ
pub const SUK = L_SFT(ZAD);
/// ٌ
pub const DMTN = L_SFT(SAD);
/// ٍ
pub const KSTN = L_SFT(SE);
/// ً
pub const FTHN = L_SFT(QAF);
/// ُ
pub const DMM = L_SFT(FE);
/// ِ
pub const KAS = L_SFT(GHYN);
/// َ
pub const FAT = L_SFT(EYN);
pub const TSDD = L_SFT(HE);
/// ]
pub const RBRC = L_SFT(KHE);
/// [
pub const LBRC = L_SFT(HEJ);
/// }
pub const RCBR = L_SFT(JIM);
/// {
pub const LCBR = L_SFT(CHE);
/// ؤ
pub const HMZV = L_SFT(SHIN);
/// ئ
pub const HMZY = L_SFT(SIN);
/// ي
pub const YEA = L_SFT(YE);
/// إ
pub const HMZU = L_SFT(BE);
/// أ
pub const HMZO = L_SFT(LAM);
/// آ
pub const MALF = L_SFT(ALEF);
/// ة
pub const TEHM = L_SFT(TE);
/// »
pub const RQOT = L_SFT(NOON);
/// «
pub const LQOT = L_SFT(MIM);
/// :
pub const COLN = L_SFT(KAF);
/// ؛
pub const SCLA = L_SFT(GAF);
/// >
pub const GT = L_SFT(LT);
/// ك
pub const KAFA = L_SFT(ZA);
/// ٓ
pub const MADO = L_SFT(TA);
/// ژ
pub const JEH = L_SFT(ZE);
/// ٰ
pub const SUPA = L_SFT(RE);
/// (zero-width non-joiner)
pub const ZWNJ = L_SFT(ZAL);
/// ٔ
pub const HMZA = L_SFT(DAL);
/// ء
pub const HMZ = L_SFT(PE);
/// ؟
pub const QSA = L_SFT(SLSH);
// AltGr symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ~ │ ` │ @ │ # │ $ │ % │ ^ │ & │ • │   │   │ _ │ − │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ ° │   │ € │   │   │   │   │   │   │   │   │   │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │   │   │ ى │   │   │ ٱ │   │ ﴾ │ ﴿ │ ; │ " │ ‐ │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ | │   │   │   │  ٖ │   │  ٕ │ … │ , │ ' │ ? │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ~
pub const TILD = R_ALT(ZWJ);
/// `
pub const GRV = R_ALT(N1A);
/// @
pub const AT = R_ALT(N2A);
/// #
pub const HASH = R_ALT(N3A);
/// $
pub const DLR = R_ALT(N4A);
/// %
pub const PERC = R_ALT(N5A);
/// ^
pub const CIRC = R_ALT(N6A);
/// &
pub const AMPR = R_ALT(N7A);
/// •
pub const BULT = R_ALT(N8A);
/// (left-to-right mark)
pub const LRM = R_ALT(N9A);
/// (right-to-left mark)
pub const RLM = R_ALT(N0A);
/// _
pub const UNDS = R_ALT(MINS);
/// − (dead)
pub const DMNS = DEAD(R_ALT(EQL));
/// °
pub const DEG = R_ALT(ZAD);
/// €
pub const EURO = R_ALT(SE);
/// (left-to-right override)
pub const LRO = R_ALT(HE);
/// (right-to-left override)
pub const RLO = R_ALT(KHE);
/// (pop directional formatting)
pub const PDF = R_ALT(HEJ);
/// (left-to-right embedding)
pub const LRE = R_ALT(JIM);
/// (right-to-left embedding)
pub const RLE = R_ALT(CHE);
/// ى
pub const ALFM = R_ALT(YE);
/// ٱ
pub const ALFW = R_ALT(ALEF);
/// ﴾
pub const LORP = R_ALT(NOON);
/// ﴿
pub const RORP = R_ALT(MIM);
/// ;
pub const SCLN = R_ALT(KAF);
/// "
pub const DQT = R_ALT(GAF);
/// -
pub const MINA = R_ALT(BSLS);
/// |
pub const PIPE = R_ALT(ZA);
/// ٖ
pub const SUBA = R_ALT(RE);
/// ء
pub const HMZB = R_ALT(DAL);
/// …
pub const ELLP = R_ALT(PE);
/// ,
pub const COMM = R_ALT(WAW);
/// '
pub const QUOT = R_ALT(DOT);
/// ?
pub const QUES = R_ALT(SLSH);
// Shift+AltGr symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │   │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │   │   │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │   │   │   │   │   │   │   │   │   │   │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │   │   │   │   │   │   │   │   │   │   │   │   │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ ¦ │   │   │   │   │   │   │   │   │   │   │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// 1
pub const N1 = L_SFT(R_ALT(N1A));
/// 2
pub const N2 = L_SFT(R_ALT(N2A));
/// 3
pub const N3 = L_SFT(R_ALT(N3A));
/// 4
pub const N4 = L_SFT(R_ALT(N4A));
/// 5
pub const N5 = L_SFT(R_ALT(N5A));
/// 6
pub const N6 = L_SFT(R_ALT(N6A));
/// 7
pub const N7 = L_SFT(R_ALT(N7A));
/// 8
pub const N8 = L_SFT(R_ALT(N8A));
/// 9
pub const N9 = L_SFT(R_ALT(N9A));
/// 0
pub const N0 = L_SFT(R_ALT(N0A));
/// ¦
pub const BRKP = L_SFT(R_ALT(LT));
/// (narrow non-breaking space)
pub const NNBS = L_SFT(R_ALT(SPC));

// Label lookup table
pub const _labels = [_]zkc_core.LabelEntry{
    .{ .value = ZWJ, .label = "ZWJ", .short_label = "ZWJ" },
    .{ .value = N1A, .label = "1A", .short_label = "1A" },
    .{ .value = N2A, .label = "2A", .short_label = "2A" },
    .{ .value = N3A, .label = "3A", .short_label = "3A" },
    .{ .value = N4A, .label = "4A", .short_label = "4A" },
    .{ .value = N5A, .label = "5A", .short_label = "5A" },
    .{ .value = N6A, .label = "6A", .short_label = "6A" },
    .{ .value = N7A, .label = "7A", .short_label = "7A" },
    .{ .value = N8A, .label = "8A", .short_label = "8A" },
    .{ .value = N9A, .label = "9A", .short_label = "9A" },
    .{ .value = N0A, .label = "0A", .short_label = "0A" },
    .{ .value = MINS, .label = "MINS", .short_label = "MINS" },
    .{ .value = EQL, .label = "EQL", .short_label = "EQL" },
    .{ .value = ZAD, .label = "ZAD", .short_label = "ZAD" },
    .{ .value = SAD, .label = "SAD", .short_label = "SAD" },
    .{ .value = SE, .label = "SE", .short_label = "SE" },
    .{ .value = QAF, .label = "QAF", .short_label = "QAF" },
    .{ .value = FE, .label = "FE", .short_label = "FE" },
    .{ .value = GHYN, .label = "GHYN", .short_label = "GHYN" },
    .{ .value = EYN, .label = "EYN", .short_label = "EYN" },
    .{ .value = HE, .label = "HE", .short_label = "HE" },
    .{ .value = KHE, .label = "KHE", .short_label = "KHE" },
    .{ .value = HEJ, .label = "HEJ", .short_label = "HEJ" },
    .{ .value = JIM, .label = "JIM", .short_label = "JIM" },
    .{ .value = CHE, .label = "CHE", .short_label = "CHE" },
    .{ .value = SHIN, .label = "SHIN", .short_label = "SHIN" },
    .{ .value = SIN, .label = "SIN", .short_label = "SIN" },
    .{ .value = YE, .label = "YE", .short_label = "YE" },
    .{ .value = BE, .label = "BE", .short_label = "BE" },
    .{ .value = LAM, .label = "LAM", .short_label = "LAM" },
    .{ .value = ALEF, .label = "ALEF", .short_label = "ALEF" },
    .{ .value = TE, .label = "TE", .short_label = "TE" },
    .{ .value = NOON, .label = "NOON", .short_label = "NOON" },
    .{ .value = MIM, .label = "MIM", .short_label = "MIM" },
    .{ .value = KAF, .label = "KAF", .short_label = "KAF" },
    .{ .value = GAF, .label = "GAF", .short_label = "GAF" },
    .{ .value = BSLS, .label = "BSLS", .short_label = "BSLS" },
    .{ .value = LT, .label = "LT", .short_label = "LT" },
    .{ .value = ZA, .label = "ZA", .short_label = "ZA" },
    .{ .value = TA, .label = "TA", .short_label = "TA" },
    .{ .value = ZE, .label = "ZE", .short_label = "ZE" },
    .{ .value = RE, .label = "RE", .short_label = "RE" },
    .{ .value = ZAL, .label = "ZAL", .short_label = "ZAL" },
    .{ .value = DAL, .label = "DAL", .short_label = "DAL" },
    .{ .value = PE, .label = "PE", .short_label = "PE" },
    .{ .value = WAW, .label = "WAW", .short_label = "WAW" },
    .{ .value = DOT, .label = "DOT", .short_label = "DOT" },
    .{ .value = SLSH, .label = "SLSH", .short_label = "SLSH" },
    .{ .value = SPC, .label = "SPC", .short_label = "SPC" },
    .{ .value = DIV, .label = "DIV", .short_label = "DIV" },
    .{ .value = EXLM, .label = "EXLM", .short_label = "EXLM" },
    .{ .value = THS, .label = "THS", .short_label = "THS" },
    .{ .value = DECS, .label = "DECS", .short_label = "DECS" },
    .{ .value = RIAL, .label = "RIAL", .short_label = "RIAL" },
    .{ .value = PRCA, .label = "PRCA", .short_label = "PRCA" },
    .{ .value = MUL, .label = "MUL", .short_label = "MUL" },
    .{ .value = COMA, .label = "COMA", .short_label = "COMA" },
    .{ .value = ASTR, .label = "ASTR", .short_label = "ASTR" },
    .{ .value = RPRN, .label = "RPRN", .short_label = "RPRN" },
    .{ .value = LPRN, .label = "LPRN", .short_label = "LPRN" },
    .{ .value = TATW, .label = "TATW", .short_label = "TATW" },
    .{ .value = PLUS, .label = "PLUS", .short_label = "PLUS" },
    .{ .value = SUK, .label = "SUK", .short_label = "SUK" },
    .{ .value = DMTN, .label = "DMTN", .short_label = "DMTN" },
    .{ .value = KSTN, .label = "KSTN", .short_label = "KSTN" },
    .{ .value = FTHN, .label = "FTHN", .short_label = "FTHN" },
    .{ .value = DMM, .label = "DMM", .short_label = "DMM" },
    .{ .value = KAS, .label = "KAS", .short_label = "KAS" },
    .{ .value = FAT, .label = "FAT", .short_label = "FAT" },
    .{ .value = TSDD, .label = "TSDD", .short_label = "TSDD" },
    .{ .value = RBRC, .label = "RBRC", .short_label = "RBRC" },
    .{ .value = LBRC, .label = "LBRC", .short_label = "LBRC" },
    .{ .value = RCBR, .label = "RCBR", .short_label = "RCBR" },
    .{ .value = LCBR, .label = "LCBR", .short_label = "LCBR" },
    .{ .value = HMZV, .label = "HMZV", .short_label = "HMZV" },
    .{ .value = HMZY, .label = "HMZY", .short_label = "HMZY" },
    .{ .value = YEA, .label = "YEA", .short_label = "YEA" },
    .{ .value = HMZU, .label = "HMZU", .short_label = "HMZU" },
    .{ .value = HMZO, .label = "HMZO", .short_label = "HMZO" },
    .{ .value = MALF, .label = "MALF", .short_label = "MALF" },
    .{ .value = TEHM, .label = "TEHM", .short_label = "TEHM" },
    .{ .value = RQOT, .label = "RQOT", .short_label = "RQOT" },
    .{ .value = LQOT, .label = "LQOT", .short_label = "LQOT" },
    .{ .value = COLN, .label = "COLN", .short_label = "COLN" },
    .{ .value = SCLA, .label = "SCLA", .short_label = "SCLA" },
    .{ .value = GT, .label = "GT", .short_label = "GT" },
    .{ .value = KAFA, .label = "KAFA", .short_label = "KAFA" },
    .{ .value = MADO, .label = "MADO", .short_label = "MADO" },
    .{ .value = JEH, .label = "JEH", .short_label = "JEH" },
    .{ .value = SUPA, .label = "SUPA", .short_label = "SUPA" },
    .{ .value = ZWNJ, .label = "ZWNJ", .short_label = "ZWNJ" },
    .{ .value = HMZA, .label = "HMZA", .short_label = "HMZA" },
    .{ .value = HMZ, .label = "HMZ", .short_label = "HMZ" },
    .{ .value = QSA, .label = "QSA", .short_label = "QSA" },
    .{ .value = TILD, .label = "TILD", .short_label = "TILD" },
    .{ .value = GRV, .label = "GRV", .short_label = "GRV" },
    .{ .value = AT, .label = "AT", .short_label = "AT" },
    .{ .value = HASH, .label = "HASH", .short_label = "HASH" },
    .{ .value = DLR, .label = "DLR", .short_label = "DLR" },
    .{ .value = PERC, .label = "PERC", .short_label = "PERC" },
    .{ .value = CIRC, .label = "CIRC", .short_label = "CIRC" },
    .{ .value = AMPR, .label = "AMPR", .short_label = "AMPR" },
    .{ .value = BULT, .label = "BULT", .short_label = "BULT" },
    .{ .value = LRM, .label = "LRM", .short_label = "LRM" },
    .{ .value = RLM, .label = "RLM", .short_label = "RLM" },
    .{ .value = UNDS, .label = "UNDS", .short_label = "UNDS" },
    .{ .value = DMNS, .label = "DMNS", .short_label = "DMNS" },
    .{ .value = DEG, .label = "DEG", .short_label = "DEG" },
    .{ .value = EURO, .label = "EURO", .short_label = "EURO" },
    .{ .value = LRO, .label = "LRO", .short_label = "LRO" },
    .{ .value = RLO, .label = "RLO", .short_label = "RLO" },
    .{ .value = PDF, .label = "PDF", .short_label = "PDF" },
    .{ .value = LRE, .label = "LRE", .short_label = "LRE" },
    .{ .value = RLE, .label = "RLE", .short_label = "RLE" },
    .{ .value = ALFM, .label = "ALFM", .short_label = "ALFM" },
    .{ .value = ALFW, .label = "ALFW", .short_label = "ALFW" },
    .{ .value = LORP, .label = "LORP", .short_label = "LORP" },
    .{ .value = RORP, .label = "RORP", .short_label = "RORP" },
    .{ .value = SCLN, .label = "SCLN", .short_label = "SCLN" },
    .{ .value = DQT, .label = "DQT", .short_label = "DQT" },
    .{ .value = MINA, .label = "MINA", .short_label = "MINA" },
    .{ .value = PIPE, .label = "PIPE", .short_label = "PIPE" },
    .{ .value = SUBA, .label = "SUBA", .short_label = "SUBA" },
    .{ .value = HMZB, .label = "HMZB", .short_label = "HMZB" },
    .{ .value = ELLP, .label = "ELLP", .short_label = "ELLP" },
    .{ .value = COMM, .label = "COMM", .short_label = "COMM" },
    .{ .value = QUOT, .label = "QUOT", .short_label = "QUOT" },
    .{ .value = QUES, .label = "QUES", .short_label = "QUES" },
    .{ .value = N1, .label = "1", .short_label = "1" },
    .{ .value = N2, .label = "2", .short_label = "2" },
    .{ .value = N3, .label = "3", .short_label = "3" },
    .{ .value = N4, .label = "4", .short_label = "4" },
    .{ .value = N5, .label = "5", .short_label = "5" },
    .{ .value = N6, .label = "6", .short_label = "6" },
    .{ .value = N7, .label = "7", .short_label = "7" },
    .{ .value = N8, .label = "8", .short_label = "8" },
    .{ .value = N9, .label = "9", .short_label = "9" },
    .{ .value = N0, .label = "0", .short_label = "0" },
    .{ .value = BRKP, .label = "BRKP", .short_label = "BRKP" },
    .{ .value = NNBS, .label = "NNBS", .short_label = "NNBS" },
};

pub fn getLabel(keycode: core.KeyCodeFire, shortest: bool) ?[]const u8 {
    return zkc_core.getLabel(&_labels, keycode, shortest);
}
