// Copyright 2026 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by zkeycodes from QMK hjson keycode files
const zkc_core = @import("../src/core.zig");
const core = @import("zigmkay").core;
const L_SFT = zkc_core.L_SFT;
const L_ALT = zkc_core.L_ALT;
const R_ALT = zkc_core.R_ALT;
const R_CTL = zkc_core.R_CTL;
const DEAD = zkc_core.DEAD;
pub const keycodes = @import("keycodes.zig");

pub const QMK_FRENCH_MAC_ISO_KEYCODES_VERSION = "0.0.1";
pub const QMK_FRENCH_MAC_ISO_KEYCODES_VERSION_BCD = @as(c_int, 0x00000001);
pub const QMK_FRENCH_MAC_ISO_KEYCODES_VERSION_MAJOR = @as(c_int, 0);
pub const QMK_FRENCH_MAC_ISO_KEYCODES_VERSION_MINOR = @as(c_int, 0);
pub const QMK_FRENCH_MAC_ISO_KEYCODES_VERSION_PATCH = @as(c_int, 1);

//
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
// │ @ │ & │ é │ " │ ' │ ( │ § │ è │ ! │ ç │ à │ ) │ - │     │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
// │     │ A │ Z │ E │ R │ T │ Y │ U │ I │ O │ P │ ^ │ $ │   │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐  │
// │      │ Q │ S │ D │ F │ G │ H │ J │ K │ L │ M │ ù │ ` │  │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴──┤
// │    │ < │ W │ X │ C │ V │ B │ N │ , │ ; │ : │ = │        │
// ├────┴┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
// │     │    │     │                       │     │    │     │
// └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
//
/// @
pub const AT = keycodes.kcf.GRV;
/// &
pub const AMPR = keycodes.kcf.N1;
/// é
pub const LEAC = keycodes.kcf.N2;
/// "
pub const DQUO = keycodes.kcf.N3;
/// '
pub const QUOT = keycodes.kcf.N4;
/// (
pub const LPRN = keycodes.kcf.N5;
/// §
pub const SECT = keycodes.kcf.N6;
/// è
pub const LEGR = keycodes.kcf.N7;
/// !
pub const EXLM = keycodes.kcf.N8;
/// ç
pub const LCCE = keycodes.kcf.N9;
/// à
pub const LAGR = keycodes.kcf.N0;
/// )
pub const RPRN = keycodes.kcf.MINS;
/// -
pub const MINS = keycodes.kcf.EQL;
/// A
pub const A = keycodes.kcf.Q;
/// Z
pub const Z = keycodes.kcf.W;
/// E
pub const E = keycodes.kcf.E;
/// R
pub const R = keycodes.kcf.R;
/// T
pub const T = keycodes.kcf.T;
/// Y
pub const Y = keycodes.kcf.Y;
/// U
pub const U = keycodes.kcf.U;
/// I
pub const I = keycodes.kcf.I;
/// O
pub const O = keycodes.kcf.O;
/// P
pub const P = keycodes.kcf.P;
/// ^
pub const CIRC = keycodes.kcf.LBRC;
/// $
pub const DLR = keycodes.kcf.RBRC;
/// Q
pub const Q = keycodes.kcf.A;
/// S
pub const S = keycodes.kcf.S;
/// D
pub const D = keycodes.kcf.D;
/// F
pub const F = keycodes.kcf.F;
/// G
pub const G = keycodes.kcf.G;
/// H
pub const H = keycodes.kcf.H;
/// J
pub const J = keycodes.kcf.J;
/// K
pub const K = keycodes.kcf.K;
/// L
pub const L = keycodes.kcf.L;
/// M
pub const M = keycodes.kcf.SCLN;
/// ù
pub const LUGR = keycodes.kcf.QUOT;
/// `
pub const GRV = keycodes.kcf.NUHS;
/// <
pub const LABK = keycodes.kcf.NUBS;
/// W
pub const W = keycodes.kcf.Z;
/// X
pub const X = keycodes.kcf.X;
/// C
pub const C = keycodes.kcf.C;
/// V
pub const V = keycodes.kcf.V;
/// B
pub const B = keycodes.kcf.B;
/// N
pub const N = keycodes.kcf.N;
/// ,
pub const COMM = keycodes.kcf.M;
/// ;
pub const SCLN = keycodes.kcf.COMM;
/// :
pub const COLN = keycodes.kcf.DOT;
/// =
pub const EQL = keycodes.kcf.SLSH;
// Shifted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
// │ # │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ ° │ _ │     │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
// │     │   │   │   │   │   │   │   │   │   │   │ ¨ │ * │   │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐  │
// │      │   │   │   │   │   │   │   │   │   │   │ % │ £ │  │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴──┤
// │    │ > │   │   │   │   │   │   │ ? │ . │ / │ + │        │
// ├────┴┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
// │     │    │     │                       │     │    │     │
// └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
//
/// #
pub const HASH = L_SFT(AT);
/// 1
pub const N1 = L_SFT(AMPR);
/// 2
pub const N2 = L_SFT(LEAC);
/// 3
pub const N3 = L_SFT(DQUO);
/// 4
pub const N4 = L_SFT(QUOT);
/// 5
pub const N5 = L_SFT(LPRN);
/// 6
pub const N6 = L_SFT(SECT);
/// 7
pub const N7 = L_SFT(LEGR);
/// 8
pub const N8 = L_SFT(EXLM);
/// 9
pub const N9 = L_SFT(LCCE);
/// 0
pub const N0 = L_SFT(LAGR);
/// °
pub const DEG = L_SFT(RPRN);
/// _
pub const UNDS = L_SFT(MINS);
/// ¨ (dead)
pub const DIAE = DEAD(L_SFT(CIRC));
/// *
pub const ASTR = L_SFT(DLR);
/// %
pub const PERC = L_SFT(LUGR);
/// £
pub const PND = L_SFT(GRV);
/// >
pub const RABK = L_SFT(LABK);
/// ?
pub const QUES = L_SFT(COMM);
/// .
pub const DOT = L_SFT(SCLN);
/// /
pub const SLSH = L_SFT(COLN);
/// +
pub const PLUS = L_SFT(EQL);
// Alted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
// │ • │  │ ë │ “ │ ‘ │ { │ ¶ │ « │ ¡ │ Ç │ Ø │ } │ — │     │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
// │     │ Æ │ Â │ Ê │ ® │ † │ Ú │ º │ î │ Œ │ π │ Ô │ € │   │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐  │
// │      │ ‡ │ Ò │ ∂ │ ƒ │ ﬁ │ Ì │ Ï │ È │ ¬ │ µ │ Ù │   │  │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴──┤
// │    │ ≤ │ ‹ │ ≈ │ © │ ◊ │ ß │ ~ │ ∞ │ … │ ÷ │ ≠ │        │
// ├────┴┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
// │     │    │     │                       │     │    │     │
// └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
//
/// •
pub const BULT = L_ALT(AT);
///  (Apple logo)
pub const APPL = L_ALT(AMPR);
/// ë
pub const LEDI = L_ALT(LEAC);
/// “
pub const LDQU = L_ALT(DQUO);
/// ‘
pub const LSQU = L_ALT(QUOT);
/// {
pub const LCBR = L_ALT(LPRN);
/// ¶
pub const PILC = L_ALT(SECT);
/// «
pub const LDAQ = L_ALT(LEGR);
/// ¡
pub const IEXL = L_ALT(EXLM);
/// Ç
pub const CCCE = L_ALT(LCCE);
/// Ø
pub const OSTR = L_ALT(LAGR);
/// }
pub const RCBR = L_ALT(RPRN);
/// —
pub const MDSH = L_ALT(MINS);
/// Æ
pub const AE = L_ALT(A);
/// Â
pub const CACI = L_ALT(Z);
/// Ê
pub const ECIR = L_ALT(E);
/// ®
pub const REGD = L_ALT(R);
/// †
pub const DAGG = L_ALT(T);
/// Ú
pub const CUAC = L_ALT(Y);
/// º
pub const MORD = L_ALT(U);
/// î
pub const LICI = L_ALT(I);
/// Œ
pub const OE = L_ALT(O);
/// π
pub const PI = L_ALT(P);
/// Ô
pub const OCIR = L_ALT(CIRC);
/// €
pub const EURO = L_ALT(DLR);
/// ‡
pub const DDAG = L_ALT(Q);
/// Ò
pub const COGR = L_ALT(S);
/// ∂
pub const PDIF = L_ALT(D);
/// ƒ
pub const FHK = L_ALT(F);
/// ﬁ
pub const FI = L_ALT(G);
/// Ì
pub const CIGR = L_ALT(H);
/// Ï
pub const CIDI = L_ALT(J);
/// È
pub const CEGR = L_ALT(K);
/// ¬
pub const NOT = L_ALT(L);
/// µ
pub const MICR = L_ALT(M);
/// Ù
pub const CUGR = L_ALT(LUGR);
/// ≤
pub const LTEQ = L_ALT(LABK);
/// ‹
pub const LSAQ = L_ALT(W);
/// ≈
pub const AEQL = L_ALT(X);
/// ©
pub const COPY = L_ALT(C);
/// ◊
pub const LOZN = L_ALT(V);
/// ß
pub const SS = L_ALT(B);
/// ~ (dead)
pub const TILD = DEAD(L_ALT(N));
/// ∞
pub const INFN = L_ALT(COMM);
/// …
pub const ELLP = L_ALT(SCLN);
/// ÷
pub const DIV = L_ALT(COLN);
/// ≠
pub const NEQL = L_ALT(EQL);
// Shift+Alted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
// │ Ÿ │ ´ │ „ │   │   │ [ │ å │ » │ Û │ Á │   │ ] │ – │     │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
// │     │   │ Å │   │ ‚ │ ™ │   │ ª │ ï │   │ ∏ │   │ ¥ │   │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐  │
// │      │ Ω │ ∑ │ ∆ │ · │ ﬂ │ Î │ Í │ Ë │ | │ Ó │ ‰ │   │  │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴──┤
// │    │ ≥ │ › │ ⁄ │ ¢ │ √ │ ∫ │ ı │ ¿ │   │ \ │ ± │        │
// ├────┴┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
// │     │    │     │                       │     │    │     │
// └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
//
/// Ÿ
pub const CYDI = L_SFT(L_ALT(AT));
/// ´ (dead)
pub const ACUT = DEAD(L_SFT(L_ALT(AMPR)));
/// „
pub const DLQU = L_SFT(L_ALT(LEAC));
/// [
pub const LBRC = L_SFT(L_ALT(LPRN));
/// å
pub const LARI = L_SFT(L_ALT(SECT));
/// »
pub const RDAQ = L_SFT(L_ALT(LEGR));
/// Û
pub const CUCI = L_SFT(L_ALT(EXLM));
/// Á
pub const CAAC = L_SFT(L_ALT(LCCE));
/// ]
pub const RBRC = L_SFT(L_ALT(RPRN));
/// –
pub const NDSH = L_SFT(L_ALT(MINS));
/// Å
pub const CARI = L_SFT(L_ALT(Z));
/// ‚
pub const SLQU = L_SFT(L_ALT(R));
/// ™
pub const TM = L_SFT(L_ALT(T));
/// ª
pub const FORD = L_SFT(L_ALT(U));
/// ï
pub const LIDI = L_SFT(L_ALT(I));
/// ∏
pub const NARP = L_SFT(L_ALT(P));
/// ¥
pub const YEN = L_SFT(L_ALT(DLR));
/// Ω
pub const OMEG = L_SFT(L_ALT(Q));
/// ∑
pub const NARS = L_SFT(L_ALT(S));
/// ∆
pub const INCR = L_SFT(L_ALT(D));
/// ·
pub const MDDT = L_SFT(L_ALT(F));
/// ﬂ
pub const FL = L_SFT(L_ALT(G));
/// Î
pub const CICI = L_SFT(L_ALT(H));
/// Í
pub const CIAC = L_SFT(L_ALT(J));
/// Ë
pub const CEDI = L_SFT(L_ALT(K));
/// |
pub const PIPE = L_SFT(L_ALT(L));
/// Ó
pub const COAC = L_SFT(L_ALT(M));
/// ‰
pub const PERM = L_SFT(L_ALT(LUGR));
/// ≥
pub const GTEQ = L_SFT(L_ALT(LABK));
/// ›
pub const RSAQ = L_SFT(L_ALT(W));
/// ⁄
pub const FRSL = L_SFT(L_ALT(X));
/// ¢
pub const CENT = L_SFT(L_ALT(C));
/// √
pub const SQRT = L_SFT(L_ALT(V));
/// ∫
pub const INTG = L_SFT(L_ALT(B));
/// ı
pub const DLSI = L_SFT(L_ALT(N));
/// ¿
pub const IQUE = L_SFT(L_ALT(COMM));
/// (backslash)
pub const BSLS = L_SFT(L_ALT(COLN));
/// ±
pub const PLMN = L_SFT(L_ALT(EQL));

// Label lookup table
pub const _labels = [_]zkc_core.LabelEntry{
    .{ .value = AT, .label = "AT", .short_label = "AT" },
    .{ .value = AMPR, .label = "AMPR", .short_label = "AMPR" },
    .{ .value = LEAC, .label = "LEAC", .short_label = "LEAC" },
    .{ .value = DQUO, .label = "DQUO", .short_label = "DQUO" },
    .{ .value = QUOT, .label = "QUOT", .short_label = "QUOT" },
    .{ .value = LPRN, .label = "LPRN", .short_label = "LPRN" },
    .{ .value = SECT, .label = "SECT", .short_label = "SECT" },
    .{ .value = LEGR, .label = "LEGR", .short_label = "LEGR" },
    .{ .value = EXLM, .label = "EXLM", .short_label = "EXLM" },
    .{ .value = LCCE, .label = "LCCE", .short_label = "LCCE" },
    .{ .value = LAGR, .label = "LAGR", .short_label = "LAGR" },
    .{ .value = RPRN, .label = "RPRN", .short_label = "RPRN" },
    .{ .value = MINS, .label = "MINS", .short_label = "MINS" },
    .{ .value = A, .label = "A", .short_label = "A" },
    .{ .value = Z, .label = "Z", .short_label = "Z" },
    .{ .value = E, .label = "E", .short_label = "E" },
    .{ .value = R, .label = "R", .short_label = "R" },
    .{ .value = T, .label = "T", .short_label = "T" },
    .{ .value = Y, .label = "Y", .short_label = "Y" },
    .{ .value = U, .label = "U", .short_label = "U" },
    .{ .value = I, .label = "I", .short_label = "I" },
    .{ .value = O, .label = "O", .short_label = "O" },
    .{ .value = P, .label = "P", .short_label = "P" },
    .{ .value = CIRC, .label = "CIRC", .short_label = "CIRC" },
    .{ .value = DLR, .label = "DLR", .short_label = "DLR" },
    .{ .value = Q, .label = "Q", .short_label = "Q" },
    .{ .value = S, .label = "S", .short_label = "S" },
    .{ .value = D, .label = "D", .short_label = "D" },
    .{ .value = F, .label = "F", .short_label = "F" },
    .{ .value = G, .label = "G", .short_label = "G" },
    .{ .value = H, .label = "H", .short_label = "H" },
    .{ .value = J, .label = "J", .short_label = "J" },
    .{ .value = K, .label = "K", .short_label = "K" },
    .{ .value = L, .label = "L", .short_label = "L" },
    .{ .value = M, .label = "M", .short_label = "M" },
    .{ .value = LUGR, .label = "LUGR", .short_label = "LUGR" },
    .{ .value = GRV, .label = "GRV", .short_label = "GRV" },
    .{ .value = LABK, .label = "LABK", .short_label = "LABK" },
    .{ .value = W, .label = "W", .short_label = "W" },
    .{ .value = X, .label = "X", .short_label = "X" },
    .{ .value = C, .label = "C", .short_label = "C" },
    .{ .value = V, .label = "V", .short_label = "V" },
    .{ .value = B, .label = "B", .short_label = "B" },
    .{ .value = N, .label = "N", .short_label = "N" },
    .{ .value = COMM, .label = "COMM", .short_label = "COMM" },
    .{ .value = SCLN, .label = "SCLN", .short_label = "SCLN" },
    .{ .value = COLN, .label = "COLN", .short_label = "COLN" },
    .{ .value = EQL, .label = "EQL", .short_label = "EQL" },
    .{ .value = HASH, .label = "HASH", .short_label = "HASH" },
    .{ .value = N1, .label = "1", .short_label = "1" },
    .{ .value = N2, .label = "2", .short_label = "2" },
    .{ .value = N3, .label = "3", .short_label = "3" },
    .{ .value = N4, .label = "4", .short_label = "4" },
    .{ .value = N5, .label = "5", .short_label = "5" },
    .{ .value = N6, .label = "6", .short_label = "6" },
    .{ .value = N7, .label = "7", .short_label = "7" },
    .{ .value = N8, .label = "8", .short_label = "8" },
    .{ .value = N9, .label = "9", .short_label = "9" },
    .{ .value = N0, .label = "0", .short_label = "0" },
    .{ .value = DEG, .label = "DEG", .short_label = "DEG" },
    .{ .value = UNDS, .label = "UNDS", .short_label = "UNDS" },
    .{ .value = DIAE, .label = "DIAE", .short_label = "DIAE" },
    .{ .value = ASTR, .label = "ASTR", .short_label = "ASTR" },
    .{ .value = PERC, .label = "PERC", .short_label = "PERC" },
    .{ .value = PND, .label = "PND", .short_label = "PND" },
    .{ .value = RABK, .label = "RABK", .short_label = "RABK" },
    .{ .value = QUES, .label = "QUES", .short_label = "QUES" },
    .{ .value = DOT, .label = "DOT", .short_label = "DOT" },
    .{ .value = SLSH, .label = "SLSH", .short_label = "SLSH" },
    .{ .value = PLUS, .label = "PLUS", .short_label = "PLUS" },
    .{ .value = BULT, .label = "BULT", .short_label = "BULT" },
    .{ .value = APPL, .label = "APPL", .short_label = "APPL" },
    .{ .value = LEDI, .label = "LEDI", .short_label = "LEDI" },
    .{ .value = LDQU, .label = "LDQU", .short_label = "LDQU" },
    .{ .value = LSQU, .label = "LSQU", .short_label = "LSQU" },
    .{ .value = LCBR, .label = "LCBR", .short_label = "LCBR" },
    .{ .value = PILC, .label = "PILC", .short_label = "PILC" },
    .{ .value = LDAQ, .label = "LDAQ", .short_label = "LDAQ" },
    .{ .value = IEXL, .label = "IEXL", .short_label = "IEXL" },
    .{ .value = CCCE, .label = "CCCE", .short_label = "CCCE" },
    .{ .value = OSTR, .label = "OSTR", .short_label = "OSTR" },
    .{ .value = RCBR, .label = "RCBR", .short_label = "RCBR" },
    .{ .value = MDSH, .label = "MDSH", .short_label = "MDSH" },
    .{ .value = AE, .label = "AE", .short_label = "AE" },
    .{ .value = CACI, .label = "CACI", .short_label = "CACI" },
    .{ .value = ECIR, .label = "ECIR", .short_label = "ECIR" },
    .{ .value = REGD, .label = "REGD", .short_label = "REGD" },
    .{ .value = DAGG, .label = "DAGG", .short_label = "DAGG" },
    .{ .value = CUAC, .label = "CUAC", .short_label = "CUAC" },
    .{ .value = MORD, .label = "MORD", .short_label = "MORD" },
    .{ .value = LICI, .label = "LICI", .short_label = "LICI" },
    .{ .value = OE, .label = "OE", .short_label = "OE" },
    .{ .value = PI, .label = "PI", .short_label = "PI" },
    .{ .value = OCIR, .label = "OCIR", .short_label = "OCIR" },
    .{ .value = EURO, .label = "EURO", .short_label = "EURO" },
    .{ .value = DDAG, .label = "DDAG", .short_label = "DDAG" },
    .{ .value = COGR, .label = "COGR", .short_label = "COGR" },
    .{ .value = PDIF, .label = "PDIF", .short_label = "PDIF" },
    .{ .value = FHK, .label = "FHK", .short_label = "FHK" },
    .{ .value = FI, .label = "FI", .short_label = "FI" },
    .{ .value = CIGR, .label = "CIGR", .short_label = "CIGR" },
    .{ .value = CIDI, .label = "CIDI", .short_label = "CIDI" },
    .{ .value = CEGR, .label = "CEGR", .short_label = "CEGR" },
    .{ .value = NOT, .label = "NOT", .short_label = "NOT" },
    .{ .value = MICR, .label = "MICR", .short_label = "MICR" },
    .{ .value = CUGR, .label = "CUGR", .short_label = "CUGR" },
    .{ .value = LTEQ, .label = "LTEQ", .short_label = "LTEQ" },
    .{ .value = LSAQ, .label = "LSAQ", .short_label = "LSAQ" },
    .{ .value = AEQL, .label = "AEQL", .short_label = "AEQL" },
    .{ .value = COPY, .label = "COPY", .short_label = "COPY" },
    .{ .value = LOZN, .label = "LOZN", .short_label = "LOZN" },
    .{ .value = SS, .label = "SS", .short_label = "SS" },
    .{ .value = TILD, .label = "TILD", .short_label = "TILD" },
    .{ .value = INFN, .label = "INFN", .short_label = "INFN" },
    .{ .value = ELLP, .label = "ELLP", .short_label = "ELLP" },
    .{ .value = DIV, .label = "DIV", .short_label = "DIV" },
    .{ .value = NEQL, .label = "NEQL", .short_label = "NEQL" },
    .{ .value = CYDI, .label = "CYDI", .short_label = "CYDI" },
    .{ .value = ACUT, .label = "ACUT", .short_label = "ACUT" },
    .{ .value = DLQU, .label = "DLQU", .short_label = "DLQU" },
    .{ .value = LBRC, .label = "LBRC", .short_label = "LBRC" },
    .{ .value = LARI, .label = "LARI", .short_label = "LARI" },
    .{ .value = RDAQ, .label = "RDAQ", .short_label = "RDAQ" },
    .{ .value = CUCI, .label = "CUCI", .short_label = "CUCI" },
    .{ .value = CAAC, .label = "CAAC", .short_label = "CAAC" },
    .{ .value = RBRC, .label = "RBRC", .short_label = "RBRC" },
    .{ .value = NDSH, .label = "NDSH", .short_label = "NDSH" },
    .{ .value = CARI, .label = "CARI", .short_label = "CARI" },
    .{ .value = SLQU, .label = "SLQU", .short_label = "SLQU" },
    .{ .value = TM, .label = "TM", .short_label = "TM" },
    .{ .value = FORD, .label = "FORD", .short_label = "FORD" },
    .{ .value = LIDI, .label = "LIDI", .short_label = "LIDI" },
    .{ .value = NARP, .label = "NARP", .short_label = "NARP" },
    .{ .value = YEN, .label = "YEN", .short_label = "YEN" },
    .{ .value = OMEG, .label = "OMEG", .short_label = "OMEG" },
    .{ .value = NARS, .label = "NARS", .short_label = "NARS" },
    .{ .value = INCR, .label = "INCR", .short_label = "INCR" },
    .{ .value = MDDT, .label = "MDDT", .short_label = "MDDT" },
    .{ .value = FL, .label = "FL", .short_label = "FL" },
    .{ .value = CICI, .label = "CICI", .short_label = "CICI" },
    .{ .value = CIAC, .label = "CIAC", .short_label = "CIAC" },
    .{ .value = CEDI, .label = "CEDI", .short_label = "CEDI" },
    .{ .value = PIPE, .label = "PIPE", .short_label = "PIPE" },
    .{ .value = COAC, .label = "COAC", .short_label = "COAC" },
    .{ .value = PERM, .label = "PERM", .short_label = "PERM" },
    .{ .value = GTEQ, .label = "GTEQ", .short_label = "GTEQ" },
    .{ .value = RSAQ, .label = "RSAQ", .short_label = "RSAQ" },
    .{ .value = FRSL, .label = "FRSL", .short_label = "FRSL" },
    .{ .value = CENT, .label = "CENT", .short_label = "CENT" },
    .{ .value = SQRT, .label = "SQRT", .short_label = "SQRT" },
    .{ .value = INTG, .label = "INTG", .short_label = "INTG" },
    .{ .value = DLSI, .label = "DLSI", .short_label = "DLSI" },
    .{ .value = IQUE, .label = "IQUE", .short_label = "IQUE" },
    .{ .value = BSLS, .label = "BSLS", .short_label = "BSLS" },
    .{ .value = PLMN, .label = "PLMN", .short_label = "PLMN" },
};

pub fn getLabel(keycode: core.KeyCodeFire, shortest: bool) ?[]const u8 {
    return zkc_core.getLabel(&_labels, keycode, shortest);
}
