// Copyright 2026 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by zkeycodes from QMK hjson keycode files
const zkc_core = @import("../src/core.zig");
const core = @import("zigmkay").core;
const L_SFT = zkc_core.L_SFT;
const L_ALT = zkc_core.L_ALT;
const R_ALT = zkc_core.R_ALT;
const R_CTL = zkc_core.R_CTL;
const DEAD = zkc_core.DEAD;
pub const keycodes = @import("keycodes.zig");

pub const QMK_FRENCH_AFNOR_KEYCODES_VERSION = "0.0.1";
pub const QMK_FRENCH_AFNOR_KEYCODES_VERSION_BCD = @as(c_int, 0x00000001);
pub const QMK_FRENCH_AFNOR_KEYCODES_VERSION_MAJOR = @as(c_int, 0);
pub const QMK_FRENCH_AFNOR_KEYCODES_VERSION_MINOR = @as(c_int, 0);
pub const QMK_FRENCH_AFNOR_KEYCODES_VERSION_PATCH = @as(c_int, 1);

// French AZERTY - AFNOR NF Z71-300
//
// A standard for the French keyboard
//
// The project was launched at the end of 2015 on the proposal of the General
// Delegation for the French language and the languages of France (Ministry
// of Culture), starting from the observation that the current "azerty"
// keyboards constrain the writing of French, languages regional and European
// languages with Latin alphabet.
//
// For the first time, a standard (NF Z71-300) defines the placement of
// characters on the French keyboard. It offers two layouts, one of which
// closely follows the QWERTY keyboard used by most people who write in French.
//
// However, it is in many ways superior to the old keyboard:
//
// - it contains all the characters required to enter text in French (for example É, œ and ")
// - it is designed to be more ergonomic and allow faster typing
// - it includes almost 60 additional characters for entering foreign languages, technical content, etc
// - however, the characters remain easy to locate thanks to intuitive groupings
//
// Source: https://norme-azerty.fr
//
//
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ @ │ à │ é │ è │ ê │ ( │ ) │ ‘ │ ’ │ « │ » │ ' │ ^ │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ A │ Z │ E │ R │ T │ Y │ U │ I │ O │ P │ - │ + │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │ Q │ S │ D │ F │ G │ H │ J │ K │ L │ M │ / │ * │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ < │ W │ X │ C │ V │ B │ N │ . │ , │ : │ ; │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// @
pub const AT = keycodes.kcf.GRV;
/// à
pub const AGRV = keycodes.kcf.N1;
/// é
pub const EACU = keycodes.kcf.N2;
/// è
pub const EGRV = keycodes.kcf.N3;
/// ê
pub const ECIR = keycodes.kcf.N4;
/// (
pub const LPRN = keycodes.kcf.N5;
/// )
pub const RPRN = keycodes.kcf.N6;
/// ‘
pub const LSQU = keycodes.kcf.N7;
/// ’
pub const RSQU = keycodes.kcf.N8;
/// «
pub const LDAQ = keycodes.kcf.N9;
/// »
pub const RDAQ = keycodes.kcf.N0;
/// '
pub const QUOT = keycodes.kcf.MINS;
/// ^ (dead)
pub const DCIR = DEAD(keycodes.kcf.EQL);
/// A
pub const A = keycodes.kcf.Q;
/// Z
pub const Z = keycodes.kcf.W;
/// E
pub const E = keycodes.kcf.E;
/// R
pub const R = keycodes.kcf.R;
/// T
pub const T = keycodes.kcf.T;
/// Y
pub const Y = keycodes.kcf.Y;
/// U
pub const U = keycodes.kcf.U;
/// I
pub const I = keycodes.kcf.I;
/// O
pub const O = keycodes.kcf.O;
/// P
pub const P = keycodes.kcf.P;
/// -
pub const MINS = keycodes.kcf.LBRC;
/// +
pub const PLUS = keycodes.kcf.RBRC;
/// Q
pub const Q = keycodes.kcf.A;
/// S
pub const S = keycodes.kcf.S;
/// D
pub const D = keycodes.kcf.D;
/// F
pub const F = keycodes.kcf.F;
/// G
pub const G = keycodes.kcf.G;
/// H
pub const H = keycodes.kcf.H;
/// J
pub const J = keycodes.kcf.J;
/// K
pub const K = keycodes.kcf.K;
/// L
pub const L = keycodes.kcf.L;
/// M
pub const M = keycodes.kcf.SCLN;
/// /
pub const SLSH = keycodes.kcf.QUOT;
/// *
pub const ASTR = keycodes.kcf.NUHS;
/// <
pub const LABK = keycodes.kcf.NUBS;
/// W
pub const W = keycodes.kcf.Z;
/// X
pub const X = keycodes.kcf.X;
/// C
pub const C = keycodes.kcf.C;
/// V
pub const V = keycodes.kcf.V;
/// B
pub const B = keycodes.kcf.B;
/// N
pub const N = keycodes.kcf.N;
/// .
pub const DOT = keycodes.kcf.M;
/// ,
pub const COMM = keycodes.kcf.COMM;
/// :
pub const COLN = keycodes.kcf.DOT;
/// ;
pub const SCLN = keycodes.kcf.SLSH;
// Shifted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ # │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ " │ ¨ │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │   │   │   │   │   │   │   │   │ – │ ± │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │   │   │   │   │   │   │   │   │   │   │ \ │ ½ │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ > │   │   │   │   │   │   │ ? │ ! │ … │ = │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// #
pub const HASH = L_SFT(AT);
/// 1
pub const N1 = L_SFT(AGRV);
/// 2
pub const N2 = L_SFT(EACU);
/// 3
pub const N3 = L_SFT(EGRV);
/// 4
pub const N4 = L_SFT(ECIR);
/// 5
pub const N5 = L_SFT(LPRN);
/// 6
pub const N6 = L_SFT(RPRN);
/// 7
pub const N7 = L_SFT(LSQU);
/// 8
pub const N8 = L_SFT(RSQU);
/// 9
pub const N9 = L_SFT(LDAQ);
/// 0
pub const N0 = L_SFT(RDAQ);
/// "
pub const DQUO = L_SFT(QUOT);
/// ¨ (dead)
pub const DIAE = DEAD(L_SFT(DCIR));
/// –
pub const NDSH = L_SFT(MINS);
/// ±
pub const PLMN = L_SFT(PLUS);
/// (backslash)
pub const BSLS = L_SFT(SLSH);
/// ½
pub const HALF = L_SFT(ASTR);
/// >
pub const RABK = L_SFT(LABK);
/// ?
pub const QUES = L_SFT(DOT);
/// !
pub const EXLM = L_SFT(COMM);
/// …
pub const ELLP = L_SFT(COLN);
/// =
pub const EQL = L_SFT(SCLN);
// AltGr symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ˘ │ § │ ´ │ ` │ & │ [ │ ] │ ¯ │ _ │ “ │ ” │ ° │ ˇ │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ æ │ £ │ € │ ® │ { │ } │ ù │ ˙ │ œ │ % │ − │ † │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │ θ │ ß │ $ │ ¤ │ µ │ Eu│   │ ∕ │ | │ ∞ │ ÷ │ × │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ ≤ │ ʒ │ © │ ç │ ¸ │ − │ ~ │ ¿ │ ¡ │ · │ ≃ │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ˘ (dead)
pub const BREV = DEAD(R_ALT(AT));
/// §
pub const SECT = R_ALT(AGRV);
/// ´ (dead)
pub const ACUT = DEAD(R_ALT(EACU));
/// ` (dead)
pub const GRV = DEAD(R_ALT(EGRV));
/// &
pub const AMPR = R_ALT(ECIR);
/// [
pub const LBRC = R_ALT(LPRN);
/// ]
pub const RBRC = R_ALT(RPRN);
/// ¯ (dead)
pub const MACR = DEAD(R_ALT(LSQU));
/// _
pub const UNDS = R_ALT(RSQU);
/// “
pub const LDQU = R_ALT(LDAQ);
/// ”
pub const RDQU = R_ALT(RDAQ);
/// °
pub const DEG = R_ALT(QUOT);
/// ˇ (dead)
pub const CARN = DEAD(R_ALT(DCIR));
/// æ
pub const AE = R_ALT(A);
/// £
pub const PND = R_ALT(Z);
/// €
pub const EURO = R_ALT(E);
/// ®
pub const REGD = R_ALT(R);
/// {
pub const LCBR = R_ALT(T);
/// }
pub const RCBR = R_ALT(Y);
/// ù
pub const UGRV = R_ALT(U);
/// ˙ (dead)
pub const DOTA = DEAD(R_ALT(I));
/// œ
pub const OE = R_ALT(O);
/// %
pub const PERC = R_ALT(P);
/// −
pub const MMNS = R_ALT(MINS);
/// †
pub const DAGG = R_ALT(PLUS);
/// θ
pub const THET = R_ALT(Q);
/// ß
pub const SS = R_ALT(S);
/// $
pub const DLR = R_ALT(D);
/// ¤ (dead monetary key)
pub const CURR = R_ALT(F);
/// µ (dead Greek key)
pub const DGRK = R_ALT(G);
/// Eu (dead European symbol key)
pub const EU = R_ALT(H);
/// ∕ (dead)
pub const DSLS = DEAD(R_ALT(K));
/// |
pub const PIPE = R_ALT(L);
/// ∞
pub const INFN = R_ALT(M);
/// ÷
pub const DIV = R_ALT(SLSH);
/// ×
pub const MUL = R_ALT(ASTR);
/// ≤
pub const LEQL = R_ALT(LABK);
/// ʒ
pub const EZH = R_ALT(W);
/// ©
pub const COPY = R_ALT(X);
/// ç
pub const CCED = R_ALT(C);
/// ¸ (dead)
pub const CEDL = DEAD(R_ALT(V));
/// − (dead)
pub const DMNS = DEAD(R_ALT(B));
/// ~ (dead)
pub const DTIL = DEAD(R_ALT(N));
/// ¿
pub const IQUE = R_ALT(DOT);
/// ¡
pub const IEXL = R_ALT(COMM);
/// ·
pub const MDDT = R_ALT(COLN);
/// ≃
pub const AEQL = R_ALT(SCLN);
// Shift+AltGr symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ̑  │   │   │   │   │ ˝ │ ̏  │   │ — │ ‹ │ › │ ˚ │   │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │   │   │ ™ │   │   │ ̣  │   │ ‰ │ ‑ │ ‡ │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │   │   │   │   │   │ ˍ │   │   │   │   │ √ │ ¼ │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ ≥ │   │   │   │ ˛ │   │   │   │ ̦  │   │ ≠ │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ̑ (dead)
pub const IBRV = DEAD(L_SFT(R_ALT(AT)));
/// ˝ (dead)
pub const DACU = DEAD(L_SFT(R_ALT(LPRN)));
/// ̏ (dead)
pub const DGRV = DEAD(L_SFT(R_ALT(RPRN)));
/// —
pub const MDSH = L_SFT(R_ALT(RSQU));
/// ‹
pub const LSAQ = L_SFT(R_ALT(LDAQ));
/// ›
pub const RSAQ = L_SFT(R_ALT(RDAQ));
/// ˚ (dead)
pub const RNGA = DEAD(L_SFT(R_ALT(QUOT)));
/// ™
pub const TM = L_SFT(R_ALT(T));
/// ̣ (dead)
pub const DOTB = DEAD(L_SFT(R_ALT(I)));
/// ‰
pub const PERM = L_SFT(R_ALT(P));
/// ‑ (non-breaking hyphen)
pub const NBHY = L_SFT(R_ALT(MINS));
/// ‡
pub const DDAG = L_SFT(R_ALT(PLUS));
/// ˍ (dead)
pub const MACB = DEAD(L_SFT(R_ALT(H)));
/// √
pub const SQRT = L_SFT(R_ALT(SLSH));
/// ¼
pub const QRTR = L_SFT(R_ALT(ASTR));
/// ≥
pub const GEQL = L_SFT(R_ALT(LABK));
/// ˛ (dead)
pub const OGON = DEAD(L_SFT(R_ALT(V)));
/// ̦ (dead)
pub const DCMM = DEAD(L_SFT(R_ALT(COMM)));
/// ≠
pub const NEQL = L_SFT(R_ALT(SCLN));

// Label lookup table
pub const _labels = [_]zkc_core.LabelEntry{
    .{ .value = AT, .label = "AT", .short_label = "AT" },
    .{ .value = AGRV, .label = "AGRV", .short_label = "AGRV" },
    .{ .value = EACU, .label = "EACU", .short_label = "EACU" },
    .{ .value = EGRV, .label = "EGRV", .short_label = "EGRV" },
    .{ .value = ECIR, .label = "ECIR", .short_label = "ECIR" },
    .{ .value = LPRN, .label = "LPRN", .short_label = "LPRN" },
    .{ .value = RPRN, .label = "RPRN", .short_label = "RPRN" },
    .{ .value = LSQU, .label = "LSQU", .short_label = "LSQU" },
    .{ .value = RSQU, .label = "RSQU", .short_label = "RSQU" },
    .{ .value = LDAQ, .label = "LDAQ", .short_label = "LDAQ" },
    .{ .value = RDAQ, .label = "RDAQ", .short_label = "RDAQ" },
    .{ .value = QUOT, .label = "QUOT", .short_label = "QUOT" },
    .{ .value = DCIR, .label = "DCIR", .short_label = "DCIR" },
    .{ .value = A, .label = "A", .short_label = "A" },
    .{ .value = Z, .label = "Z", .short_label = "Z" },
    .{ .value = E, .label = "E", .short_label = "E" },
    .{ .value = R, .label = "R", .short_label = "R" },
    .{ .value = T, .label = "T", .short_label = "T" },
    .{ .value = Y, .label = "Y", .short_label = "Y" },
    .{ .value = U, .label = "U", .short_label = "U" },
    .{ .value = I, .label = "I", .short_label = "I" },
    .{ .value = O, .label = "O", .short_label = "O" },
    .{ .value = P, .label = "P", .short_label = "P" },
    .{ .value = MINS, .label = "MINS", .short_label = "MINS" },
    .{ .value = PLUS, .label = "PLUS", .short_label = "PLUS" },
    .{ .value = Q, .label = "Q", .short_label = "Q" },
    .{ .value = S, .label = "S", .short_label = "S" },
    .{ .value = D, .label = "D", .short_label = "D" },
    .{ .value = F, .label = "F", .short_label = "F" },
    .{ .value = G, .label = "G", .short_label = "G" },
    .{ .value = H, .label = "H", .short_label = "H" },
    .{ .value = J, .label = "J", .short_label = "J" },
    .{ .value = K, .label = "K", .short_label = "K" },
    .{ .value = L, .label = "L", .short_label = "L" },
    .{ .value = M, .label = "M", .short_label = "M" },
    .{ .value = SLSH, .label = "SLSH", .short_label = "SLSH" },
    .{ .value = ASTR, .label = "ASTR", .short_label = "ASTR" },
    .{ .value = LABK, .label = "LABK", .short_label = "LABK" },
    .{ .value = W, .label = "W", .short_label = "W" },
    .{ .value = X, .label = "X", .short_label = "X" },
    .{ .value = C, .label = "C", .short_label = "C" },
    .{ .value = V, .label = "V", .short_label = "V" },
    .{ .value = B, .label = "B", .short_label = "B" },
    .{ .value = N, .label = "N", .short_label = "N" },
    .{ .value = DOT, .label = "DOT", .short_label = "DOT" },
    .{ .value = COMM, .label = "COMM", .short_label = "COMM" },
    .{ .value = COLN, .label = "COLN", .short_label = "COLN" },
    .{ .value = SCLN, .label = "SCLN", .short_label = "SCLN" },
    .{ .value = HASH, .label = "HASH", .short_label = "HASH" },
    .{ .value = N1, .label = "1", .short_label = "1" },
    .{ .value = N2, .label = "2", .short_label = "2" },
    .{ .value = N3, .label = "3", .short_label = "3" },
    .{ .value = N4, .label = "4", .short_label = "4" },
    .{ .value = N5, .label = "5", .short_label = "5" },
    .{ .value = N6, .label = "6", .short_label = "6" },
    .{ .value = N7, .label = "7", .short_label = "7" },
    .{ .value = N8, .label = "8", .short_label = "8" },
    .{ .value = N9, .label = "9", .short_label = "9" },
    .{ .value = N0, .label = "0", .short_label = "0" },
    .{ .value = DQUO, .label = "DQUO", .short_label = "DQUO" },
    .{ .value = DIAE, .label = "DIAE", .short_label = "DIAE" },
    .{ .value = NDSH, .label = "NDSH", .short_label = "NDSH" },
    .{ .value = PLMN, .label = "PLMN", .short_label = "PLMN" },
    .{ .value = BSLS, .label = "BSLS", .short_label = "BSLS" },
    .{ .value = HALF, .label = "HALF", .short_label = "HALF" },
    .{ .value = RABK, .label = "RABK", .short_label = "RABK" },
    .{ .value = QUES, .label = "QUES", .short_label = "QUES" },
    .{ .value = EXLM, .label = "EXLM", .short_label = "EXLM" },
    .{ .value = ELLP, .label = "ELLP", .short_label = "ELLP" },
    .{ .value = EQL, .label = "EQL", .short_label = "EQL" },
    .{ .value = BREV, .label = "BREV", .short_label = "BREV" },
    .{ .value = SECT, .label = "SECT", .short_label = "SECT" },
    .{ .value = ACUT, .label = "ACUT", .short_label = "ACUT" },
    .{ .value = GRV, .label = "GRV", .short_label = "GRV" },
    .{ .value = AMPR, .label = "AMPR", .short_label = "AMPR" },
    .{ .value = LBRC, .label = "LBRC", .short_label = "LBRC" },
    .{ .value = RBRC, .label = "RBRC", .short_label = "RBRC" },
    .{ .value = MACR, .label = "MACR", .short_label = "MACR" },
    .{ .value = UNDS, .label = "UNDS", .short_label = "UNDS" },
    .{ .value = LDQU, .label = "LDQU", .short_label = "LDQU" },
    .{ .value = RDQU, .label = "RDQU", .short_label = "RDQU" },
    .{ .value = DEG, .label = "DEG", .short_label = "DEG" },
    .{ .value = CARN, .label = "CARN", .short_label = "CARN" },
    .{ .value = AE, .label = "AE", .short_label = "AE" },
    .{ .value = PND, .label = "PND", .short_label = "PND" },
    .{ .value = EURO, .label = "EURO", .short_label = "EURO" },
    .{ .value = REGD, .label = "REGD", .short_label = "REGD" },
    .{ .value = LCBR, .label = "LCBR", .short_label = "LCBR" },
    .{ .value = RCBR, .label = "RCBR", .short_label = "RCBR" },
    .{ .value = UGRV, .label = "UGRV", .short_label = "UGRV" },
    .{ .value = DOTA, .label = "DOTA", .short_label = "DOTA" },
    .{ .value = OE, .label = "OE", .short_label = "OE" },
    .{ .value = PERC, .label = "PERC", .short_label = "PERC" },
    .{ .value = MMNS, .label = "MMNS", .short_label = "MMNS" },
    .{ .value = DAGG, .label = "DAGG", .short_label = "DAGG" },
    .{ .value = THET, .label = "THET", .short_label = "THET" },
    .{ .value = SS, .label = "SS", .short_label = "SS" },
    .{ .value = DLR, .label = "DLR", .short_label = "DLR" },
    .{ .value = CURR, .label = "CURR", .short_label = "CURR" },
    .{ .value = DGRK, .label = "DGRK", .short_label = "DGRK" },
    .{ .value = EU, .label = "EU", .short_label = "EU" },
    .{ .value = DSLS, .label = "DSLS", .short_label = "DSLS" },
    .{ .value = PIPE, .label = "PIPE", .short_label = "PIPE" },
    .{ .value = INFN, .label = "INFN", .short_label = "INFN" },
    .{ .value = DIV, .label = "DIV", .short_label = "DIV" },
    .{ .value = MUL, .label = "MUL", .short_label = "MUL" },
    .{ .value = LEQL, .label = "LEQL", .short_label = "LEQL" },
    .{ .value = EZH, .label = "EZH", .short_label = "EZH" },
    .{ .value = COPY, .label = "COPY", .short_label = "COPY" },
    .{ .value = CCED, .label = "CCED", .short_label = "CCED" },
    .{ .value = CEDL, .label = "CEDL", .short_label = "CEDL" },
    .{ .value = DMNS, .label = "DMNS", .short_label = "DMNS" },
    .{ .value = DTIL, .label = "DTIL", .short_label = "DTIL" },
    .{ .value = IQUE, .label = "IQUE", .short_label = "IQUE" },
    .{ .value = IEXL, .label = "IEXL", .short_label = "IEXL" },
    .{ .value = MDDT, .label = "MDDT", .short_label = "MDDT" },
    .{ .value = AEQL, .label = "AEQL", .short_label = "AEQL" },
    .{ .value = IBRV, .label = "IBRV", .short_label = "IBRV" },
    .{ .value = DACU, .label = "DACU", .short_label = "DACU" },
    .{ .value = DGRV, .label = "DGRV", .short_label = "DGRV" },
    .{ .value = MDSH, .label = "MDSH", .short_label = "MDSH" },
    .{ .value = LSAQ, .label = "LSAQ", .short_label = "LSAQ" },
    .{ .value = RSAQ, .label = "RSAQ", .short_label = "RSAQ" },
    .{ .value = RNGA, .label = "RNGA", .short_label = "RNGA" },
    .{ .value = TM, .label = "TM", .short_label = "TM" },
    .{ .value = DOTB, .label = "DOTB", .short_label = "DOTB" },
    .{ .value = PERM, .label = "PERM", .short_label = "PERM" },
    .{ .value = NBHY, .label = "NBHY", .short_label = "NBHY" },
    .{ .value = DDAG, .label = "DDAG", .short_label = "DDAG" },
    .{ .value = MACB, .label = "MACB", .short_label = "MACB" },
    .{ .value = SQRT, .label = "SQRT", .short_label = "SQRT" },
    .{ .value = QRTR, .label = "QRTR", .short_label = "QRTR" },
    .{ .value = GEQL, .label = "GEQL", .short_label = "GEQL" },
    .{ .value = OGON, .label = "OGON", .short_label = "OGON" },
    .{ .value = DCMM, .label = "DCMM", .short_label = "DCMM" },
    .{ .value = NEQL, .label = "NEQL", .short_label = "NEQL" },
};

pub fn getLabel(keycode: core.KeyCodeFire, shortest: bool) ?[]const u8 {
    return zkc_core.getLabel(&_labels, keycode, shortest);
}
