// Copyright 2026 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by zkeycodes from QMK hjson keycode files
const zkc_core = @import("../src/core.zig");
const core = @import("zigmkay").core;
const L_SFT = zkc_core.L_SFT;
const L_ALT = zkc_core.L_ALT;
const R_ALT = zkc_core.R_ALT;
const R_CTL = zkc_core.R_CTL;
const DEAD = zkc_core.DEAD;
pub const keycodes = @import("keycodes.zig");

pub const QMK_GERMAN_MAC_ISO_KEYCODES_VERSION = "0.0.1";
pub const QMK_GERMAN_MAC_ISO_KEYCODES_VERSION_BCD = @as(c_int, 0x00000001);
pub const QMK_GERMAN_MAC_ISO_KEYCODES_VERSION_MAJOR = @as(c_int, 0);
pub const QMK_GERMAN_MAC_ISO_KEYCODES_VERSION_MINOR = @as(c_int, 0);
pub const QMK_GERMAN_MAC_ISO_KEYCODES_VERSION_PATCH = @as(c_int, 1);

//
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
// │ ^ │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ ß │ ´ │     │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
// │     │ Q │ W │ E │ R │ T │ Z │ U │ I │ O │ P │ Ü │ + │   │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐  │
// │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ Ö │ Ä │ # │  │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴──┤
// │    │ < │ Y │ X │ C │ V │ B │ N │ M │ , │ . │ - │        │
// ├────┴┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
// │     │    │     │                       │     │    │     │
// └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
//
/// ^ (dead)
pub const CIRC = DEAD(keycodes.kcf.GRV);
/// 1
pub const N1 = keycodes.kcf.N1;
/// 2
pub const N2 = keycodes.kcf.N2;
/// 3
pub const N3 = keycodes.kcf.N3;
/// 4
pub const N4 = keycodes.kcf.N4;
/// 5
pub const N5 = keycodes.kcf.N5;
/// 6
pub const N6 = keycodes.kcf.N6;
/// 7
pub const N7 = keycodes.kcf.N7;
/// 8
pub const N8 = keycodes.kcf.N8;
/// 9
pub const N9 = keycodes.kcf.N9;
/// 0
pub const N0 = keycodes.kcf.N0;
/// ß
pub const SS = keycodes.kcf.MINS;
/// ´ (dead)
pub const ACUT = DEAD(keycodes.kcf.EQL);
/// Q
pub const Q = keycodes.kcf.Q;
/// W
pub const W = keycodes.kcf.W;
/// E
pub const E = keycodes.kcf.E;
/// R
pub const R = keycodes.kcf.R;
/// T
pub const T = keycodes.kcf.T;
/// Z
pub const Z = keycodes.kcf.Y;
/// U
pub const U = keycodes.kcf.U;
/// I
pub const I = keycodes.kcf.I;
/// O
pub const O = keycodes.kcf.O;
/// P
pub const P = keycodes.kcf.P;
/// Ü
pub const UDIA = keycodes.kcf.LBRC;
/// +
pub const PLUS = keycodes.kcf.RBRC;
/// A
pub const A = keycodes.kcf.A;
/// S
pub const S = keycodes.kcf.S;
/// D
pub const D = keycodes.kcf.D;
/// F
pub const F = keycodes.kcf.F;
/// G
pub const G = keycodes.kcf.G;
/// H
pub const H = keycodes.kcf.H;
/// J
pub const J = keycodes.kcf.J;
/// K
pub const K = keycodes.kcf.K;
/// L
pub const L = keycodes.kcf.L;
/// Ö
pub const ODIA = keycodes.kcf.SCLN;
/// Ä
pub const ADIA = keycodes.kcf.QUOT;
/// #
pub const HASH = keycodes.kcf.NUHS;
/// <
pub const LABK = keycodes.kcf.NUBS;
/// Y
pub const Y = keycodes.kcf.Z;
/// X
pub const X = keycodes.kcf.X;
/// C
pub const C = keycodes.kcf.C;
/// V
pub const V = keycodes.kcf.V;
/// B
pub const B = keycodes.kcf.B;
/// N
pub const N = keycodes.kcf.N;
/// M
pub const M = keycodes.kcf.M;
/// ,
pub const COMM = keycodes.kcf.COMM;
/// .
pub const DOT = keycodes.kcf.DOT;
/// -
pub const MINS = keycodes.kcf.SLSH;
// Shifted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
// │ ° │ ! │ " │ § │ $ │ % │ & │ / │ ( │ ) │ = │ ? │ ` │     │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
// │     │   │   │   │   │   │   │   │   │   │   │   │ * │   │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐  │
// │      │   │   │   │   │   │   │   │   │   │   │   │ ' │  │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴──┤
// │    │ > │   │   │   │   │   │   │   │ ; │ : │ _ │        │
// ├────┴┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
// │     │    │     │                       │     │    │     │
// └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
//
/// °
pub const DEG = L_SFT(CIRC);
/// !
pub const EXLM = L_SFT(N1);
/// "
pub const DQUO = L_SFT(N2);
/// §
pub const SECT = L_SFT(N3);
/// $
pub const DLR = L_SFT(N4);
/// %
pub const PERC = L_SFT(N5);
/// &
pub const AMPR = L_SFT(N6);
/// /
pub const SLSH = L_SFT(N7);
/// (
pub const LPRN = L_SFT(N8);
/// )
pub const RPRN = L_SFT(N9);
/// =
pub const EQL = L_SFT(N0);
/// ?
pub const QUES = L_SFT(SS);
/// ` (dead)
pub const GRV = DEAD(L_SFT(ACUT));
/// *
pub const ASTR = L_SFT(PLUS);
/// '
pub const QUOT = L_SFT(HASH);
/// >
pub const RABK = L_SFT(LABK);
/// ;
pub const SCLN = L_SFT(COMM);
/// :
pub const COLN = L_SFT(DOT);
/// _
pub const UNDS = L_SFT(MINS);
// Alted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
// │ „ │ ¡ │ “ │ ¶ │ ¢ │ [ │ ] │ | │ { │ } │ ≠ │ ¿ │   │     │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
// │     │ « │ ∑ │ € │ ® │ † │ Ω │ ¨ │ ⁄ │ Ø │ π │ • │ ± │   │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐  │
// │      │ Å │ ‚ │ ∂ │ ƒ │ © │ ª │ º │ ∆ │ @ │ Œ │ Æ │ ‘ │  │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴──┤
// │    │ ≤ │ ¥ │ ≈ │ Ç │ √ │ ∫ │ ~ │ µ │ ∞ │ … │ – │        │
// ├────┴┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
// │     │    │     │                       │     │    │     │
// └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
//
/// „
pub const DLQU = L_ALT(CIRC);
/// ¡
pub const IEXL = L_ALT(N1);
/// “
pub const LDQU = L_ALT(N2);
/// ¶
pub const PILC = L_ALT(N3);
/// ¢
pub const CENT = L_ALT(N4);
/// [
pub const LBRC = L_ALT(N5);
/// ]
pub const RBRC = L_ALT(N6);
/// |
pub const PIPE = L_ALT(N7);
/// {
pub const LCBR = L_ALT(N8);
/// }
pub const RCBR = L_ALT(N9);
/// ≠
pub const NEQL = L_ALT(N0);
/// ¿
pub const IQUE = L_ALT(SS);
/// «
pub const LDAQ = L_ALT(Q);
/// ∑
pub const NARS = L_ALT(W);
/// €
pub const EURO = L_ALT(E);
/// ®
pub const REGD = L_ALT(R);
/// †
pub const DAGG = L_ALT(T);
/// Ω
pub const OMEG = L_ALT(Z);
/// ¨ (dead)
pub const DIAE = DEAD(L_ALT(U));
/// ⁄
pub const FRSL = L_ALT(I);
/// Ø
pub const OSTR = L_ALT(O);
/// π
pub const PI = L_ALT(P);
/// •
pub const BULT = L_ALT(UDIA);
/// ±
pub const PLMN = L_ALT(PLUS);
/// Å
pub const ARNG = L_ALT(A);
/// ‚
pub const SLQU = L_ALT(S);
/// ∂
pub const PDIF = L_ALT(D);
/// ƒ
pub const FHK = L_ALT(F);
/// ©
pub const COPY = L_ALT(G);
/// ª
pub const FORD = L_ALT(H);
/// º
pub const MORD = L_ALT(J);
/// ∆
pub const INCR = L_ALT(K);
/// @
pub const AT = L_ALT(L);
/// Œ
pub const OE = L_ALT(ODIA);
/// Æ
pub const AE = L_ALT(ADIA);
/// ‘
pub const LSQU = L_ALT(HASH);
/// ≤
pub const LTEQ = L_ALT(LABK);
/// ¥
pub const YEN = L_ALT(Y);
/// ≈
pub const AEQL = L_ALT(X);
/// Ç
pub const CCCE = L_ALT(C);
/// √
pub const SQRT = L_ALT(V);
/// ∫
pub const INTG = L_ALT(B);
/// ~ (dead)
pub const TILD = DEAD(L_ALT(N));
/// µ
pub const MICR = L_ALT(M);
/// ∞
pub const INFN = L_ALT(COMM);
/// …
pub const ELLP = L_ALT(DOT);
/// –
pub const NDSH = L_ALT(MINS);
// Shift+Alted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
// │   │ ¬ │ ” │   │ £ │ ﬁ │   │ \ │ ˜ │ · │ ¯ │ ˙ │ ˚ │     │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
// │     │ » │   │ ‰ │ ¸ │ ˝ │ ˇ │ Á │ Û │   │ ∏ │   │  │   │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐  │
// │      │   │ Í │ ™ │ Ï │ Ì │ Ó │ ı │   │ ﬂ │   │   │   │  │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴──┤
// │    │ ≥ │ ‡ │ Ù │   │ ◊ │ ‹ │ › │ ˘ │ ˛ │ ÷ │ — │        │
// ├────┴┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
// │     │    │     │                       │     │    │     │
// └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
//
/// ¬
pub const NOT = L_SFT(L_ALT(N1));
/// ”
pub const RDQU = L_SFT(L_ALT(N2));
/// £
pub const PND = L_SFT(L_ALT(N4));
/// ﬁ
pub const FI = L_SFT(L_ALT(N5));
/// (backslash)
pub const BSLS = L_SFT(L_ALT(N7));
/// ˜
pub const STIL = L_SFT(L_ALT(N8));
/// ·
pub const MDDT = L_SFT(L_ALT(N9));
/// ¯
pub const MACR = L_SFT(L_ALT(N0));
/// ˙
pub const DOTA = L_SFT(L_ALT(SS));
/// ˚
pub const RNGA = L_SFT(L_ALT(ACUT));
/// »
pub const RDAQ = L_SFT(L_ALT(Q));
/// ‰
pub const PERM = L_SFT(L_ALT(E));
/// ¸
pub const CEDL = L_SFT(L_ALT(R));
/// ˝
pub const DACU = L_SFT(L_ALT(T));
/// ˇ
pub const CARN = L_SFT(L_ALT(Z));
/// Á
pub const AACU = L_SFT(L_ALT(U));
/// Û
pub const UCIR = L_SFT(L_ALT(I));
/// ∏
pub const NARP = L_SFT(L_ALT(P));
///  (Apple logo)
pub const APPL = L_SFT(L_ALT(PLUS));
/// Í
pub const IACU = L_SFT(L_ALT(S));
/// ™
pub const TM = L_SFT(L_ALT(D));
/// Ï
pub const IDIA = L_SFT(L_ALT(F));
/// Ì
pub const IGRV = L_SFT(L_ALT(G));
/// Ó
pub const OACU = L_SFT(L_ALT(H));
/// ı
pub const DLSI = L_SFT(L_ALT(J));
/// ﬂ
pub const FL = L_SFT(L_ALT(L));
/// ≥
pub const GTEQ = L_SFT(L_ALT(LABK));
/// ‡
pub const DDAG = L_SFT(L_ALT(Y));
/// Ù
pub const UGRV = L_SFT(L_ALT(X));
/// ◊
pub const LOZN = L_SFT(L_ALT(V));
/// ‹
pub const LSAQ = L_SFT(L_ALT(B));
/// ›
pub const RSAQ = L_SFT(L_ALT(N));
/// ˘
pub const BREV = L_SFT(L_ALT(M));
/// ˛
pub const OGON = L_SFT(L_ALT(COMM));
/// ÷
pub const DIV = L_SFT(L_ALT(DOT));
/// —
pub const MDSH = L_SFT(L_ALT(MINS));

// Label lookup table
pub const _labels = [_]zkc_core.LabelEntry{
    .{ .value = CIRC, .label = "CIRC", .short_label = "CIRC" },
    .{ .value = N1, .label = "1", .short_label = "1" },
    .{ .value = N2, .label = "2", .short_label = "2" },
    .{ .value = N3, .label = "3", .short_label = "3" },
    .{ .value = N4, .label = "4", .short_label = "4" },
    .{ .value = N5, .label = "5", .short_label = "5" },
    .{ .value = N6, .label = "6", .short_label = "6" },
    .{ .value = N7, .label = "7", .short_label = "7" },
    .{ .value = N8, .label = "8", .short_label = "8" },
    .{ .value = N9, .label = "9", .short_label = "9" },
    .{ .value = N0, .label = "0", .short_label = "0" },
    .{ .value = SS, .label = "SS", .short_label = "SS" },
    .{ .value = ACUT, .label = "ACUT", .short_label = "ACUT" },
    .{ .value = Q, .label = "Q", .short_label = "Q" },
    .{ .value = W, .label = "W", .short_label = "W" },
    .{ .value = E, .label = "E", .short_label = "E" },
    .{ .value = R, .label = "R", .short_label = "R" },
    .{ .value = T, .label = "T", .short_label = "T" },
    .{ .value = Z, .label = "Z", .short_label = "Z" },
    .{ .value = U, .label = "U", .short_label = "U" },
    .{ .value = I, .label = "I", .short_label = "I" },
    .{ .value = O, .label = "O", .short_label = "O" },
    .{ .value = P, .label = "P", .short_label = "P" },
    .{ .value = UDIA, .label = "UDIA", .short_label = "UDIA" },
    .{ .value = PLUS, .label = "PLUS", .short_label = "PLUS" },
    .{ .value = A, .label = "A", .short_label = "A" },
    .{ .value = S, .label = "S", .short_label = "S" },
    .{ .value = D, .label = "D", .short_label = "D" },
    .{ .value = F, .label = "F", .short_label = "F" },
    .{ .value = G, .label = "G", .short_label = "G" },
    .{ .value = H, .label = "H", .short_label = "H" },
    .{ .value = J, .label = "J", .short_label = "J" },
    .{ .value = K, .label = "K", .short_label = "K" },
    .{ .value = L, .label = "L", .short_label = "L" },
    .{ .value = ODIA, .label = "ODIA", .short_label = "ODIA" },
    .{ .value = ADIA, .label = "ADIA", .short_label = "ADIA" },
    .{ .value = HASH, .label = "HASH", .short_label = "HASH" },
    .{ .value = LABK, .label = "LABK", .short_label = "LABK" },
    .{ .value = Y, .label = "Y", .short_label = "Y" },
    .{ .value = X, .label = "X", .short_label = "X" },
    .{ .value = C, .label = "C", .short_label = "C" },
    .{ .value = V, .label = "V", .short_label = "V" },
    .{ .value = B, .label = "B", .short_label = "B" },
    .{ .value = N, .label = "N", .short_label = "N" },
    .{ .value = M, .label = "M", .short_label = "M" },
    .{ .value = COMM, .label = "COMM", .short_label = "COMM" },
    .{ .value = DOT, .label = "DOT", .short_label = "DOT" },
    .{ .value = MINS, .label = "MINS", .short_label = "MINS" },
    .{ .value = DEG, .label = "DEG", .short_label = "DEG" },
    .{ .value = EXLM, .label = "EXLM", .short_label = "EXLM" },
    .{ .value = DQUO, .label = "DQUO", .short_label = "DQUO" },
    .{ .value = SECT, .label = "SECT", .short_label = "SECT" },
    .{ .value = DLR, .label = "DLR", .short_label = "DLR" },
    .{ .value = PERC, .label = "PERC", .short_label = "PERC" },
    .{ .value = AMPR, .label = "AMPR", .short_label = "AMPR" },
    .{ .value = SLSH, .label = "SLSH", .short_label = "SLSH" },
    .{ .value = LPRN, .label = "LPRN", .short_label = "LPRN" },
    .{ .value = RPRN, .label = "RPRN", .short_label = "RPRN" },
    .{ .value = EQL, .label = "EQL", .short_label = "EQL" },
    .{ .value = QUES, .label = "QUES", .short_label = "QUES" },
    .{ .value = GRV, .label = "GRV", .short_label = "GRV" },
    .{ .value = ASTR, .label = "ASTR", .short_label = "ASTR" },
    .{ .value = QUOT, .label = "QUOT", .short_label = "QUOT" },
    .{ .value = RABK, .label = "RABK", .short_label = "RABK" },
    .{ .value = SCLN, .label = "SCLN", .short_label = "SCLN" },
    .{ .value = COLN, .label = "COLN", .short_label = "COLN" },
    .{ .value = UNDS, .label = "UNDS", .short_label = "UNDS" },
    .{ .value = DLQU, .label = "DLQU", .short_label = "DLQU" },
    .{ .value = IEXL, .label = "IEXL", .short_label = "IEXL" },
    .{ .value = LDQU, .label = "LDQU", .short_label = "LDQU" },
    .{ .value = PILC, .label = "PILC", .short_label = "PILC" },
    .{ .value = CENT, .label = "CENT", .short_label = "CENT" },
    .{ .value = LBRC, .label = "LBRC", .short_label = "LBRC" },
    .{ .value = RBRC, .label = "RBRC", .short_label = "RBRC" },
    .{ .value = PIPE, .label = "PIPE", .short_label = "PIPE" },
    .{ .value = LCBR, .label = "LCBR", .short_label = "LCBR" },
    .{ .value = RCBR, .label = "RCBR", .short_label = "RCBR" },
    .{ .value = NEQL, .label = "NEQL", .short_label = "NEQL" },
    .{ .value = IQUE, .label = "IQUE", .short_label = "IQUE" },
    .{ .value = LDAQ, .label = "LDAQ", .short_label = "LDAQ" },
    .{ .value = NARS, .label = "NARS", .short_label = "NARS" },
    .{ .value = EURO, .label = "EURO", .short_label = "EURO" },
    .{ .value = REGD, .label = "REGD", .short_label = "REGD" },
    .{ .value = DAGG, .label = "DAGG", .short_label = "DAGG" },
    .{ .value = OMEG, .label = "OMEG", .short_label = "OMEG" },
    .{ .value = DIAE, .label = "DIAE", .short_label = "DIAE" },
    .{ .value = FRSL, .label = "FRSL", .short_label = "FRSL" },
    .{ .value = OSTR, .label = "OSTR", .short_label = "OSTR" },
    .{ .value = PI, .label = "PI", .short_label = "PI" },
    .{ .value = BULT, .label = "BULT", .short_label = "BULT" },
    .{ .value = PLMN, .label = "PLMN", .short_label = "PLMN" },
    .{ .value = ARNG, .label = "ARNG", .short_label = "ARNG" },
    .{ .value = SLQU, .label = "SLQU", .short_label = "SLQU" },
    .{ .value = PDIF, .label = "PDIF", .short_label = "PDIF" },
    .{ .value = FHK, .label = "FHK", .short_label = "FHK" },
    .{ .value = COPY, .label = "COPY", .short_label = "COPY" },
    .{ .value = FORD, .label = "FORD", .short_label = "FORD" },
    .{ .value = MORD, .label = "MORD", .short_label = "MORD" },
    .{ .value = INCR, .label = "INCR", .short_label = "INCR" },
    .{ .value = AT, .label = "AT", .short_label = "AT" },
    .{ .value = OE, .label = "OE", .short_label = "OE" },
    .{ .value = AE, .label = "AE", .short_label = "AE" },
    .{ .value = LSQU, .label = "LSQU", .short_label = "LSQU" },
    .{ .value = LTEQ, .label = "LTEQ", .short_label = "LTEQ" },
    .{ .value = YEN, .label = "YEN", .short_label = "YEN" },
    .{ .value = AEQL, .label = "AEQL", .short_label = "AEQL" },
    .{ .value = CCCE, .label = "CCCE", .short_label = "CCCE" },
    .{ .value = SQRT, .label = "SQRT", .short_label = "SQRT" },
    .{ .value = INTG, .label = "INTG", .short_label = "INTG" },
    .{ .value = TILD, .label = "TILD", .short_label = "TILD" },
    .{ .value = MICR, .label = "MICR", .short_label = "MICR" },
    .{ .value = INFN, .label = "INFN", .short_label = "INFN" },
    .{ .value = ELLP, .label = "ELLP", .short_label = "ELLP" },
    .{ .value = NDSH, .label = "NDSH", .short_label = "NDSH" },
    .{ .value = NOT, .label = "NOT", .short_label = "NOT" },
    .{ .value = RDQU, .label = "RDQU", .short_label = "RDQU" },
    .{ .value = PND, .label = "PND", .short_label = "PND" },
    .{ .value = FI, .label = "FI", .short_label = "FI" },
    .{ .value = BSLS, .label = "BSLS", .short_label = "BSLS" },
    .{ .value = STIL, .label = "STIL", .short_label = "STIL" },
    .{ .value = MDDT, .label = "MDDT", .short_label = "MDDT" },
    .{ .value = MACR, .label = "MACR", .short_label = "MACR" },
    .{ .value = DOTA, .label = "DOTA", .short_label = "DOTA" },
    .{ .value = RNGA, .label = "RNGA", .short_label = "RNGA" },
    .{ .value = RDAQ, .label = "RDAQ", .short_label = "RDAQ" },
    .{ .value = PERM, .label = "PERM", .short_label = "PERM" },
    .{ .value = CEDL, .label = "CEDL", .short_label = "CEDL" },
    .{ .value = DACU, .label = "DACU", .short_label = "DACU" },
    .{ .value = CARN, .label = "CARN", .short_label = "CARN" },
    .{ .value = AACU, .label = "AACU", .short_label = "AACU" },
    .{ .value = UCIR, .label = "UCIR", .short_label = "UCIR" },
    .{ .value = NARP, .label = "NARP", .short_label = "NARP" },
    .{ .value = APPL, .label = "APPL", .short_label = "APPL" },
    .{ .value = IACU, .label = "IACU", .short_label = "IACU" },
    .{ .value = TM, .label = "TM", .short_label = "TM" },
    .{ .value = IDIA, .label = "IDIA", .short_label = "IDIA" },
    .{ .value = IGRV, .label = "IGRV", .short_label = "IGRV" },
    .{ .value = OACU, .label = "OACU", .short_label = "OACU" },
    .{ .value = DLSI, .label = "DLSI", .short_label = "DLSI" },
    .{ .value = FL, .label = "FL", .short_label = "FL" },
    .{ .value = GTEQ, .label = "GTEQ", .short_label = "GTEQ" },
    .{ .value = DDAG, .label = "DDAG", .short_label = "DDAG" },
    .{ .value = UGRV, .label = "UGRV", .short_label = "UGRV" },
    .{ .value = LOZN, .label = "LOZN", .short_label = "LOZN" },
    .{ .value = LSAQ, .label = "LSAQ", .short_label = "LSAQ" },
    .{ .value = RSAQ, .label = "RSAQ", .short_label = "RSAQ" },
    .{ .value = BREV, .label = "BREV", .short_label = "BREV" },
    .{ .value = OGON, .label = "OGON", .short_label = "OGON" },
    .{ .value = DIV, .label = "DIV", .short_label = "DIV" },
    .{ .value = MDSH, .label = "MDSH", .short_label = "MDSH" },
};

pub fn getLabel(keycode: core.KeyCodeFire, shortest: bool) ?[]const u8 {
    return zkc_core.getLabel(&_labels, keycode, shortest);
}
