// Copyright 2026 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by zkeycodes from QMK hjson keycode files
const zkc_core = @import("../src/core.zig");
const core = @import("zigmkay").core;
const L_SFT = zkc_core.L_SFT;
const L_ALT = zkc_core.L_ALT;
const R_ALT = zkc_core.R_ALT;
const R_CTL = zkc_core.R_CTL;
const DEAD = zkc_core.DEAD;
pub const keycodes = @import("keycodes.zig");

pub const QMK_HEBREW_KEYCODES_VERSION = "0.0.1";
pub const QMK_HEBREW_KEYCODES_VERSION_BCD = @as(c_int, 0x00000001);
pub const QMK_HEBREW_KEYCODES_VERSION_MAJOR = @as(c_int, 0);
pub const QMK_HEBREW_KEYCODES_VERSION_MINOR = @as(c_int, 0);
pub const QMK_HEBREW_KEYCODES_VERSION_PATCH = @as(c_int, 1);

//
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ; │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ - │ = │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ / │ ' │ פ │ ם │ ן │ ו │ ט │ א │ ר │ ק │ ] │ [ │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │ ף │ ך │ ל │ ח │ י │ ע │ כ │ ג │ ד │ ש │ , │ \ │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │   │ ץ │ ת │ צ │ מ │ נ │ ה │ ב │ ס │ ז │ . │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ;
pub const SCLN = keycodes.kcf.GRV;
/// 1
pub const N1 = keycodes.kcf.N1;
/// 2
pub const N2 = keycodes.kcf.N2;
/// 3
pub const N3 = keycodes.kcf.N3;
/// 4
pub const N4 = keycodes.kcf.N4;
/// 5
pub const N5 = keycodes.kcf.N5;
/// 6
pub const N6 = keycodes.kcf.N6;
/// 7
pub const N7 = keycodes.kcf.N7;
/// 8
pub const N8 = keycodes.kcf.N8;
/// 9
pub const N9 = keycodes.kcf.N9;
/// 0
pub const N0 = keycodes.kcf.N0;
/// -
pub const MINS = keycodes.kcf.MINS;
/// =
pub const EQL = keycodes.kcf.EQL;
/// /
pub const SLSH = keycodes.kcf.Q;
/// '
pub const QUOT = keycodes.kcf.W;
/// ק
pub const QOF = keycodes.kcf.E;
/// ר
pub const RESH = keycodes.kcf.R;
/// א
pub const ALEF = keycodes.kcf.T;
/// ט
pub const TET = keycodes.kcf.Y;
/// ו
pub const VAV = keycodes.kcf.U;
/// ן
pub const FNUN = keycodes.kcf.I;
/// ם
pub const FMEM = keycodes.kcf.O;
/// פ
pub const PE = keycodes.kcf.P;
/// ]
pub const RBRC = keycodes.kcf.LBRC;
/// [
pub const LBRC = keycodes.kcf.RBRC;
/// ש
pub const SHIN = keycodes.kcf.A;
/// ד
pub const DALT = keycodes.kcf.S;
/// ג
pub const GIML = keycodes.kcf.D;
/// כ
pub const KAF = keycodes.kcf.F;
/// ע
pub const AYIN = keycodes.kcf.G;
/// י
pub const YOD = keycodes.kcf.H;
/// ח
pub const HET = keycodes.kcf.J;
/// ל
pub const LAMD = keycodes.kcf.K;
/// ך
pub const FKAF = keycodes.kcf.L;
/// ף
pub const FPE = keycodes.kcf.SCLN;
/// ,
pub const COMM = keycodes.kcf.QUOT;
/// (backslash)
pub const BSLS = keycodes.kcf.NUHS;
/// ז
pub const ZAYN = keycodes.kcf.Z;
/// ס
pub const SMKH = keycodes.kcf.X;
/// ב
pub const BET = keycodes.kcf.C;
/// ה
pub const HE = keycodes.kcf.V;
/// נ
pub const NUN = keycodes.kcf.B;
/// מ
pub const MEM = keycodes.kcf.N;
/// צ
pub const TSDI = keycodes.kcf.M;
/// ת
pub const TAV = keycodes.kcf.COMM;
/// ץ
pub const FTSD = keycodes.kcf.DOT;
/// .
pub const DOT = keycodes.kcf.SLSH;
// Shifted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ~ │ ! │ @ │ # │ $ │ % │ ^ │ & │ * │ ) │ ( │ _ │ + │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │   │   │   │   │   │   │   │   │ } │ { │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │   │   │   │   │   │   │   │   │   │ : │ " │ | │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │   │   │   │   │   │   │   │   │ > │ < │ ? │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ~
pub const TILD = L_SFT(SCLN);
/// !
pub const EXLM = L_SFT(N1);
/// @
pub const AT = L_SFT(N2);
/// #
pub const PND = L_SFT(N3);
/// $
pub const DLR = L_SFT(N4);
/// %
pub const PERC = L_SFT(N5);
/// ^
pub const CIRC = L_SFT(N6);
/// &
pub const AMPR = L_SFT(N7);
/// *
pub const ASTR = L_SFT(N8);
/// )
pub const RPRN = L_SFT(N9);
/// (
pub const LPRN = L_SFT(N0);
/// _
pub const UNDS = L_SFT(MINS);
/// +
pub const PLUS = L_SFT(EQL);
/// }
pub const RCBR = L_SFT(RBRC);
/// {
pub const LCBR = L_SFT(LBRC);
/// :
pub const COLN = L_SFT(FPE);
/// "
pub const DQUO = L_SFT(COMM);
/// |
pub const PIPE = L_SFT(BSLS);
/// >
pub const RABK = L_SFT(TAV);
/// <
pub const LABK = L_SFT(FTSD);
/// ?
pub const QUES = L_SFT(DOT);
// AltGr symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │   │   │   │ € │ ₪ │ ° │   │   │ × │   │   │   │   │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │   │   │   │ װ │   │   │   │   │   │   │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │   │   │   │   │ ײ │ ױ │   │   │   │   │   │   │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │   │   │   │   │   │   │   │   │   │   │ ÷ │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// €
pub const EURO = R_ALT(N3);
/// ₪
pub const SHKL = R_ALT(N4);
/// °
pub const DEG = R_ALT(N5);
/// ×
pub const MUL = R_ALT(N8);
/// װ
pub const DVAV = R_ALT(TET);
/// ױ
pub const VYOD = R_ALT(AYIN);
/// ײ
pub const DYOD = R_ALT(YOD);
/// ÷
pub const DIV = R_ALT(DOT);

// Label lookup table
pub const _labels = [_]zkc_core.LabelEntry{
    .{ .value = SCLN, .label = "SCLN", .short_label = "SCLN" },
    .{ .value = N1, .label = "1", .short_label = "1" },
    .{ .value = N2, .label = "2", .short_label = "2" },
    .{ .value = N3, .label = "3", .short_label = "3" },
    .{ .value = N4, .label = "4", .short_label = "4" },
    .{ .value = N5, .label = "5", .short_label = "5" },
    .{ .value = N6, .label = "6", .short_label = "6" },
    .{ .value = N7, .label = "7", .short_label = "7" },
    .{ .value = N8, .label = "8", .short_label = "8" },
    .{ .value = N9, .label = "9", .short_label = "9" },
    .{ .value = N0, .label = "0", .short_label = "0" },
    .{ .value = MINS, .label = "MINS", .short_label = "MINS" },
    .{ .value = EQL, .label = "EQL", .short_label = "EQL" },
    .{ .value = SLSH, .label = "SLSH", .short_label = "SLSH" },
    .{ .value = QUOT, .label = "QUOT", .short_label = "QUOT" },
    .{ .value = QOF, .label = "QOF", .short_label = "QOF" },
    .{ .value = RESH, .label = "RESH", .short_label = "RESH" },
    .{ .value = ALEF, .label = "ALEF", .short_label = "ALEF" },
    .{ .value = TET, .label = "TET", .short_label = "TET" },
    .{ .value = VAV, .label = "VAV", .short_label = "VAV" },
    .{ .value = FNUN, .label = "FNUN", .short_label = "FNUN" },
    .{ .value = FMEM, .label = "FMEM", .short_label = "FMEM" },
    .{ .value = PE, .label = "PE", .short_label = "PE" },
    .{ .value = RBRC, .label = "RBRC", .short_label = "RBRC" },
    .{ .value = LBRC, .label = "LBRC", .short_label = "LBRC" },
    .{ .value = SHIN, .label = "SHIN", .short_label = "SHIN" },
    .{ .value = DALT, .label = "DALT", .short_label = "DALT" },
    .{ .value = GIML, .label = "GIML", .short_label = "GIML" },
    .{ .value = KAF, .label = "KAF", .short_label = "KAF" },
    .{ .value = AYIN, .label = "AYIN", .short_label = "AYIN" },
    .{ .value = YOD, .label = "YOD", .short_label = "YOD" },
    .{ .value = HET, .label = "HET", .short_label = "HET" },
    .{ .value = LAMD, .label = "LAMD", .short_label = "LAMD" },
    .{ .value = FKAF, .label = "FKAF", .short_label = "FKAF" },
    .{ .value = FPE, .label = "FPE", .short_label = "FPE" },
    .{ .value = COMM, .label = "COMM", .short_label = "COMM" },
    .{ .value = BSLS, .label = "BSLS", .short_label = "BSLS" },
    .{ .value = ZAYN, .label = "ZAYN", .short_label = "ZAYN" },
    .{ .value = SMKH, .label = "SMKH", .short_label = "SMKH" },
    .{ .value = BET, .label = "BET", .short_label = "BET" },
    .{ .value = HE, .label = "HE", .short_label = "HE" },
    .{ .value = NUN, .label = "NUN", .short_label = "NUN" },
    .{ .value = MEM, .label = "MEM", .short_label = "MEM" },
    .{ .value = TSDI, .label = "TSDI", .short_label = "TSDI" },
    .{ .value = TAV, .label = "TAV", .short_label = "TAV" },
    .{ .value = FTSD, .label = "FTSD", .short_label = "FTSD" },
    .{ .value = DOT, .label = "DOT", .short_label = "DOT" },
    .{ .value = TILD, .label = "TILD", .short_label = "TILD" },
    .{ .value = EXLM, .label = "EXLM", .short_label = "EXLM" },
    .{ .value = AT, .label = "AT", .short_label = "AT" },
    .{ .value = PND, .label = "PND", .short_label = "PND" },
    .{ .value = DLR, .label = "DLR", .short_label = "DLR" },
    .{ .value = PERC, .label = "PERC", .short_label = "PERC" },
    .{ .value = CIRC, .label = "CIRC", .short_label = "CIRC" },
    .{ .value = AMPR, .label = "AMPR", .short_label = "AMPR" },
    .{ .value = ASTR, .label = "ASTR", .short_label = "ASTR" },
    .{ .value = RPRN, .label = "RPRN", .short_label = "RPRN" },
    .{ .value = LPRN, .label = "LPRN", .short_label = "LPRN" },
    .{ .value = UNDS, .label = "UNDS", .short_label = "UNDS" },
    .{ .value = PLUS, .label = "PLUS", .short_label = "PLUS" },
    .{ .value = RCBR, .label = "RCBR", .short_label = "RCBR" },
    .{ .value = LCBR, .label = "LCBR", .short_label = "LCBR" },
    .{ .value = COLN, .label = "COLN", .short_label = "COLN" },
    .{ .value = DQUO, .label = "DQUO", .short_label = "DQUO" },
    .{ .value = PIPE, .label = "PIPE", .short_label = "PIPE" },
    .{ .value = RABK, .label = "RABK", .short_label = "RABK" },
    .{ .value = LABK, .label = "LABK", .short_label = "LABK" },
    .{ .value = QUES, .label = "QUES", .short_label = "QUES" },
    .{ .value = EURO, .label = "EURO", .short_label = "EURO" },
    .{ .value = SHKL, .label = "SHKL", .short_label = "SHKL" },
    .{ .value = DEG, .label = "DEG", .short_label = "DEG" },
    .{ .value = MUL, .label = "MUL", .short_label = "MUL" },
    .{ .value = DVAV, .label = "DVAV", .short_label = "DVAV" },
    .{ .value = VYOD, .label = "VYOD", .short_label = "VYOD" },
    .{ .value = DYOD, .label = "DYOD", .short_label = "DYOD" },
    .{ .value = DIV, .label = "DIV", .short_label = "DIV" },
};

pub fn getLabel(keycode: core.KeyCodeFire, shortest: bool) ?[]const u8 {
    return zkc_core.getLabel(&_labels, keycode, shortest);
}
