// Copyright 2026 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by zkeycodes from QMK hjson keycode files
const zkc_core = @import("../src/core.zig");
const core = @import("zigmkay").core;
const L_SFT = zkc_core.L_SFT;
const L_ALT = zkc_core.L_ALT;
const R_ALT = zkc_core.R_ALT;
const R_CTL = zkc_core.R_CTL;
const DEAD = zkc_core.DEAD;
pub const keycodes = @import("keycodes.zig");

pub const QMK_ITALIAN_MAC_ANSI_KEYCODES_VERSION = "0.0.1";
pub const QMK_ITALIAN_MAC_ANSI_KEYCODES_VERSION_BCD = @as(c_int, 0x00000001);
pub const QMK_ITALIAN_MAC_ANSI_KEYCODES_VERSION_MAJOR = @as(c_int, 0);
pub const QMK_ITALIAN_MAC_ANSI_KEYCODES_VERSION_MINOR = @as(c_int, 0);
pub const QMK_ITALIAN_MAC_ANSI_KEYCODES_VERSION_PATCH = @as(c_int, 1);

//
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
// │ < │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ ' │ ì │     │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
// │     │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │ è │ + │ ù │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴───┤
// │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ ò │ à │      │
// ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴──────┤
// │        │ Z │ X │ C │ V │ B │ N │ M │ , │ . │ - │        │
// ├─────┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
// │     │    │     │                       │     │    │     │
// └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
//
/// <
pub const LABK = keycodes.kcf.GRV;
/// 1
pub const N1 = keycodes.kcf.N1;
/// 2
pub const N2 = keycodes.kcf.N2;
/// 3
pub const N3 = keycodes.kcf.N3;
/// 4
pub const N4 = keycodes.kcf.N4;
/// 5
pub const N5 = keycodes.kcf.N5;
/// 6
pub const N6 = keycodes.kcf.N6;
/// 7
pub const N7 = keycodes.kcf.N7;
/// 8
pub const N8 = keycodes.kcf.N8;
/// 9
pub const N9 = keycodes.kcf.N9;
/// 0
pub const N0 = keycodes.kcf.N0;
/// '
pub const QUOT = keycodes.kcf.MINS;
/// ì
pub const IGRV = keycodes.kcf.EQL;
/// Q
pub const Q = keycodes.kcf.Q;
/// W
pub const W = keycodes.kcf.W;
/// E
pub const E = keycodes.kcf.E;
/// R
pub const R = keycodes.kcf.R;
/// T
pub const T = keycodes.kcf.T;
/// Y
pub const Y = keycodes.kcf.Y;
/// U
pub const U = keycodes.kcf.U;
/// I
pub const I = keycodes.kcf.I;
/// O
pub const O = keycodes.kcf.O;
/// P
pub const P = keycodes.kcf.P;
/// è
pub const EGRV = keycodes.kcf.LBRC;
/// +
pub const PLUS = keycodes.kcf.RBRC;
/// ù
pub const UGRV = keycodes.kcf.BSLS;
/// A
pub const A = keycodes.kcf.A;
/// S
pub const S = keycodes.kcf.S;
/// D
pub const D = keycodes.kcf.D;
/// F
pub const F = keycodes.kcf.F;
/// G
pub const G = keycodes.kcf.G;
/// H
pub const H = keycodes.kcf.H;
/// J
pub const J = keycodes.kcf.J;
/// K
pub const K = keycodes.kcf.K;
/// L
pub const L = keycodes.kcf.L;
/// ò
pub const OGRV = keycodes.kcf.SCLN;
/// à
pub const AGRV = keycodes.kcf.QUOT;
/// (backslash, not physically present)
pub const BSLS = keycodes.kcf.NUBS;
/// Z
pub const Z = keycodes.kcf.Z;
/// X
pub const X = keycodes.kcf.X;
/// C
pub const C = keycodes.kcf.C;
/// V
pub const V = keycodes.kcf.V;
/// B
pub const B = keycodes.kcf.B;
/// N
pub const N = keycodes.kcf.N;
/// M
pub const M = keycodes.kcf.M;
/// ,
pub const COMM = keycodes.kcf.COMM;
/// .
pub const DOT = keycodes.kcf.DOT;
/// -
pub const MINS = keycodes.kcf.SLSH;
// Shifted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
// │ > │ ! │ " │ £ │ $ │ % │ & │ / │ ( │ ) │ = │ ? │ ^ │     │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
// │     │   │   │   │   │   │   │   │   │   │   │ é │ * │ § │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴───┤
// │      │   │   │   │   │   │   │   │   │   │ ç │ ° │      │
// ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴──────┤
// │        │   │   │   │   │   │   │   │ ; │ : │ _ │        │
// ├─────┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
// │     │    │     │                       │     │    │     │
// └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
//
/// >
pub const RABK = L_SFT(LABK);
/// !
pub const EXLM = L_SFT(N1);
/// "
pub const DQUO = L_SFT(N2);
/// £
pub const PND = L_SFT(N3);
/// $
pub const DLR = L_SFT(N4);
/// %
pub const PERC = L_SFT(N5);
/// &
pub const AMPR = L_SFT(N6);
/// /
pub const SLSH = L_SFT(N7);
/// (
pub const LPRN = L_SFT(N8);
/// )
pub const RPRN = L_SFT(N9);
/// =
pub const EQL = L_SFT(N0);
/// ?
pub const QUES = L_SFT(QUOT);
/// ^
pub const CIRC = L_SFT(IGRV);
/// é
pub const EACU = L_SFT(EGRV);
/// *
pub const ASTR = L_SFT(PLUS);
/// §
pub const SECT = L_SFT(UGRV);
/// ç
pub const LCCE = L_SFT(OGRV);
/// °
pub const DEG = L_SFT(AGRV);
/// | (not physically present)
pub const PIPE = L_SFT(BSLS);
/// ;
pub const SCLN = L_SFT(COMM);
/// :
pub const COLN = L_SFT(DOT);
/// _
pub const UNDS = L_SFT(MINS);
// Alted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
// │ ≤ │ « │ “ │ ‘ │ ¥ │ ~ │ ‹ │ ÷ │ ´ │ ` │ ≠ │ ¡ │ ˆ │     │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
// │     │ „ │ Ω │ € │ ® │ ™ │ Æ │ ¨ │ Œ │ Ø │ π │ [ │ ] │ ¶ │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴───┤
// │      │ Å │ ß │ ∂ │ ƒ │ ∞ │ ∆ │ ª │ º │ ¬ │ @ │ # │      │
// ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴──────┤
// │        │ ∑ │ † │ © │ √ │ ∫ │ ˜ │ µ │ … │ • │ – │        │
// ├─────┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
// │     │    │     │                       │     │    │     │
// └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
//
/// ≤
pub const LTEQ = L_ALT(LABK);
/// «
pub const LDAQ = L_ALT(N1);
/// “
pub const LDQU = L_ALT(N2);
/// ‘
pub const LSQU = L_ALT(N3);
/// ¥
pub const YEN = L_ALT(N4);
/// ~
pub const TILD = L_ALT(N5);
/// ‹
pub const LSAQ = L_ALT(N6);
/// ÷
pub const DIV = L_ALT(N7);
/// ´ (dead)
pub const ACUT = DEAD(L_ALT(N8));
/// ` (dead)
pub const DGRV = DEAD(L_ALT(N9));
/// ≠
pub const NEQL = L_ALT(N0);
/// ¡
pub const IEXL = L_ALT(QUOT);
/// ˆ (dead)
pub const DCIR = DEAD(L_ALT(IGRV));
/// „
pub const DLQU = L_ALT(Q);
/// Ω
pub const OMEG = L_ALT(W);
/// €
pub const EURO = L_ALT(E);
/// ®
pub const REGD = L_ALT(R);
/// ™
pub const TM = L_ALT(T);
/// Æ
pub const AE = L_ALT(Y);
/// ¨ (dead)
pub const DIAE = DEAD(L_ALT(U));
/// Œ
pub const OE = L_ALT(I);
/// Ø
pub const OSTR = L_ALT(O);
/// π
pub const PI = L_ALT(P);
/// [
pub const LBRC = L_ALT(EGRV);
/// ]
pub const RBRC = L_ALT(PLUS);
/// Å
pub const ARNG = L_ALT(A);
/// ß
pub const SS = L_ALT(S);
/// ∂
pub const PDIF = L_ALT(D);
/// ƒ
pub const FHK = L_ALT(F);
/// ∞
pub const INFN = L_ALT(G);
/// ∆
pub const INCR = L_ALT(H);
/// ª
pub const FORD = L_ALT(J);
/// º
pub const MORD = L_ALT(K);
/// ¬
pub const NOT = L_ALT(L);
/// @
pub const AT = L_ALT(OGRV);
/// #
pub const HASH = L_ALT(AGRV);
/// ¶
pub const PILC = L_ALT(UGRV);
/// ` (not physically present)
pub const GRV = L_ALT(BSLS);
/// ∑
pub const NARS = L_ALT(Z);
/// †
pub const DAGG = L_ALT(X);
/// ©
pub const COPY = L_ALT(C);
/// √
pub const SQRT = L_ALT(V);
/// ∫
pub const INTG = L_ALT(B);
/// ˜ (dead)
pub const STIL = DEAD(L_ALT(N));
/// µ
pub const MICR = L_ALT(M);
/// …
pub const ELLP = L_ALT(COMM);
/// •
pub const BULT = L_ALT(DOT);
/// –
pub const NDSH = L_ALT(MINS);
// Shift+Alted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
// │ ≥ │ » │ ” │ ’ │ ¢ │ ‰ │ › │ ⁄ │  │   │ ≈ │ ¿ │ ± │     │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
// │     │ ‚ │ À │ È │ Ì │ Ò │   │ Ù │   │   │ ∏ │ { │ } │ ◊ │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴───┤
// │      │   │ ¯ │ ˘ │ ˙ │ ˚ │ ¸ │ ˝ │ ˛ │ ˇ │ Ç │ ∞ │      │
// ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴──────┤
// │        │   │ ‡ │ Á │ É │ Í │ Ó │ Ú │   │ · │ — │        │
// ├─────┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
// │     │    │     │                       │     │    │     │
// └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
//
/// ≥
pub const GTEQ = L_SFT(L_ALT(LABK));
/// »
pub const RDAQ = L_SFT(L_ALT(N1));
/// ”
pub const RDQU = L_SFT(L_ALT(N2));
/// ’
pub const RSQU = L_SFT(L_ALT(N3));
/// ¢
pub const CENT = L_SFT(L_ALT(N4));
/// ‰
pub const PERM = L_SFT(L_ALT(N5));
/// ›
pub const RSAQ = L_SFT(L_ALT(N6));
/// ⁄
pub const FRSL = L_SFT(L_ALT(N7));
///  (Apple logo)
pub const APPL = L_SFT(L_ALT(N8));
/// ≈
pub const AEQL = L_SFT(L_ALT(N0));
/// ¿
pub const IQUE = L_SFT(L_ALT(QUOT));
/// ±
pub const PLMN = L_SFT(L_ALT(IGRV));
/// ‚
pub const SLQU = L_SFT(L_ALT(Q));
/// À
pub const CAGR = L_SFT(L_ALT(W));
/// È
pub const CEGR = L_SFT(L_ALT(E));
/// Ì
pub const CIGR = L_SFT(L_ALT(R));
/// Ò
pub const COGR = L_SFT(L_ALT(T));
/// Ù
pub const CUGR = L_SFT(L_ALT(U));
/// ∏
pub const NARP = L_SFT(L_ALT(P));
/// {
pub const LCBR = L_SFT(L_ALT(EGRV));
/// }
pub const RCBR = L_SFT(L_ALT(PLUS));
/// ◊
pub const LOZN = L_SFT(L_ALT(UGRV));
/// ¯
pub const MACR = L_SFT(L_ALT(S));
/// ˘
pub const BREV = L_SFT(L_ALT(D));
/// ˙
pub const DOTA = L_SFT(L_ALT(F));
/// ˚
pub const RGNA = L_SFT(L_ALT(G));
/// ¸
pub const CEDL = L_SFT(L_ALT(H));
/// ˝
pub const DACU = L_SFT(L_ALT(J));
/// ˛
pub const OGON = L_SFT(L_ALT(K));
/// ˇ
pub const CARN = L_SFT(L_ALT(L));
/// Ç
pub const CCCE = L_SFT(L_ALT(OGRV));
/// ‡
pub const DDAG = L_SFT(L_ALT(X));
/// Á
pub const CAAC = L_SFT(L_ALT(C));
/// É
pub const CEAC = L_SFT(L_ALT(V));
/// Í
pub const CIAC = L_SFT(L_ALT(B));
/// Ó
pub const COAC = L_SFT(L_ALT(N));
/// Ú
pub const CUAC = L_SFT(L_ALT(M));
/// ·
pub const MDDT = L_SFT(L_ALT(DOT));
/// —
pub const MDSH = L_SFT(L_ALT(MINS));

// Label lookup table
pub const _labels = [_]zkc_core.LabelEntry{
    .{ .value = LABK, .label = "LABK", .short_label = "LABK" },
    .{ .value = N1, .label = "1", .short_label = "1" },
    .{ .value = N2, .label = "2", .short_label = "2" },
    .{ .value = N3, .label = "3", .short_label = "3" },
    .{ .value = N4, .label = "4", .short_label = "4" },
    .{ .value = N5, .label = "5", .short_label = "5" },
    .{ .value = N6, .label = "6", .short_label = "6" },
    .{ .value = N7, .label = "7", .short_label = "7" },
    .{ .value = N8, .label = "8", .short_label = "8" },
    .{ .value = N9, .label = "9", .short_label = "9" },
    .{ .value = N0, .label = "0", .short_label = "0" },
    .{ .value = QUOT, .label = "QUOT", .short_label = "QUOT" },
    .{ .value = IGRV, .label = "IGRV", .short_label = "IGRV" },
    .{ .value = Q, .label = "Q", .short_label = "Q" },
    .{ .value = W, .label = "W", .short_label = "W" },
    .{ .value = E, .label = "E", .short_label = "E" },
    .{ .value = R, .label = "R", .short_label = "R" },
    .{ .value = T, .label = "T", .short_label = "T" },
    .{ .value = Y, .label = "Y", .short_label = "Y" },
    .{ .value = U, .label = "U", .short_label = "U" },
    .{ .value = I, .label = "I", .short_label = "I" },
    .{ .value = O, .label = "O", .short_label = "O" },
    .{ .value = P, .label = "P", .short_label = "P" },
    .{ .value = EGRV, .label = "EGRV", .short_label = "EGRV" },
    .{ .value = PLUS, .label = "PLUS", .short_label = "PLUS" },
    .{ .value = UGRV, .label = "UGRV", .short_label = "UGRV" },
    .{ .value = A, .label = "A", .short_label = "A" },
    .{ .value = S, .label = "S", .short_label = "S" },
    .{ .value = D, .label = "D", .short_label = "D" },
    .{ .value = F, .label = "F", .short_label = "F" },
    .{ .value = G, .label = "G", .short_label = "G" },
    .{ .value = H, .label = "H", .short_label = "H" },
    .{ .value = J, .label = "J", .short_label = "J" },
    .{ .value = K, .label = "K", .short_label = "K" },
    .{ .value = L, .label = "L", .short_label = "L" },
    .{ .value = OGRV, .label = "OGRV", .short_label = "OGRV" },
    .{ .value = AGRV, .label = "AGRV", .short_label = "AGRV" },
    .{ .value = BSLS, .label = "BSLS", .short_label = "BSLS" },
    .{ .value = Z, .label = "Z", .short_label = "Z" },
    .{ .value = X, .label = "X", .short_label = "X" },
    .{ .value = C, .label = "C", .short_label = "C" },
    .{ .value = V, .label = "V", .short_label = "V" },
    .{ .value = B, .label = "B", .short_label = "B" },
    .{ .value = N, .label = "N", .short_label = "N" },
    .{ .value = M, .label = "M", .short_label = "M" },
    .{ .value = COMM, .label = "COMM", .short_label = "COMM" },
    .{ .value = DOT, .label = "DOT", .short_label = "DOT" },
    .{ .value = MINS, .label = "MINS", .short_label = "MINS" },
    .{ .value = RABK, .label = "RABK", .short_label = "RABK" },
    .{ .value = EXLM, .label = "EXLM", .short_label = "EXLM" },
    .{ .value = DQUO, .label = "DQUO", .short_label = "DQUO" },
    .{ .value = PND, .label = "PND", .short_label = "PND" },
    .{ .value = DLR, .label = "DLR", .short_label = "DLR" },
    .{ .value = PERC, .label = "PERC", .short_label = "PERC" },
    .{ .value = AMPR, .label = "AMPR", .short_label = "AMPR" },
    .{ .value = SLSH, .label = "SLSH", .short_label = "SLSH" },
    .{ .value = LPRN, .label = "LPRN", .short_label = "LPRN" },
    .{ .value = RPRN, .label = "RPRN", .short_label = "RPRN" },
    .{ .value = EQL, .label = "EQL", .short_label = "EQL" },
    .{ .value = QUES, .label = "QUES", .short_label = "QUES" },
    .{ .value = CIRC, .label = "CIRC", .short_label = "CIRC" },
    .{ .value = EACU, .label = "EACU", .short_label = "EACU" },
    .{ .value = ASTR, .label = "ASTR", .short_label = "ASTR" },
    .{ .value = SECT, .label = "SECT", .short_label = "SECT" },
    .{ .value = LCCE, .label = "LCCE", .short_label = "LCCE" },
    .{ .value = DEG, .label = "DEG", .short_label = "DEG" },
    .{ .value = PIPE, .label = "PIPE", .short_label = "PIPE" },
    .{ .value = SCLN, .label = "SCLN", .short_label = "SCLN" },
    .{ .value = COLN, .label = "COLN", .short_label = "COLN" },
    .{ .value = UNDS, .label = "UNDS", .short_label = "UNDS" },
    .{ .value = LTEQ, .label = "LTEQ", .short_label = "LTEQ" },
    .{ .value = LDAQ, .label = "LDAQ", .short_label = "LDAQ" },
    .{ .value = LDQU, .label = "LDQU", .short_label = "LDQU" },
    .{ .value = LSQU, .label = "LSQU", .short_label = "LSQU" },
    .{ .value = YEN, .label = "YEN", .short_label = "YEN" },
    .{ .value = TILD, .label = "TILD", .short_label = "TILD" },
    .{ .value = LSAQ, .label = "LSAQ", .short_label = "LSAQ" },
    .{ .value = DIV, .label = "DIV", .short_label = "DIV" },
    .{ .value = ACUT, .label = "ACUT", .short_label = "ACUT" },
    .{ .value = DGRV, .label = "DGRV", .short_label = "DGRV" },
    .{ .value = NEQL, .label = "NEQL", .short_label = "NEQL" },
    .{ .value = IEXL, .label = "IEXL", .short_label = "IEXL" },
    .{ .value = DCIR, .label = "DCIR", .short_label = "DCIR" },
    .{ .value = DLQU, .label = "DLQU", .short_label = "DLQU" },
    .{ .value = OMEG, .label = "OMEG", .short_label = "OMEG" },
    .{ .value = EURO, .label = "EURO", .short_label = "EURO" },
    .{ .value = REGD, .label = "REGD", .short_label = "REGD" },
    .{ .value = TM, .label = "TM", .short_label = "TM" },
    .{ .value = AE, .label = "AE", .short_label = "AE" },
    .{ .value = DIAE, .label = "DIAE", .short_label = "DIAE" },
    .{ .value = OE, .label = "OE", .short_label = "OE" },
    .{ .value = OSTR, .label = "OSTR", .short_label = "OSTR" },
    .{ .value = PI, .label = "PI", .short_label = "PI" },
    .{ .value = LBRC, .label = "LBRC", .short_label = "LBRC" },
    .{ .value = RBRC, .label = "RBRC", .short_label = "RBRC" },
    .{ .value = ARNG, .label = "ARNG", .short_label = "ARNG" },
    .{ .value = SS, .label = "SS", .short_label = "SS" },
    .{ .value = PDIF, .label = "PDIF", .short_label = "PDIF" },
    .{ .value = FHK, .label = "FHK", .short_label = "FHK" },
    .{ .value = INFN, .label = "INFN", .short_label = "INFN" },
    .{ .value = INCR, .label = "INCR", .short_label = "INCR" },
    .{ .value = FORD, .label = "FORD", .short_label = "FORD" },
    .{ .value = MORD, .label = "MORD", .short_label = "MORD" },
    .{ .value = NOT, .label = "NOT", .short_label = "NOT" },
    .{ .value = AT, .label = "AT", .short_label = "AT" },
    .{ .value = HASH, .label = "HASH", .short_label = "HASH" },
    .{ .value = PILC, .label = "PILC", .short_label = "PILC" },
    .{ .value = GRV, .label = "GRV", .short_label = "GRV" },
    .{ .value = NARS, .label = "NARS", .short_label = "NARS" },
    .{ .value = DAGG, .label = "DAGG", .short_label = "DAGG" },
    .{ .value = COPY, .label = "COPY", .short_label = "COPY" },
    .{ .value = SQRT, .label = "SQRT", .short_label = "SQRT" },
    .{ .value = INTG, .label = "INTG", .short_label = "INTG" },
    .{ .value = STIL, .label = "STIL", .short_label = "STIL" },
    .{ .value = MICR, .label = "MICR", .short_label = "MICR" },
    .{ .value = ELLP, .label = "ELLP", .short_label = "ELLP" },
    .{ .value = BULT, .label = "BULT", .short_label = "BULT" },
    .{ .value = NDSH, .label = "NDSH", .short_label = "NDSH" },
    .{ .value = GTEQ, .label = "GTEQ", .short_label = "GTEQ" },
    .{ .value = RDAQ, .label = "RDAQ", .short_label = "RDAQ" },
    .{ .value = RDQU, .label = "RDQU", .short_label = "RDQU" },
    .{ .value = RSQU, .label = "RSQU", .short_label = "RSQU" },
    .{ .value = CENT, .label = "CENT", .short_label = "CENT" },
    .{ .value = PERM, .label = "PERM", .short_label = "PERM" },
    .{ .value = RSAQ, .label = "RSAQ", .short_label = "RSAQ" },
    .{ .value = FRSL, .label = "FRSL", .short_label = "FRSL" },
    .{ .value = APPL, .label = "APPL", .short_label = "APPL" },
    .{ .value = AEQL, .label = "AEQL", .short_label = "AEQL" },
    .{ .value = IQUE, .label = "IQUE", .short_label = "IQUE" },
    .{ .value = PLMN, .label = "PLMN", .short_label = "PLMN" },
    .{ .value = SLQU, .label = "SLQU", .short_label = "SLQU" },
    .{ .value = CAGR, .label = "CAGR", .short_label = "CAGR" },
    .{ .value = CEGR, .label = "CEGR", .short_label = "CEGR" },
    .{ .value = CIGR, .label = "CIGR", .short_label = "CIGR" },
    .{ .value = COGR, .label = "COGR", .short_label = "COGR" },
    .{ .value = CUGR, .label = "CUGR", .short_label = "CUGR" },
    .{ .value = NARP, .label = "NARP", .short_label = "NARP" },
    .{ .value = LCBR, .label = "LCBR", .short_label = "LCBR" },
    .{ .value = RCBR, .label = "RCBR", .short_label = "RCBR" },
    .{ .value = LOZN, .label = "LOZN", .short_label = "LOZN" },
    .{ .value = MACR, .label = "MACR", .short_label = "MACR" },
    .{ .value = BREV, .label = "BREV", .short_label = "BREV" },
    .{ .value = DOTA, .label = "DOTA", .short_label = "DOTA" },
    .{ .value = RGNA, .label = "RGNA", .short_label = "RGNA" },
    .{ .value = CEDL, .label = "CEDL", .short_label = "CEDL" },
    .{ .value = DACU, .label = "DACU", .short_label = "DACU" },
    .{ .value = OGON, .label = "OGON", .short_label = "OGON" },
    .{ .value = CARN, .label = "CARN", .short_label = "CARN" },
    .{ .value = CCCE, .label = "CCCE", .short_label = "CCCE" },
    .{ .value = DDAG, .label = "DDAG", .short_label = "DDAG" },
    .{ .value = CAAC, .label = "CAAC", .short_label = "CAAC" },
    .{ .value = CEAC, .label = "CEAC", .short_label = "CEAC" },
    .{ .value = CIAC, .label = "CIAC", .short_label = "CIAC" },
    .{ .value = COAC, .label = "COAC", .short_label = "COAC" },
    .{ .value = CUAC, .label = "CUAC", .short_label = "CUAC" },
    .{ .value = MDDT, .label = "MDDT", .short_label = "MDDT" },
    .{ .value = MDSH, .label = "MDSH", .short_label = "MDSH" },
};

pub fn getLabel(keycode: core.KeyCodeFire, shortest: bool) ?[]const u8 {
    return zkc_core.getLabel(&_labels, keycode, shortest);
}
