// Copyright 2026 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by zkeycodes from QMK hjson keycode files
const zkc_core = @import("../src/core.zig");
const core = @import("zigmkay").core;
const L_SFT = zkc_core.L_SFT;
const L_ALT = zkc_core.L_ALT;
const R_ALT = zkc_core.R_ALT;
const R_CTL = zkc_core.R_CTL;
const DEAD = zkc_core.DEAD;
pub const keycodes = @import("keycodes.zig");

pub const QMK_KOREAN_KEYCODES_VERSION = "0.0.1";
pub const QMK_KOREAN_KEYCODES_VERSION_BCD = @as(c_int, 0x00000001);
pub const QMK_KOREAN_KEYCODES_VERSION_MAJOR = @as(c_int, 0);
pub const QMK_KOREAN_KEYCODES_VERSION_MINOR = @as(c_int, 0);
pub const QMK_KOREAN_KEYCODES_VERSION_PATCH = @as(c_int, 1);

//
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ` │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ - │ = │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │ [ │ ] │  ₩  │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
// │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ ; │ ' │        │
// ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
// │        │ Z │ X │ C │ V │ B │ N │ M │ , │ . │ / │          │
// ├─────┬──┴┬──┴──┬┴──┬┴───┴───┴───┴──┬┴──┬┴───┴┬──┴┬───┬─────┤
// │     │   │     │Hnj│               │H↔Y│     │   │   │     │
// └─────┴───┴─────┴───┴───────────────┴───┴─────┴───┴───┴─────┘
//
/// `
pub const GRV = keycodes.kcf.GRV;
/// 1
pub const N1 = keycodes.kcf.N1;
/// 2
pub const N2 = keycodes.kcf.N2;
/// 3
pub const N3 = keycodes.kcf.N3;
/// 4
pub const N4 = keycodes.kcf.N4;
/// 5
pub const N5 = keycodes.kcf.N5;
/// 6
pub const N6 = keycodes.kcf.N6;
/// 7
pub const N7 = keycodes.kcf.N7;
/// 8
pub const N8 = keycodes.kcf.N8;
/// 9
pub const N9 = keycodes.kcf.N9;
/// 0
pub const N0 = keycodes.kcf.N0;
/// -
pub const MINS = keycodes.kcf.MINS;
/// =
pub const EQL = keycodes.kcf.EQL;
/// Q
pub const Q = keycodes.kcf.Q;
/// W
pub const W = keycodes.kcf.W;
/// E
pub const E = keycodes.kcf.E;
/// R
pub const R = keycodes.kcf.R;
/// T
pub const T = keycodes.kcf.T;
/// Y
pub const Y = keycodes.kcf.Y;
/// U
pub const U = keycodes.kcf.U;
/// I
pub const I = keycodes.kcf.I;
/// O
pub const O = keycodes.kcf.O;
/// P
pub const P = keycodes.kcf.P;
/// [
pub const LBRC = keycodes.kcf.LBRC;
/// ]
pub const RBRC = keycodes.kcf.RBRC;
/// ₩
pub const WON = keycodes.kcf.BSLS;
/// A
pub const A = keycodes.kcf.A;
/// S
pub const S = keycodes.kcf.S;
/// D
pub const D = keycodes.kcf.D;
/// F
pub const F = keycodes.kcf.F;
/// G
pub const G = keycodes.kcf.G;
/// H
pub const H = keycodes.kcf.H;
/// J
pub const J = keycodes.kcf.J;
/// K
pub const K = keycodes.kcf.K;
/// L
pub const L = keycodes.kcf.L;
/// ;
pub const SCLN = keycodes.kcf.SCLN;
/// '
pub const QUOT = keycodes.kcf.QUOT;
/// Z
pub const Z = keycodes.kcf.Z;
/// X
pub const X = keycodes.kcf.X;
/// C
pub const C = keycodes.kcf.C;
/// V
pub const V = keycodes.kcf.V;
/// B
pub const B = keycodes.kcf.B;
/// N
pub const N = keycodes.kcf.N;
/// M
pub const M = keycodes.kcf.M;
/// ,
pub const COMM = keycodes.kcf.COMM;
/// .
pub const DOT = keycodes.kcf.DOT;
/// /
pub const SLSH = keycodes.kcf.SLSH;
/// Hanja (한자)
pub const HANJ = keycodes.kcf.LNG2;
/// Han ↔ Yeong (한 ↔ 영)
pub const HAEN = keycodes.kcf.LNG1;
// Shifted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ~ │ ! │ @ │ # │ $ │ % │ ^ │ & │ * │ ( │ ) │ _ │ + │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │   │   │   │   │   │   │   │   │ { │ } │  |  │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
// │      │   │   │   │   │   │   │   │   │   │ : │ " │        │
// ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
// │        │   │   │   │   │   │   │   │ < │ > │ ? │          │
// ├─────┬──┴┬──┴──┬┴──┬┴───┴───┴───┴──┬┴──┬┴───┴┬──┴┬───┬─────┤
// │     │   │     │   │               │   │     │   │   │     │
// └─────┴───┴─────┴───┴───────────────┴───┴─────┴───┴───┴─────┘
//
/// ~
pub const TILD = L_SFT(GRV);
/// !
pub const EXLM = L_SFT(N1);
/// @
pub const AT = L_SFT(N2);
/// #
pub const HASH = L_SFT(N3);
/// $
pub const DLR = L_SFT(N4);
/// %
pub const PERC = L_SFT(N5);
/// ^
pub const CIRC = L_SFT(N6);
/// &
pub const AMPR = L_SFT(N7);
/// *
pub const ASTR = L_SFT(N8);
/// (
pub const LPRN = L_SFT(N9);
/// )
pub const RPRN = L_SFT(N0);
/// _
pub const UNDS = L_SFT(MINS);
/// +
pub const PLUS = L_SFT(EQL);
/// {
pub const LCBR = L_SFT(LBRC);
/// }
pub const RCBR = L_SFT(RBRC);
/// |
pub const PIPE = L_SFT(WON);
/// :
pub const COLN = L_SFT(SCLN);
/// "
pub const DQUO = L_SFT(QUOT);
/// <
pub const LABK = L_SFT(COMM);
/// >
pub const RABK = L_SFT(DOT);
/// ?
pub const QUES = L_SFT(SLSH);

// Label lookup table
pub const _labels = [_]zkc_core.LabelEntry{
    .{ .value = GRV, .label = "GRV", .short_label = "GRV" },
    .{ .value = N1, .label = "1", .short_label = "1" },
    .{ .value = N2, .label = "2", .short_label = "2" },
    .{ .value = N3, .label = "3", .short_label = "3" },
    .{ .value = N4, .label = "4", .short_label = "4" },
    .{ .value = N5, .label = "5", .short_label = "5" },
    .{ .value = N6, .label = "6", .short_label = "6" },
    .{ .value = N7, .label = "7", .short_label = "7" },
    .{ .value = N8, .label = "8", .short_label = "8" },
    .{ .value = N9, .label = "9", .short_label = "9" },
    .{ .value = N0, .label = "0", .short_label = "0" },
    .{ .value = MINS, .label = "MINS", .short_label = "MINS" },
    .{ .value = EQL, .label = "EQL", .short_label = "EQL" },
    .{ .value = Q, .label = "Q", .short_label = "Q" },
    .{ .value = W, .label = "W", .short_label = "W" },
    .{ .value = E, .label = "E", .short_label = "E" },
    .{ .value = R, .label = "R", .short_label = "R" },
    .{ .value = T, .label = "T", .short_label = "T" },
    .{ .value = Y, .label = "Y", .short_label = "Y" },
    .{ .value = U, .label = "U", .short_label = "U" },
    .{ .value = I, .label = "I", .short_label = "I" },
    .{ .value = O, .label = "O", .short_label = "O" },
    .{ .value = P, .label = "P", .short_label = "P" },
    .{ .value = LBRC, .label = "LBRC", .short_label = "LBRC" },
    .{ .value = RBRC, .label = "RBRC", .short_label = "RBRC" },
    .{ .value = WON, .label = "WON", .short_label = "WON" },
    .{ .value = A, .label = "A", .short_label = "A" },
    .{ .value = S, .label = "S", .short_label = "S" },
    .{ .value = D, .label = "D", .short_label = "D" },
    .{ .value = F, .label = "F", .short_label = "F" },
    .{ .value = G, .label = "G", .short_label = "G" },
    .{ .value = H, .label = "H", .short_label = "H" },
    .{ .value = J, .label = "J", .short_label = "J" },
    .{ .value = K, .label = "K", .short_label = "K" },
    .{ .value = L, .label = "L", .short_label = "L" },
    .{ .value = SCLN, .label = "SCLN", .short_label = "SCLN" },
    .{ .value = QUOT, .label = "QUOT", .short_label = "QUOT" },
    .{ .value = Z, .label = "Z", .short_label = "Z" },
    .{ .value = X, .label = "X", .short_label = "X" },
    .{ .value = C, .label = "C", .short_label = "C" },
    .{ .value = V, .label = "V", .short_label = "V" },
    .{ .value = B, .label = "B", .short_label = "B" },
    .{ .value = N, .label = "N", .short_label = "N" },
    .{ .value = M, .label = "M", .short_label = "M" },
    .{ .value = COMM, .label = "COMM", .short_label = "COMM" },
    .{ .value = DOT, .label = "DOT", .short_label = "DOT" },
    .{ .value = SLSH, .label = "SLSH", .short_label = "SLSH" },
    .{ .value = HANJ, .label = "HANJ", .short_label = "HANJ" },
    .{ .value = HAEN, .label = "HAEN", .short_label = "HAEN" },
    .{ .value = TILD, .label = "TILD", .short_label = "TILD" },
    .{ .value = EXLM, .label = "EXLM", .short_label = "EXLM" },
    .{ .value = AT, .label = "AT", .short_label = "AT" },
    .{ .value = HASH, .label = "HASH", .short_label = "HASH" },
    .{ .value = DLR, .label = "DLR", .short_label = "DLR" },
    .{ .value = PERC, .label = "PERC", .short_label = "PERC" },
    .{ .value = CIRC, .label = "CIRC", .short_label = "CIRC" },
    .{ .value = AMPR, .label = "AMPR", .short_label = "AMPR" },
    .{ .value = ASTR, .label = "ASTR", .short_label = "ASTR" },
    .{ .value = LPRN, .label = "LPRN", .short_label = "LPRN" },
    .{ .value = RPRN, .label = "RPRN", .short_label = "RPRN" },
    .{ .value = UNDS, .label = "UNDS", .short_label = "UNDS" },
    .{ .value = PLUS, .label = "PLUS", .short_label = "PLUS" },
    .{ .value = LCBR, .label = "LCBR", .short_label = "LCBR" },
    .{ .value = RCBR, .label = "RCBR", .short_label = "RCBR" },
    .{ .value = PIPE, .label = "PIPE", .short_label = "PIPE" },
    .{ .value = COLN, .label = "COLN", .short_label = "COLN" },
    .{ .value = DQUO, .label = "DQUO", .short_label = "DQUO" },
    .{ .value = LABK, .label = "LABK", .short_label = "LABK" },
    .{ .value = RABK, .label = "RABK", .short_label = "RABK" },
    .{ .value = QUES, .label = "QUES", .short_label = "QUES" },
};

pub fn getLabel(keycode: core.KeyCodeFire, shortest: bool) ?[]const u8 {
    return zkc_core.getLabel(&_labels, keycode, shortest);
}
