// Copyright 2026 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by zkeycodes from QMK hjson keycode files
const zkc_core = @import("../src/core.zig");
const core = @import("zigmkay").core;
const L_SFT = zkc_core.L_SFT;
const L_ALT = zkc_core.L_ALT;
const R_ALT = zkc_core.R_ALT;
const R_CTL = zkc_core.R_CTL;
const DEAD = zkc_core.DEAD;
pub const keycodes = @import("keycodes.zig");

pub const QMK_LITHUANIAN_AZERTY_KEYCODES_VERSION = "0.0.1";
pub const QMK_LITHUANIAN_AZERTY_KEYCODES_VERSION_BCD = @as(c_int, 0x00000001);
pub const QMK_LITHUANIAN_AZERTY_KEYCODES_VERSION_MAJOR = @as(c_int, 0);
pub const QMK_LITHUANIAN_AZERTY_KEYCODES_VERSION_MINOR = @as(c_int, 0);
pub const QMK_LITHUANIAN_AZERTY_KEYCODES_VERSION_PATCH = @as(c_int, 1);

//
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ` │ ! │ - │ / │ ; │ : │ , │ . │ = │ ( │ ) │ ? │ X │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ Ą │ Ž │ E │ R │ T │ Y │ U │ I │ O │ P │ Į │ W │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │ A │ S │ D │ Š │ G │ H │ J │ K │ L │ Ų │ Ė │ Q │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ < │ Z │ Ū │ C │ V │ B │ N │ M │ Č │ F │ Ę │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// `
pub const GRV = keycodes.kcf.GRV;
/// !
pub const EXLM = keycodes.kcf.N1;
/// -
pub const MINS = keycodes.kcf.N2;
/// /
pub const SLSH = keycodes.kcf.N3;
/// ;
pub const SCLN = keycodes.kcf.N4;
/// :
pub const COLN = keycodes.kcf.N5;
/// ,
pub const COMM = keycodes.kcf.N6;
/// .
pub const DOT = keycodes.kcf.N7;
/// =
pub const EQL = keycodes.kcf.N8;
/// (
pub const LPRN = keycodes.kcf.N9;
/// )
pub const RPRN = keycodes.kcf.N0;
/// ?
pub const QUES = keycodes.kcf.MINS;
/// X
pub const X = keycodes.kcf.EQL;
/// Ą
pub const AOGO = keycodes.kcf.Q;
/// Ž
pub const ZCAR = keycodes.kcf.W;
/// E
pub const E = keycodes.kcf.E;
/// R
pub const R = keycodes.kcf.R;
/// T
pub const T = keycodes.kcf.T;
/// Y
pub const Y = keycodes.kcf.Y;
/// U
pub const U = keycodes.kcf.U;
/// I
pub const I = keycodes.kcf.I;
/// O
pub const O = keycodes.kcf.O;
/// P
pub const P = keycodes.kcf.P;
/// Į
pub const IOGO = keycodes.kcf.LBRC;
/// W
pub const W = keycodes.kcf.RBRC;
/// A
pub const A = keycodes.kcf.A;
/// S
pub const S = keycodes.kcf.S;
/// D
pub const D = keycodes.kcf.D;
/// Š
pub const SCAR = keycodes.kcf.F;
/// G
pub const G = keycodes.kcf.G;
/// H
pub const H = keycodes.kcf.H;
/// J
pub const J = keycodes.kcf.J;
/// K
pub const K = keycodes.kcf.K;
/// L
pub const L = keycodes.kcf.L;
/// Ų
pub const UOGO = keycodes.kcf.SCLN;
/// Ė
pub const EDOT = keycodes.kcf.QUOT;
/// Q
pub const Q = keycodes.kcf.NUHS;
/// <
pub const LABK = keycodes.kcf.NUBS;
/// Z
pub const Z = keycodes.kcf.Z;
/// Ū
pub const UMAC = keycodes.kcf.X;
/// C
pub const C = keycodes.kcf.C;
/// V
pub const V = keycodes.kcf.V;
/// B
pub const B = keycodes.kcf.B;
/// N
pub const N = keycodes.kcf.N;
/// M
pub const M = keycodes.kcf.M;
/// Č
pub const CCAR = keycodes.kcf.COMM;
/// F
pub const F = keycodes.kcf.DOT;
/// Ę
pub const EOGO = keycodes.kcf.SLSH;
// Shifted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ~ │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ + │   │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │   │   │   │   │   │   │   │   │   │   │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │   │   │   │   │   │   │   │   │   │   │   │   │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ > │   │   │   │   │   │   │   │   │   │   │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ~
pub const TILD = L_SFT(GRV);
/// 1
pub const N1 = L_SFT(EXLM);
/// 2
pub const N2 = L_SFT(MINS);
/// 3
pub const N3 = L_SFT(SLSH);
/// 4
pub const N4 = L_SFT(SCLN);
/// 5
pub const N5 = L_SFT(COLN);
/// 6
pub const N6 = L_SFT(COMM);
/// 7
pub const N7 = L_SFT(DOT);
/// 8
pub const N8 = L_SFT(EQL);
/// 9
pub const N9 = L_SFT(LPRN);
/// 0
pub const N0 = L_SFT(RPRN);
/// +
pub const PLUS = L_SFT(QUES);
/// >
pub const RABK = L_SFT(LABK);
// AltGr symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ´ │ @ │ _ │ # │ $ │ § │ ^ │ & │ * │ [ │ ] │ ' │ % │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │ € │   │   │   │   │   │   │   │ { │ } │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │   │   │   │   │   │   │   │   │   │   │ " │ | │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ – │   │   │   │   │   │   │   │ „ │ “ │ \ │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ´
pub const ACUT = R_ALT(GRV);
/// @
pub const AT = R_ALT(EXLM);
/// _
pub const UNDS = R_ALT(MINS);
/// #
pub const HASH = R_ALT(SLSH);
/// $
pub const DLR = R_ALT(SCLN);
/// §
pub const SECT = R_ALT(COLN);
/// ^
pub const CIRC = R_ALT(COMM);
/// &
pub const AMPR = R_ALT(DOT);
/// *
pub const ASTR = R_ALT(EQL);
/// [
pub const LBRC = R_ALT(LPRN);
/// ]
pub const RBRC = R_ALT(RPRN);
/// '
pub const QUOT = R_ALT(QUES);
/// %
pub const PERC = R_ALT(X);
/// €
pub const EURO = R_ALT(E);
/// {
pub const LCBR = R_ALT(IOGO);
/// }
pub const RCBR = R_ALT(W);
/// "
pub const DQUO = R_ALT(EDOT);
/// |
pub const PIPE = R_ALT(Q);
/// –
pub const NDSH = R_ALT(LABK);
/// „
pub const DLQU = R_ALT(CCAR);
/// “
pub const LDQU = R_ALT(F);
/// (backslash)
pub const BSLS = R_ALT(EOGO);

// Label lookup table
pub const _labels = [_]zkc_core.LabelEntry{
    .{ .value = GRV, .label = "GRV", .short_label = "GRV" },
    .{ .value = EXLM, .label = "EXLM", .short_label = "EXLM" },
    .{ .value = MINS, .label = "MINS", .short_label = "MINS" },
    .{ .value = SLSH, .label = "SLSH", .short_label = "SLSH" },
    .{ .value = SCLN, .label = "SCLN", .short_label = "SCLN" },
    .{ .value = COLN, .label = "COLN", .short_label = "COLN" },
    .{ .value = COMM, .label = "COMM", .short_label = "COMM" },
    .{ .value = DOT, .label = "DOT", .short_label = "DOT" },
    .{ .value = EQL, .label = "EQL", .short_label = "EQL" },
    .{ .value = LPRN, .label = "LPRN", .short_label = "LPRN" },
    .{ .value = RPRN, .label = "RPRN", .short_label = "RPRN" },
    .{ .value = QUES, .label = "QUES", .short_label = "QUES" },
    .{ .value = X, .label = "X", .short_label = "X" },
    .{ .value = AOGO, .label = "AOGO", .short_label = "AOGO" },
    .{ .value = ZCAR, .label = "ZCAR", .short_label = "ZCAR" },
    .{ .value = E, .label = "E", .short_label = "E" },
    .{ .value = R, .label = "R", .short_label = "R" },
    .{ .value = T, .label = "T", .short_label = "T" },
    .{ .value = Y, .label = "Y", .short_label = "Y" },
    .{ .value = U, .label = "U", .short_label = "U" },
    .{ .value = I, .label = "I", .short_label = "I" },
    .{ .value = O, .label = "O", .short_label = "O" },
    .{ .value = P, .label = "P", .short_label = "P" },
    .{ .value = IOGO, .label = "IOGO", .short_label = "IOGO" },
    .{ .value = W, .label = "W", .short_label = "W" },
    .{ .value = A, .label = "A", .short_label = "A" },
    .{ .value = S, .label = "S", .short_label = "S" },
    .{ .value = D, .label = "D", .short_label = "D" },
    .{ .value = SCAR, .label = "SCAR", .short_label = "SCAR" },
    .{ .value = G, .label = "G", .short_label = "G" },
    .{ .value = H, .label = "H", .short_label = "H" },
    .{ .value = J, .label = "J", .short_label = "J" },
    .{ .value = K, .label = "K", .short_label = "K" },
    .{ .value = L, .label = "L", .short_label = "L" },
    .{ .value = UOGO, .label = "UOGO", .short_label = "UOGO" },
    .{ .value = EDOT, .label = "EDOT", .short_label = "EDOT" },
    .{ .value = Q, .label = "Q", .short_label = "Q" },
    .{ .value = LABK, .label = "LABK", .short_label = "LABK" },
    .{ .value = Z, .label = "Z", .short_label = "Z" },
    .{ .value = UMAC, .label = "UMAC", .short_label = "UMAC" },
    .{ .value = C, .label = "C", .short_label = "C" },
    .{ .value = V, .label = "V", .short_label = "V" },
    .{ .value = B, .label = "B", .short_label = "B" },
    .{ .value = N, .label = "N", .short_label = "N" },
    .{ .value = M, .label = "M", .short_label = "M" },
    .{ .value = CCAR, .label = "CCAR", .short_label = "CCAR" },
    .{ .value = F, .label = "F", .short_label = "F" },
    .{ .value = EOGO, .label = "EOGO", .short_label = "EOGO" },
    .{ .value = TILD, .label = "TILD", .short_label = "TILD" },
    .{ .value = N1, .label = "1", .short_label = "1" },
    .{ .value = N2, .label = "2", .short_label = "2" },
    .{ .value = N3, .label = "3", .short_label = "3" },
    .{ .value = N4, .label = "4", .short_label = "4" },
    .{ .value = N5, .label = "5", .short_label = "5" },
    .{ .value = N6, .label = "6", .short_label = "6" },
    .{ .value = N7, .label = "7", .short_label = "7" },
    .{ .value = N8, .label = "8", .short_label = "8" },
    .{ .value = N9, .label = "9", .short_label = "9" },
    .{ .value = N0, .label = "0", .short_label = "0" },
    .{ .value = PLUS, .label = "PLUS", .short_label = "PLUS" },
    .{ .value = RABK, .label = "RABK", .short_label = "RABK" },
    .{ .value = ACUT, .label = "ACUT", .short_label = "ACUT" },
    .{ .value = AT, .label = "AT", .short_label = "AT" },
    .{ .value = UNDS, .label = "UNDS", .short_label = "UNDS" },
    .{ .value = HASH, .label = "HASH", .short_label = "HASH" },
    .{ .value = DLR, .label = "DLR", .short_label = "DLR" },
    .{ .value = SECT, .label = "SECT", .short_label = "SECT" },
    .{ .value = CIRC, .label = "CIRC", .short_label = "CIRC" },
    .{ .value = AMPR, .label = "AMPR", .short_label = "AMPR" },
    .{ .value = ASTR, .label = "ASTR", .short_label = "ASTR" },
    .{ .value = LBRC, .label = "LBRC", .short_label = "LBRC" },
    .{ .value = RBRC, .label = "RBRC", .short_label = "RBRC" },
    .{ .value = QUOT, .label = "QUOT", .short_label = "QUOT" },
    .{ .value = PERC, .label = "PERC", .short_label = "PERC" },
    .{ .value = EURO, .label = "EURO", .short_label = "EURO" },
    .{ .value = LCBR, .label = "LCBR", .short_label = "LCBR" },
    .{ .value = RCBR, .label = "RCBR", .short_label = "RCBR" },
    .{ .value = DQUO, .label = "DQUO", .short_label = "DQUO" },
    .{ .value = PIPE, .label = "PIPE", .short_label = "PIPE" },
    .{ .value = NDSH, .label = "NDSH", .short_label = "NDSH" },
    .{ .value = DLQU, .label = "DLQU", .short_label = "DLQU" },
    .{ .value = LDQU, .label = "LDQU", .short_label = "LDQU" },
    .{ .value = BSLS, .label = "BSLS", .short_label = "BSLS" },
};

pub fn getLabel(keycode: core.KeyCodeFire, shortest: bool) ?[]const u8 {
    return zkc_core.getLabel(&_labels, keycode, shortest);
}
