// Copyright 2026 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by zkeycodes from QMK hjson keycode files
const zkc_core = @import("../src/core.zig");
const core = @import("zigmkay").core;
const L_SFT = zkc_core.L_SFT;
const L_ALT = zkc_core.L_ALT;
const R_ALT = zkc_core.R_ALT;
const R_CTL = zkc_core.R_CTL;
const DEAD = zkc_core.DEAD;
pub const keycodes = @import("keycodes.zig");

pub const QMK_NEO2_KEYCODES_VERSION = "0.0.1";
pub const QMK_NEO2_KEYCODES_VERSION_BCD = @as(c_int, 0x00000001);
pub const QMK_NEO2_KEYCODES_VERSION_MAJOR = @as(c_int, 0);
pub const QMK_NEO2_KEYCODES_VERSION_MINOR = @as(c_int, 0);
pub const QMK_NEO2_KEYCODES_VERSION_PATCH = @as(c_int, 1);

//
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ^ │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ - │ ` │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ X │ V │ L │ C │ W │ K │ H │ G │ F │ Q │ ß │ ´ │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │  L3  │ U │ I │ A │ E │ O │ S │ N │ R │ T │ D │ Y │ L3│    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │L4 │ Ü │ Ö │ Ä │ P │ Z │ B │ M │ , │ . │ J │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │ L4 │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ^ (dead)
pub const CIRC = DEAD(keycodes.kcf.GRV);
/// 1
pub const N1 = keycodes.kcf.N1;
/// 2
pub const N2 = keycodes.kcf.N2;
/// 3
pub const N3 = keycodes.kcf.N3;
/// 4
pub const N4 = keycodes.kcf.N4;
/// 5
pub const N5 = keycodes.kcf.N5;
/// 6
pub const N6 = keycodes.kcf.N6;
/// 7
pub const N7 = keycodes.kcf.N7;
/// 8
pub const N8 = keycodes.kcf.N8;
/// 9
pub const N9 = keycodes.kcf.N9;
/// 0
pub const N0 = keycodes.kcf.N0;
/// -
pub const MINS = keycodes.kcf.MINS;
/// ` (dead)
pub const GRV = DEAD(keycodes.kcf.EQL);
/// X
pub const X = keycodes.kcf.Q;
/// V
pub const V = keycodes.kcf.W;
/// L
pub const L = keycodes.kcf.E;
/// C
pub const C = keycodes.kcf.R;
/// W
pub const W = keycodes.kcf.T;
/// K
pub const K = keycodes.kcf.Y;
/// H
pub const H = keycodes.kcf.U;
/// G
pub const G = keycodes.kcf.I;
/// F
pub const F = keycodes.kcf.O;
/// Q
pub const Q = keycodes.kcf.P;
/// ß
pub const SS = keycodes.kcf.LBRC;
/// ´ (dead)
pub const ACUT = DEAD(keycodes.kcf.RBRC);
/// (layer 3)
pub const L3L = keycodes.kcf.CAPS;
/// U
pub const U = keycodes.kcf.A;
/// I
pub const I = keycodes.kcf.S;
/// A
pub const A = keycodes.kcf.D;
/// E
pub const E = keycodes.kcf.F;
/// O
pub const O = keycodes.kcf.G;
/// S
pub const S = keycodes.kcf.H;
/// N
pub const N = keycodes.kcf.J;
/// R
pub const R = keycodes.kcf.K;
/// T
pub const T = keycodes.kcf.L;
/// D
pub const D = keycodes.kcf.SCLN;
/// Y
pub const Y = keycodes.kcf.QUOT;
/// (layer 3)
pub const L3R = keycodes.kcf.NUHS;
/// (layer 4)
pub const L4L = keycodes.kcf.NUBS;
/// Ü
pub const UDIA = keycodes.kcf.Z;
/// Ö
pub const ODIA = keycodes.kcf.X;
/// Ä
pub const ADIA = keycodes.kcf.C;
/// P
pub const P = keycodes.kcf.V;
/// Z
pub const Z = keycodes.kcf.B;
/// B
pub const B = keycodes.kcf.N;
/// M
pub const M = keycodes.kcf.M;
/// ,
pub const COMM = keycodes.kcf.COMM;
/// .
pub const DOT = keycodes.kcf.DOT;
/// J
pub const J = keycodes.kcf.SLSH;
/// (layer 4)
pub const L4R = keycodes.kcf.ALGR;

// Label lookup table
pub const _labels = [_]zkc_core.LabelEntry{
    .{ .value = CIRC, .label = "CIRC", .short_label = "CIRC" },
    .{ .value = N1, .label = "1", .short_label = "1" },
    .{ .value = N2, .label = "2", .short_label = "2" },
    .{ .value = N3, .label = "3", .short_label = "3" },
    .{ .value = N4, .label = "4", .short_label = "4" },
    .{ .value = N5, .label = "5", .short_label = "5" },
    .{ .value = N6, .label = "6", .short_label = "6" },
    .{ .value = N7, .label = "7", .short_label = "7" },
    .{ .value = N8, .label = "8", .short_label = "8" },
    .{ .value = N9, .label = "9", .short_label = "9" },
    .{ .value = N0, .label = "0", .short_label = "0" },
    .{ .value = MINS, .label = "MINS", .short_label = "MINS" },
    .{ .value = GRV, .label = "GRV", .short_label = "GRV" },
    .{ .value = X, .label = "X", .short_label = "X" },
    .{ .value = V, .label = "V", .short_label = "V" },
    .{ .value = L, .label = "L", .short_label = "L" },
    .{ .value = C, .label = "C", .short_label = "C" },
    .{ .value = W, .label = "W", .short_label = "W" },
    .{ .value = K, .label = "K", .short_label = "K" },
    .{ .value = H, .label = "H", .short_label = "H" },
    .{ .value = G, .label = "G", .short_label = "G" },
    .{ .value = F, .label = "F", .short_label = "F" },
    .{ .value = Q, .label = "Q", .short_label = "Q" },
    .{ .value = SS, .label = "SS", .short_label = "SS" },
    .{ .value = ACUT, .label = "ACUT", .short_label = "ACUT" },
    .{ .value = L3L, .label = "L3L", .short_label = "L3L" },
    .{ .value = U, .label = "U", .short_label = "U" },
    .{ .value = I, .label = "I", .short_label = "I" },
    .{ .value = A, .label = "A", .short_label = "A" },
    .{ .value = E, .label = "E", .short_label = "E" },
    .{ .value = O, .label = "O", .short_label = "O" },
    .{ .value = S, .label = "S", .short_label = "S" },
    .{ .value = N, .label = "N", .short_label = "N" },
    .{ .value = R, .label = "R", .short_label = "R" },
    .{ .value = T, .label = "T", .short_label = "T" },
    .{ .value = D, .label = "D", .short_label = "D" },
    .{ .value = Y, .label = "Y", .short_label = "Y" },
    .{ .value = L3R, .label = "L3R", .short_label = "L3R" },
    .{ .value = L4L, .label = "L4L", .short_label = "L4L" },
    .{ .value = UDIA, .label = "UDIA", .short_label = "UDIA" },
    .{ .value = ODIA, .label = "ODIA", .short_label = "ODIA" },
    .{ .value = ADIA, .label = "ADIA", .short_label = "ADIA" },
    .{ .value = P, .label = "P", .short_label = "P" },
    .{ .value = Z, .label = "Z", .short_label = "Z" },
    .{ .value = B, .label = "B", .short_label = "B" },
    .{ .value = M, .label = "M", .short_label = "M" },
    .{ .value = COMM, .label = "COMM", .short_label = "COMM" },
    .{ .value = DOT, .label = "DOT", .short_label = "DOT" },
    .{ .value = J, .label = "J", .short_label = "J" },
    .{ .value = L4R, .label = "L4R", .short_label = "L4R" },
};

pub fn getLabel(keycode: core.KeyCodeFire, shortest: bool) ?[]const u8 {
    return zkc_core.getLabel(&_labels, keycode, shortest);
}
