// Copyright 2026 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by zkeycodes from QMK hjson keycode files
const zkc_core = @import("../src/core.zig");
const core = @import("zigmkay").core;
const L_SFT = zkc_core.L_SFT;
const L_ALT = zkc_core.L_ALT;
const R_ALT = zkc_core.R_ALT;
const R_CTL = zkc_core.R_CTL;
const DEAD = zkc_core.DEAD;
pub const keycodes = @import("keycodes.zig");

pub const QMK_NORDIC_KEYCODES_VERSION = "0.0.1";
pub const QMK_NORDIC_KEYCODES_VERSION_BCD = @as(c_int, 0x00000001);
pub const QMK_NORDIC_KEYCODES_VERSION_MAJOR = @as(c_int, 0);
pub const QMK_NORDIC_KEYCODES_VERSION_MINOR = @as(c_int, 0);
pub const QMK_NORDIC_KEYCODES_VERSION_PATCH = @as(c_int, 1);

pub const HALF = keycodes.kcf.GRV;
pub const PLUS = keycodes.kcf.MINS;
pub const ACUT = keycodes.kcf.EQL;
pub const AM = keycodes.kcf.LBRC;
/// this is the "umlaut" char on Nordic keyboards, Apple layout
pub const QUOT = keycodes.kcf.RBRC;
pub const AE = keycodes.kcf.SCLN;
pub const OSLH = keycodes.kcf.QUOT;
pub const APOS = keycodes.kcf.NUHS;
pub const LESS = keycodes.kcf.NUBS;
pub const MINS = keycodes.kcf.SLSH;
pub const SECT = L_SFT(HALF);
pub const QUO2 = L_SFT(keycodes.kcf.N2);
pub const BULT = L_SFT(keycodes.kcf.N4);
pub const AMPR = L_SFT(keycodes.kcf.N6);
pub const SLSH = L_SFT(keycodes.kcf.N7);
pub const LPRN = L_SFT(keycodes.kcf.N8);
pub const RPRN = L_SFT(keycodes.kcf.N9);
pub const EQL = L_SFT(keycodes.kcf.N0);
pub const QUES = L_SFT(PLUS);
pub const GRV = L_SFT(ACUT);
pub const CIRC = L_SFT(QUOT);
pub const GRTR = L_SFT(LESS);
pub const SCLN = L_SFT(keycodes.kcf.COMM);
pub const COLN = L_SFT(keycodes.kcf.DOT);
pub const UNDS = L_SFT(MINS);
pub const AT = R_ALT(keycodes.kcf.N2);
pub const PND = R_ALT(keycodes.kcf.N3);
pub const DLR = R_ALT(keycodes.kcf.N4);
pub const LCBR = R_ALT(keycodes.kcf.N7);
pub const LBRC = R_ALT(keycodes.kcf.N8);
pub const RBRC = R_ALT(keycodes.kcf.N9);
pub const RCBR = R_ALT(keycodes.kcf.N0);
pub const PIPE = R_ALT(keycodes.kcf.NUBS);
pub const EURO = R_ALT(keycodes.kcf.E);
pub const TILD = R_ALT(QUOT);
pub const BSLS = R_ALT(keycodes.kcf.MINS);
pub const MU = R_ALT(keycodes.kcf.M);

// Label lookup table
pub const _labels = [_]zkc_core.LabelEntry{
    .{ .value = HALF, .label = "HALF", .short_label = "HALF" },
    .{ .value = PLUS, .label = "PLUS", .short_label = "PLUS" },
    .{ .value = ACUT, .label = "ACUT", .short_label = "ACUT" },
    .{ .value = AM, .label = "AM", .short_label = "AM" },
    .{ .value = QUOT, .label = "QUOT", .short_label = "QUOT" },
    .{ .value = AE, .label = "AE", .short_label = "AE" },
    .{ .value = OSLH, .label = "OSLH", .short_label = "OSLH" },
    .{ .value = APOS, .label = "APOS", .short_label = "APOS" },
    .{ .value = LESS, .label = "LESS", .short_label = "LESS" },
    .{ .value = MINS, .label = "MINS", .short_label = "MINS" },
    .{ .value = SECT, .label = "SECT", .short_label = "SECT" },
    .{ .value = QUO2, .label = "QUO2", .short_label = "QUO2" },
    .{ .value = BULT, .label = "BULT", .short_label = "BULT" },
    .{ .value = AMPR, .label = "AMPR", .short_label = "AMPR" },
    .{ .value = SLSH, .label = "SLSH", .short_label = "SLSH" },
    .{ .value = LPRN, .label = "LPRN", .short_label = "LPRN" },
    .{ .value = RPRN, .label = "RPRN", .short_label = "RPRN" },
    .{ .value = EQL, .label = "EQL", .short_label = "EQL" },
    .{ .value = QUES, .label = "QUES", .short_label = "QUES" },
    .{ .value = GRV, .label = "GRV", .short_label = "GRV" },
    .{ .value = CIRC, .label = "CIRC", .short_label = "CIRC" },
    .{ .value = GRTR, .label = "GRTR", .short_label = "GRTR" },
    .{ .value = SCLN, .label = "SCLN", .short_label = "SCLN" },
    .{ .value = COLN, .label = "COLN", .short_label = "COLN" },
    .{ .value = UNDS, .label = "UNDS", .short_label = "UNDS" },
    .{ .value = AT, .label = "AT", .short_label = "AT" },
    .{ .value = PND, .label = "PND", .short_label = "PND" },
    .{ .value = DLR, .label = "DLR", .short_label = "DLR" },
    .{ .value = LCBR, .label = "LCBR", .short_label = "LCBR" },
    .{ .value = LBRC, .label = "LBRC", .short_label = "LBRC" },
    .{ .value = RBRC, .label = "RBRC", .short_label = "RBRC" },
    .{ .value = RCBR, .label = "RCBR", .short_label = "RCBR" },
    .{ .value = PIPE, .label = "PIPE", .short_label = "PIPE" },
    .{ .value = EURO, .label = "EURO", .short_label = "EURO" },
    .{ .value = TILD, .label = "TILD", .short_label = "TILD" },
    .{ .value = BSLS, .label = "BSLS", .short_label = "BSLS" },
    .{ .value = MU, .label = "MU", .short_label = "MU" },
};

pub fn getLabel(keycode: core.KeyCodeFire, shortest: bool) ?[]const u8 {
    return zkc_core.getLabel(&_labels, keycode, shortest);
}
