// Copyright 2026 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by zkeycodes from QMK hjson keycode files
const zkc_core = @import("../src/core.zig");
const core = @import("zigmkay").core;
const L_SFT = zkc_core.L_SFT;
const L_ALT = zkc_core.L_ALT;
const R_ALT = zkc_core.R_ALT;
const R_CTL = zkc_core.R_CTL;
const DEAD = zkc_core.DEAD;
pub const keycodes = @import("keycodes.zig");

pub const QMK_RUSSIAN_TYPEWRITER_KEYCODES_VERSION = "0.0.1";
pub const QMK_RUSSIAN_TYPEWRITER_KEYCODES_VERSION_BCD = @as(c_int, 0x00000001);
pub const QMK_RUSSIAN_TYPEWRITER_KEYCODES_VERSION_MAJOR = @as(c_int, 0);
pub const QMK_RUSSIAN_TYPEWRITER_KEYCODES_VERSION_MINOR = @as(c_int, 0);
pub const QMK_RUSSIAN_TYPEWRITER_KEYCODES_VERSION_PATCH = @as(c_int, 1);

//
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ | │ № │ - │ / │ " │ : │ , │ . │ _ │ ? │ % │ ! │ ; │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ Й │ Ц │ У │ К │ Е │ Н │ Г │ Ш │ Щ │ З │ Х │ Ъ │  )  │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
// │      │ Ф │ Ы │ В │ А │ П │ Р │ О │ Л │ Д │ Ж │ Э │        │
// ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
// │        │ Я │ Ч │ С │ М │ И │ Т │ Ь │ Б │ Ю │ Ё │          │
// ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// |
pub const PIPE = keycodes.kcf.GRV;
/// №
pub const NUM = keycodes.kcf.N1;
/// -
pub const MINS = keycodes.kcf.N2;
/// /
pub const SLSH = keycodes.kcf.N3;
/// "
pub const DQUO = keycodes.kcf.N4;
/// :
pub const COLN = keycodes.kcf.N5;
/// ,
pub const COMM = keycodes.kcf.N6;
/// .
pub const DOT = keycodes.kcf.N7;
/// _
pub const UNDS = keycodes.kcf.N8;
/// ?
pub const QUES = keycodes.kcf.N9;
/// %
pub const PERC = keycodes.kcf.N0;
/// !
pub const EXLM = keycodes.kcf.MINS;
/// ;
pub const SCLN = keycodes.kcf.EQL;
/// Й
pub const SHTI = keycodes.kcf.Q;
/// Ц
pub const TSE = keycodes.kcf.W;
/// У
pub const U = keycodes.kcf.E;
/// К
pub const KA = keycodes.kcf.R;
/// Е
pub const IE = keycodes.kcf.T;
/// Н
pub const EN = keycodes.kcf.Y;
/// Г
pub const GHE = keycodes.kcf.U;
/// Ш
pub const SHA = keycodes.kcf.I;
/// Щ
pub const SHCH = keycodes.kcf.O;
/// З
pub const ZE = keycodes.kcf.P;
/// Х
pub const HA = keycodes.kcf.LBRC;
/// Ъ
pub const HARD = keycodes.kcf.RBRC;
/// )
pub const RPRN = keycodes.kcf.BSLS;
/// Ф
pub const EF = keycodes.kcf.A;
/// Ы
pub const YERU = keycodes.kcf.S;
/// В
pub const VE = keycodes.kcf.D;
/// А
pub const A = keycodes.kcf.F;
/// П
pub const PE = keycodes.kcf.G;
/// Р
pub const ER = keycodes.kcf.H;
/// О
pub const O = keycodes.kcf.J;
/// Л
pub const EL = keycodes.kcf.K;
/// Д
pub const DE = keycodes.kcf.L;
/// Ж
pub const ZHE = keycodes.kcf.SCLN;
/// Э
pub const E = keycodes.kcf.QUOT;
/// Я
pub const YA = keycodes.kcf.Z;
/// Ч
pub const CHE = keycodes.kcf.X;
/// С
pub const ES = keycodes.kcf.C;
/// М
pub const EM = keycodes.kcf.V;
/// И
pub const I = keycodes.kcf.B;
/// Т
pub const TE = keycodes.kcf.N;
/// Ь
pub const SOFT = keycodes.kcf.M;
/// Б
pub const BE = keycodes.kcf.COMM;
/// Ю
pub const YU = keycodes.kcf.DOT;
/// Ё
pub const YO = keycodes.kcf.SLSH;
// Shifted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ + │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ = │ \ │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │   │   │   │   │   │   │   │   │   │   │  (  │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
// │      │   │   │   │   │   │   │   │   │   │   │   │        │
// ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
// │        │   │   │   │   │   │   │   │   │   │   │          │
// ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// +
pub const PLUS = L_SFT(PIPE);
/// 1
pub const N1 = L_SFT(NUM);
/// 2
pub const N2 = L_SFT(MINS);
/// 3
pub const N3 = L_SFT(SLSH);
/// 4
pub const N4 = L_SFT(DQUO);
/// 5
pub const N5 = L_SFT(COLN);
/// 6
pub const N6 = L_SFT(COMM);
/// 7
pub const N7 = L_SFT(DOT);
/// 8
pub const N8 = L_SFT(UNDS);
/// 9
pub const N9 = L_SFT(QUES);
/// 0
pub const N0 = L_SFT(PERC);
/// =
pub const EQL = L_SFT(EXLM);
/// (backslash)
pub const BSLS = L_SFT(SCLN);
/// (
pub const LPRN = L_SFT(RPRN);
// AltGr symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │   │   │   │   │   │   │   │   │ ₽ │   │   │   │   │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │   │   │   │   │   │   │   │   │   │   │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
// │      │   │   │   │   │   │   │   │   │   │   │   │        │
// ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
// │        │   │   │   │   │   │   │   │   │   │   │          │
// ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ₽
pub const RUBL = R_ALT(UNDS);

// Label lookup table
pub const _labels = [_]zkc_core.LabelEntry{
    .{ .value = PIPE, .label = "PIPE", .short_label = "PIPE" },
    .{ .value = NUM, .label = "NUM", .short_label = "NUM" },
    .{ .value = MINS, .label = "MINS", .short_label = "MINS" },
    .{ .value = SLSH, .label = "SLSH", .short_label = "SLSH" },
    .{ .value = DQUO, .label = "DQUO", .short_label = "DQUO" },
    .{ .value = COLN, .label = "COLN", .short_label = "COLN" },
    .{ .value = COMM, .label = "COMM", .short_label = "COMM" },
    .{ .value = DOT, .label = "DOT", .short_label = "DOT" },
    .{ .value = UNDS, .label = "UNDS", .short_label = "UNDS" },
    .{ .value = QUES, .label = "QUES", .short_label = "QUES" },
    .{ .value = PERC, .label = "PERC", .short_label = "PERC" },
    .{ .value = EXLM, .label = "EXLM", .short_label = "EXLM" },
    .{ .value = SCLN, .label = "SCLN", .short_label = "SCLN" },
    .{ .value = SHTI, .label = "SHTI", .short_label = "SHTI" },
    .{ .value = TSE, .label = "TSE", .short_label = "TSE" },
    .{ .value = U, .label = "U", .short_label = "U" },
    .{ .value = KA, .label = "KA", .short_label = "KA" },
    .{ .value = IE, .label = "IE", .short_label = "IE" },
    .{ .value = EN, .label = "EN", .short_label = "EN" },
    .{ .value = GHE, .label = "GHE", .short_label = "GHE" },
    .{ .value = SHA, .label = "SHA", .short_label = "SHA" },
    .{ .value = SHCH, .label = "SHCH", .short_label = "SHCH" },
    .{ .value = ZE, .label = "ZE", .short_label = "ZE" },
    .{ .value = HA, .label = "HA", .short_label = "HA" },
    .{ .value = HARD, .label = "HARD", .short_label = "HARD" },
    .{ .value = RPRN, .label = "RPRN", .short_label = "RPRN" },
    .{ .value = EF, .label = "EF", .short_label = "EF" },
    .{ .value = YERU, .label = "YERU", .short_label = "YERU" },
    .{ .value = VE, .label = "VE", .short_label = "VE" },
    .{ .value = A, .label = "A", .short_label = "A" },
    .{ .value = PE, .label = "PE", .short_label = "PE" },
    .{ .value = ER, .label = "ER", .short_label = "ER" },
    .{ .value = O, .label = "O", .short_label = "O" },
    .{ .value = EL, .label = "EL", .short_label = "EL" },
    .{ .value = DE, .label = "DE", .short_label = "DE" },
    .{ .value = ZHE, .label = "ZHE", .short_label = "ZHE" },
    .{ .value = E, .label = "E", .short_label = "E" },
    .{ .value = YA, .label = "YA", .short_label = "YA" },
    .{ .value = CHE, .label = "CHE", .short_label = "CHE" },
    .{ .value = ES, .label = "ES", .short_label = "ES" },
    .{ .value = EM, .label = "EM", .short_label = "EM" },
    .{ .value = I, .label = "I", .short_label = "I" },
    .{ .value = TE, .label = "TE", .short_label = "TE" },
    .{ .value = SOFT, .label = "SOFT", .short_label = "SOFT" },
    .{ .value = BE, .label = "BE", .short_label = "BE" },
    .{ .value = YU, .label = "YU", .short_label = "YU" },
    .{ .value = YO, .label = "YO", .short_label = "YO" },
    .{ .value = PLUS, .label = "PLUS", .short_label = "PLUS" },
    .{ .value = N1, .label = "1", .short_label = "1" },
    .{ .value = N2, .label = "2", .short_label = "2" },
    .{ .value = N3, .label = "3", .short_label = "3" },
    .{ .value = N4, .label = "4", .short_label = "4" },
    .{ .value = N5, .label = "5", .short_label = "5" },
    .{ .value = N6, .label = "6", .short_label = "6" },
    .{ .value = N7, .label = "7", .short_label = "7" },
    .{ .value = N8, .label = "8", .short_label = "8" },
    .{ .value = N9, .label = "9", .short_label = "9" },
    .{ .value = N0, .label = "0", .short_label = "0" },
    .{ .value = EQL, .label = "EQL", .short_label = "EQL" },
    .{ .value = BSLS, .label = "BSLS", .short_label = "BSLS" },
    .{ .value = LPRN, .label = "LPRN", .short_label = "LPRN" },
    .{ .value = RUBL, .label = "RUBL", .short_label = "RUBL" },
};

pub fn getLabel(keycode: core.KeyCodeFire, shortest: bool) ?[]const u8 {
    return zkc_core.getLabel(&_labels, keycode, shortest);
}
