// Copyright 2026 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by zkeycodes from QMK hjson keycode files
const zkc_core = @import("../src/core.zig");
const core = @import("zigmkay").core;
const L_SFT = zkc_core.L_SFT;
const L_ALT = zkc_core.L_ALT;
const R_ALT = zkc_core.R_ALT;
const R_CTL = zkc_core.R_CTL;
const DEAD = zkc_core.DEAD;
pub const keycodes = @import("keycodes.zig");

pub const QMK_SERBIAN_KEYCODES_VERSION = "0.0.1";
pub const QMK_SERBIAN_KEYCODES_VERSION_BCD = @as(c_int, 0x00000001);
pub const QMK_SERBIAN_KEYCODES_VERSION_MAJOR = @as(c_int, 0);
pub const QMK_SERBIAN_KEYCODES_VERSION_MINOR = @as(c_int, 0);
pub const QMK_SERBIAN_KEYCODES_VERSION_PATCH = @as(c_int, 1);

//
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ` │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ ' │ + │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ Љ │ Њ │ Е │ Р │ Т │ З │ У │ И │ О │ П │ Ш │ Ђ │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │ А │ С │ Д │ Ф │ Г │ Х │ Ј │ К │ Л │ Ч │ Ћ │ Ж │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ < │ Ѕ │ Џ │ Ц │ В │ Б │ Н │ М │ , │ . │ - │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// `
pub const GRV = keycodes.kcf.GRV;
/// 1
pub const N1 = keycodes.kcf.N1;
/// 2
pub const N2 = keycodes.kcf.N2;
/// 3
pub const N3 = keycodes.kcf.N3;
/// 4
pub const N4 = keycodes.kcf.N4;
/// 5
pub const N5 = keycodes.kcf.N5;
/// 6
pub const N6 = keycodes.kcf.N6;
/// 7
pub const N7 = keycodes.kcf.N7;
/// 8
pub const N8 = keycodes.kcf.N8;
/// 9
pub const N9 = keycodes.kcf.N9;
/// 0
pub const N0 = keycodes.kcf.N0;
/// ' (dead)
pub const QUOT = DEAD(keycodes.kcf.MINS);
/// +
pub const PLUS = keycodes.kcf.EQL;
/// Љ
pub const LJE = keycodes.kcf.Q;
/// Њ
pub const NJE = keycodes.kcf.W;
/// Е
pub const IE = keycodes.kcf.E;
/// Р
pub const ER = keycodes.kcf.R;
/// Т
pub const TE = keycodes.kcf.T;
/// З
pub const ZE = keycodes.kcf.Y;
/// У
pub const U = keycodes.kcf.U;
/// И
pub const I = keycodes.kcf.I;
/// О
pub const O = keycodes.kcf.O;
/// П
pub const PE = keycodes.kcf.P;
/// Ш
pub const SHA = keycodes.kcf.LBRC;
/// Ђ
pub const DJE = keycodes.kcf.RBRC;
/// А
pub const A = keycodes.kcf.A;
/// С
pub const ES = keycodes.kcf.S;
/// Д
pub const DE = keycodes.kcf.D;
/// Ф
pub const EF = keycodes.kcf.F;
/// Г
pub const GHE = keycodes.kcf.G;
/// Х
pub const HA = keycodes.kcf.H;
/// Ј
pub const JE = keycodes.kcf.J;
/// К
pub const KA = keycodes.kcf.K;
/// Л
pub const EL = keycodes.kcf.L;
/// Ч
pub const CHE = keycodes.kcf.SCLN;
/// Ћ
pub const TSHE = keycodes.kcf.QUOT;
/// Ж
pub const ZHE = keycodes.kcf.NUHS;
/// <
pub const LABK = keycodes.kcf.NUBS;
/// Ѕ
pub const DZE = keycodes.kcf.Z;
/// Џ
pub const DZHE = keycodes.kcf.X;
/// Ц
pub const TSE = keycodes.kcf.C;
/// В
pub const VE = keycodes.kcf.V;
/// Б
pub const BE = keycodes.kcf.B;
/// Н
pub const EN = keycodes.kcf.N;
/// М
pub const EM = keycodes.kcf.M;
/// ,
pub const COMM = keycodes.kcf.COMM;
/// .
pub const DOT = keycodes.kcf.DOT;
/// -
pub const MINS = keycodes.kcf.SLSH;
// Shifted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ~ │ ! │ " │ # │ $ │ % │ & │ / │ ( │ ) │ = │ ? │ * │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │   │   │   │   │   │   │   │   │   │   │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │   │   │   │   │   │   │   │   │   │   │   │   │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ > │   │   │   │   │   │   │   │ ; │ : │ _ │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ~
pub const TILD = L_SFT(GRV);
/// !
pub const EXLM = L_SFT(N1);
/// "
pub const DQUO = L_SFT(N2);
/// #
pub const HASH = L_SFT(N3);
/// $
pub const DLR = L_SFT(N4);
/// %
pub const PERC = L_SFT(N5);
/// &
pub const AMPR = L_SFT(N6);
/// /
pub const SLSH = L_SFT(N7);
/// (
pub const LPRN = L_SFT(N8);
/// )
pub const RPRN = L_SFT(N9);
/// =
pub const EQL = L_SFT(N0);
/// ?
pub const QUES = L_SFT(QUOT);
/// *
pub const ASTR = L_SFT(PLUS);
/// >
pub const RABK = L_SFT(LABK);
/// ;
pub const SCLN = L_SFT(COMM);
/// :
pub const COLN = L_SFT(DOT);
/// _
pub const UNDS = L_SFT(MINS);
// AltGr symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │   │   │   │   │   │   │   │   │   │   │   │   │   │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │ € │   │   │   │   │   │   │   │   │   │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │   │   │   │   │   │   │   │   │   │   │   │   │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │   │   │   │   │   │   │   │   │   │   │   │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// €
pub const EURO = R_ALT(IE);

// Label lookup table
pub const _labels = [_]zkc_core.LabelEntry{
    .{ .value = GRV, .label = "GRV", .short_label = "GRV" },
    .{ .value = N1, .label = "1", .short_label = "1" },
    .{ .value = N2, .label = "2", .short_label = "2" },
    .{ .value = N3, .label = "3", .short_label = "3" },
    .{ .value = N4, .label = "4", .short_label = "4" },
    .{ .value = N5, .label = "5", .short_label = "5" },
    .{ .value = N6, .label = "6", .short_label = "6" },
    .{ .value = N7, .label = "7", .short_label = "7" },
    .{ .value = N8, .label = "8", .short_label = "8" },
    .{ .value = N9, .label = "9", .short_label = "9" },
    .{ .value = N0, .label = "0", .short_label = "0" },
    .{ .value = QUOT, .label = "QUOT", .short_label = "QUOT" },
    .{ .value = PLUS, .label = "PLUS", .short_label = "PLUS" },
    .{ .value = LJE, .label = "LJE", .short_label = "LJE" },
    .{ .value = NJE, .label = "NJE", .short_label = "NJE" },
    .{ .value = IE, .label = "IE", .short_label = "IE" },
    .{ .value = ER, .label = "ER", .short_label = "ER" },
    .{ .value = TE, .label = "TE", .short_label = "TE" },
    .{ .value = ZE, .label = "ZE", .short_label = "ZE" },
    .{ .value = U, .label = "U", .short_label = "U" },
    .{ .value = I, .label = "I", .short_label = "I" },
    .{ .value = O, .label = "O", .short_label = "O" },
    .{ .value = PE, .label = "PE", .short_label = "PE" },
    .{ .value = SHA, .label = "SHA", .short_label = "SHA" },
    .{ .value = DJE, .label = "DJE", .short_label = "DJE" },
    .{ .value = A, .label = "A", .short_label = "A" },
    .{ .value = ES, .label = "ES", .short_label = "ES" },
    .{ .value = DE, .label = "DE", .short_label = "DE" },
    .{ .value = EF, .label = "EF", .short_label = "EF" },
    .{ .value = GHE, .label = "GHE", .short_label = "GHE" },
    .{ .value = HA, .label = "HA", .short_label = "HA" },
    .{ .value = JE, .label = "JE", .short_label = "JE" },
    .{ .value = KA, .label = "KA", .short_label = "KA" },
    .{ .value = EL, .label = "EL", .short_label = "EL" },
    .{ .value = CHE, .label = "CHE", .short_label = "CHE" },
    .{ .value = TSHE, .label = "TSHE", .short_label = "TSHE" },
    .{ .value = ZHE, .label = "ZHE", .short_label = "ZHE" },
    .{ .value = LABK, .label = "LABK", .short_label = "LABK" },
    .{ .value = DZE, .label = "DZE", .short_label = "DZE" },
    .{ .value = DZHE, .label = "DZHE", .short_label = "DZHE" },
    .{ .value = TSE, .label = "TSE", .short_label = "TSE" },
    .{ .value = VE, .label = "VE", .short_label = "VE" },
    .{ .value = BE, .label = "BE", .short_label = "BE" },
    .{ .value = EN, .label = "EN", .short_label = "EN" },
    .{ .value = EM, .label = "EM", .short_label = "EM" },
    .{ .value = COMM, .label = "COMM", .short_label = "COMM" },
    .{ .value = DOT, .label = "DOT", .short_label = "DOT" },
    .{ .value = MINS, .label = "MINS", .short_label = "MINS" },
    .{ .value = TILD, .label = "TILD", .short_label = "TILD" },
    .{ .value = EXLM, .label = "EXLM", .short_label = "EXLM" },
    .{ .value = DQUO, .label = "DQUO", .short_label = "DQUO" },
    .{ .value = HASH, .label = "HASH", .short_label = "HASH" },
    .{ .value = DLR, .label = "DLR", .short_label = "DLR" },
    .{ .value = PERC, .label = "PERC", .short_label = "PERC" },
    .{ .value = AMPR, .label = "AMPR", .short_label = "AMPR" },
    .{ .value = SLSH, .label = "SLSH", .short_label = "SLSH" },
    .{ .value = LPRN, .label = "LPRN", .short_label = "LPRN" },
    .{ .value = RPRN, .label = "RPRN", .short_label = "RPRN" },
    .{ .value = EQL, .label = "EQL", .short_label = "EQL" },
    .{ .value = QUES, .label = "QUES", .short_label = "QUES" },
    .{ .value = ASTR, .label = "ASTR", .short_label = "ASTR" },
    .{ .value = RABK, .label = "RABK", .short_label = "RABK" },
    .{ .value = SCLN, .label = "SCLN", .short_label = "SCLN" },
    .{ .value = COLN, .label = "COLN", .short_label = "COLN" },
    .{ .value = UNDS, .label = "UNDS", .short_label = "UNDS" },
    .{ .value = EURO, .label = "EURO", .short_label = "EURO" },
};

pub fn getLabel(keycode: core.KeyCodeFire, shortest: bool) ?[]const u8 {
    return zkc_core.getLabel(&_labels, keycode, shortest);
}
