// Copyright 2026 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by zkeycodes from QMK hjson keycode files
const zkc_core = @import("../src/core.zig");
const core = @import("zigmkay").core;
const L_SFT = zkc_core.L_SFT;
const L_ALT = zkc_core.L_ALT;
const R_ALT = zkc_core.R_ALT;
const R_CTL = zkc_core.R_CTL;
const DEAD = zkc_core.DEAD;
pub const keycodes = @import("keycodes.zig");

pub const QMK_SLOVENIAN_KEYCODES_VERSION = "0.0.1";
pub const QMK_SLOVENIAN_KEYCODES_VERSION_BCD = @as(c_int, 0x00000001);
pub const QMK_SLOVENIAN_KEYCODES_VERSION_MAJOR = @as(c_int, 0);
pub const QMK_SLOVENIAN_KEYCODES_VERSION_MINOR = @as(c_int, 0);
pub const QMK_SLOVENIAN_KEYCODES_VERSION_PATCH = @as(c_int, 1);

//
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ¸ │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ ' │ + │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ Q │ W │ E │ R │ T │ Z │ U │ I │ O │ P │ Š │ Đ │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ Č │ Ć │ Ž │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ < │ Y │ X │ C │ V │ B │ N │ M │ , │ . │ - │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ¸ (dead)
pub const CEDL = DEAD(keycodes.kcf.GRV);
/// 1
pub const N1 = keycodes.kcf.N1;
/// 2
pub const N2 = keycodes.kcf.N2;
/// 3
pub const N3 = keycodes.kcf.N3;
/// 4
pub const N4 = keycodes.kcf.N4;
/// 5
pub const N5 = keycodes.kcf.N5;
/// 6
pub const N6 = keycodes.kcf.N6;
/// 7
pub const N7 = keycodes.kcf.N7;
/// 8
pub const N8 = keycodes.kcf.N8;
/// 9
pub const N9 = keycodes.kcf.N9;
/// 0
pub const N0 = keycodes.kcf.N0;
/// '
pub const QUOT = keycodes.kcf.MINS;
/// +
pub const PLUS = keycodes.kcf.EQL;
/// Q
pub const Q = keycodes.kcf.Q;
/// W
pub const W = keycodes.kcf.W;
/// E
pub const E = keycodes.kcf.E;
/// R
pub const R = keycodes.kcf.R;
/// T
pub const T = keycodes.kcf.T;
/// Z
pub const Z = keycodes.kcf.Y;
/// U
pub const U = keycodes.kcf.U;
/// I
pub const I = keycodes.kcf.I;
/// O
pub const O = keycodes.kcf.O;
/// P
pub const P = keycodes.kcf.P;
/// Š
pub const SCAR = keycodes.kcf.LBRC;
/// Đ
pub const DSTR = keycodes.kcf.RBRC;
/// A
pub const A = keycodes.kcf.A;
/// S
pub const S = keycodes.kcf.S;
/// D
pub const D = keycodes.kcf.D;
/// F
pub const F = keycodes.kcf.F;
/// G
pub const G = keycodes.kcf.G;
/// H
pub const H = keycodes.kcf.H;
/// J
pub const J = keycodes.kcf.J;
/// K
pub const K = keycodes.kcf.K;
/// L
pub const L = keycodes.kcf.L;
/// Č
pub const CCAR = keycodes.kcf.SCLN;
/// Ć
pub const CACU = keycodes.kcf.QUOT;
/// Ž
pub const ZCAR = keycodes.kcf.NUHS;
/// <
pub const LABK = keycodes.kcf.NUBS;
/// Y
pub const Y = keycodes.kcf.Z;
/// X
pub const X = keycodes.kcf.X;
/// C
pub const C = keycodes.kcf.C;
/// V
pub const V = keycodes.kcf.V;
/// B
pub const B = keycodes.kcf.B;
/// N
pub const N = keycodes.kcf.N;
/// M
pub const M = keycodes.kcf.M;
/// ,
pub const COMM = keycodes.kcf.COMM;
/// .
pub const DOT = keycodes.kcf.DOT;
/// -
pub const MINS = keycodes.kcf.SLSH;
// Shifted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ¨ │ ! │ " │ # │ $ │ % │ & │ / │ ( │ ) │ = │ ? │ * │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │   │   │   │   │   │   │   │   │   │   │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │   │   │   │   │   │   │   │   │   │   │   │   │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ > │   │   │   │   │   │   │   │ ; │ : │ _ │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ¨ (dead)
pub const DIAE = DEAD(L_SFT(CEDL));
/// !
pub const EXLM = L_SFT(N1);
/// "
pub const DQUO = L_SFT(N2);
/// #
pub const HASH = L_SFT(N3);
/// $
pub const DLR = L_SFT(N4);
/// %
pub const PERC = L_SFT(N5);
/// &
pub const AMPR = L_SFT(N6);
/// /
pub const SLSH = L_SFT(N7);
/// (
pub const LPRN = L_SFT(N8);
/// )
pub const RPRN = L_SFT(N9);
/// =
pub const EQL = L_SFT(N0);
/// ?
pub const QUES = L_SFT(QUOT);
/// *
pub const ASTR = L_SFT(PLUS);
/// >
pub const RABK = L_SFT(LABK);
/// ;
pub const SCLN = L_SFT(COMM);
/// :
pub const COLN = L_SFT(DOT);
/// _
pub const UNDS = L_SFT(MINS);
// AltGr symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │   │ ~ │ ˇ │ ^ │ ˘ │ ° │ ˛ │ ` │ ˙ │ ´ │ ˝ │   │   │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ \ │ | │ € │   │   │   │   │   │   │   │ ÷ │ × │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │   │   │   │ [ │ ] │   │   │ ł │ Ł │   │ ß │ ¤ │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │   │   │   │   │ @ │ { │ } │ § │   │   │   │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ~
pub const TILD = R_ALT(N1);
/// ˇ (dead)
pub const CARN = DEAD(R_ALT(N2));
/// ^ (dead)
pub const CIRC = DEAD(R_ALT(N3));
/// ˘ (dead)
pub const BREV = DEAD(R_ALT(N4));
/// ° (dead)
pub const RNGA = DEAD(R_ALT(N5));
/// ˛ (dead)
pub const OGON = DEAD(R_ALT(N6));
/// `
pub const GRV = R_ALT(N7);
/// ˙ (dead)
pub const DOTA = DEAD(R_ALT(N8));
/// ´ (dead)
pub const ACUT = DEAD(R_ALT(N9));
/// ˝ (dead)
pub const DACU = DEAD(R_ALT(N0));
/// (backslash)
pub const BSLS = R_ALT(Q);
/// |
pub const PIPE = R_ALT(W);
/// €
pub const EURO = R_ALT(E);
/// ÷
pub const DIV = R_ALT(SCAR);
/// ×
pub const MUL = R_ALT(DSTR);
/// [
pub const LBRC = R_ALT(F);
/// ]
pub const RBRC = R_ALT(G);
/// ł
pub const LLST = R_ALT(K);
/// Ł
pub const CLST = R_ALT(L);
/// ß
pub const SS = R_ALT(CACU);
/// ¤
pub const CURR = R_ALT(ZCAR);
/// @
pub const AT = R_ALT(V);
/// {
pub const LCBR = R_ALT(B);
/// }
pub const RCBR = R_ALT(N);
/// §
pub const SECT = R_ALT(M);

// Label lookup table
pub const _labels = [_]zkc_core.LabelEntry{
    .{ .value = CEDL, .label = "CEDL", .short_label = "CEDL" },
    .{ .value = N1, .label = "1", .short_label = "1" },
    .{ .value = N2, .label = "2", .short_label = "2" },
    .{ .value = N3, .label = "3", .short_label = "3" },
    .{ .value = N4, .label = "4", .short_label = "4" },
    .{ .value = N5, .label = "5", .short_label = "5" },
    .{ .value = N6, .label = "6", .short_label = "6" },
    .{ .value = N7, .label = "7", .short_label = "7" },
    .{ .value = N8, .label = "8", .short_label = "8" },
    .{ .value = N9, .label = "9", .short_label = "9" },
    .{ .value = N0, .label = "0", .short_label = "0" },
    .{ .value = QUOT, .label = "QUOT", .short_label = "QUOT" },
    .{ .value = PLUS, .label = "PLUS", .short_label = "PLUS" },
    .{ .value = Q, .label = "Q", .short_label = "Q" },
    .{ .value = W, .label = "W", .short_label = "W" },
    .{ .value = E, .label = "E", .short_label = "E" },
    .{ .value = R, .label = "R", .short_label = "R" },
    .{ .value = T, .label = "T", .short_label = "T" },
    .{ .value = Z, .label = "Z", .short_label = "Z" },
    .{ .value = U, .label = "U", .short_label = "U" },
    .{ .value = I, .label = "I", .short_label = "I" },
    .{ .value = O, .label = "O", .short_label = "O" },
    .{ .value = P, .label = "P", .short_label = "P" },
    .{ .value = SCAR, .label = "SCAR", .short_label = "SCAR" },
    .{ .value = DSTR, .label = "DSTR", .short_label = "DSTR" },
    .{ .value = A, .label = "A", .short_label = "A" },
    .{ .value = S, .label = "S", .short_label = "S" },
    .{ .value = D, .label = "D", .short_label = "D" },
    .{ .value = F, .label = "F", .short_label = "F" },
    .{ .value = G, .label = "G", .short_label = "G" },
    .{ .value = H, .label = "H", .short_label = "H" },
    .{ .value = J, .label = "J", .short_label = "J" },
    .{ .value = K, .label = "K", .short_label = "K" },
    .{ .value = L, .label = "L", .short_label = "L" },
    .{ .value = CCAR, .label = "CCAR", .short_label = "CCAR" },
    .{ .value = CACU, .label = "CACU", .short_label = "CACU" },
    .{ .value = ZCAR, .label = "ZCAR", .short_label = "ZCAR" },
    .{ .value = LABK, .label = "LABK", .short_label = "LABK" },
    .{ .value = Y, .label = "Y", .short_label = "Y" },
    .{ .value = X, .label = "X", .short_label = "X" },
    .{ .value = C, .label = "C", .short_label = "C" },
    .{ .value = V, .label = "V", .short_label = "V" },
    .{ .value = B, .label = "B", .short_label = "B" },
    .{ .value = N, .label = "N", .short_label = "N" },
    .{ .value = M, .label = "M", .short_label = "M" },
    .{ .value = COMM, .label = "COMM", .short_label = "COMM" },
    .{ .value = DOT, .label = "DOT", .short_label = "DOT" },
    .{ .value = MINS, .label = "MINS", .short_label = "MINS" },
    .{ .value = DIAE, .label = "DIAE", .short_label = "DIAE" },
    .{ .value = EXLM, .label = "EXLM", .short_label = "EXLM" },
    .{ .value = DQUO, .label = "DQUO", .short_label = "DQUO" },
    .{ .value = HASH, .label = "HASH", .short_label = "HASH" },
    .{ .value = DLR, .label = "DLR", .short_label = "DLR" },
    .{ .value = PERC, .label = "PERC", .short_label = "PERC" },
    .{ .value = AMPR, .label = "AMPR", .short_label = "AMPR" },
    .{ .value = SLSH, .label = "SLSH", .short_label = "SLSH" },
    .{ .value = LPRN, .label = "LPRN", .short_label = "LPRN" },
    .{ .value = RPRN, .label = "RPRN", .short_label = "RPRN" },
    .{ .value = EQL, .label = "EQL", .short_label = "EQL" },
    .{ .value = QUES, .label = "QUES", .short_label = "QUES" },
    .{ .value = ASTR, .label = "ASTR", .short_label = "ASTR" },
    .{ .value = RABK, .label = "RABK", .short_label = "RABK" },
    .{ .value = SCLN, .label = "SCLN", .short_label = "SCLN" },
    .{ .value = COLN, .label = "COLN", .short_label = "COLN" },
    .{ .value = UNDS, .label = "UNDS", .short_label = "UNDS" },
    .{ .value = TILD, .label = "TILD", .short_label = "TILD" },
    .{ .value = CARN, .label = "CARN", .short_label = "CARN" },
    .{ .value = CIRC, .label = "CIRC", .short_label = "CIRC" },
    .{ .value = BREV, .label = "BREV", .short_label = "BREV" },
    .{ .value = RNGA, .label = "RNGA", .short_label = "RNGA" },
    .{ .value = OGON, .label = "OGON", .short_label = "OGON" },
    .{ .value = GRV, .label = "GRV", .short_label = "GRV" },
    .{ .value = DOTA, .label = "DOTA", .short_label = "DOTA" },
    .{ .value = ACUT, .label = "ACUT", .short_label = "ACUT" },
    .{ .value = DACU, .label = "DACU", .short_label = "DACU" },
    .{ .value = BSLS, .label = "BSLS", .short_label = "BSLS" },
    .{ .value = PIPE, .label = "PIPE", .short_label = "PIPE" },
    .{ .value = EURO, .label = "EURO", .short_label = "EURO" },
    .{ .value = DIV, .label = "DIV", .short_label = "DIV" },
    .{ .value = MUL, .label = "MUL", .short_label = "MUL" },
    .{ .value = LBRC, .label = "LBRC", .short_label = "LBRC" },
    .{ .value = RBRC, .label = "RBRC", .short_label = "RBRC" },
    .{ .value = LLST, .label = "LLST", .short_label = "LLST" },
    .{ .value = CLST, .label = "CLST", .short_label = "CLST" },
    .{ .value = SS, .label = "SS", .short_label = "SS" },
    .{ .value = CURR, .label = "CURR", .short_label = "CURR" },
    .{ .value = AT, .label = "AT", .short_label = "AT" },
    .{ .value = LCBR, .label = "LCBR", .short_label = "LCBR" },
    .{ .value = RCBR, .label = "RCBR", .short_label = "RCBR" },
    .{ .value = SECT, .label = "SECT", .short_label = "SECT" },
};

pub fn getLabel(keycode: core.KeyCodeFire, shortest: bool) ?[]const u8 {
    return zkc_core.getLabel(&_labels, keycode, shortest);
}
