// Copyright 2026 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by zkeycodes from QMK hjson keycode files
const zkc_core = @import("../src/core.zig");
const core = @import("zigmkay").core;
const L_SFT = zkc_core.L_SFT;
const L_ALT = zkc_core.L_ALT;
const R_ALT = zkc_core.R_ALT;
const R_CTL = zkc_core.R_CTL;
const DEAD = zkc_core.DEAD;
pub const keycodes = @import("keycodes.zig");

pub const QMK_SLOVAK_KEYCODES_VERSION = "0.0.1";
pub const QMK_SLOVAK_KEYCODES_VERSION_BCD = @as(c_int, 0x00000001);
pub const QMK_SLOVAK_KEYCODES_VERSION_MAJOR = @as(c_int, 0);
pub const QMK_SLOVAK_KEYCODES_VERSION_MINOR = @as(c_int, 0);
pub const QMK_SLOVAK_KEYCODES_VERSION_PATCH = @as(c_int, 1);

//
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ; │ + │ ľ │ š │ č │ ť │ ž │ ý │ á │ í │ é │ = │ ´ │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ Q │ W │ E │ R │ T │ Z │ U │ I │ O │ P │ ú │ ä │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ ô │ § │ ň │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ & │ Y │ X │ C │ V │ B │ N │ M │ , │ . │ - │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ;
pub const SCLN = keycodes.kcf.GRV;
/// +
pub const PLUS = keycodes.kcf.N1;
/// ľ
pub const LCAR = keycodes.kcf.N2;
/// š
pub const SCAR = keycodes.kcf.N3;
/// č
pub const CCAR = keycodes.kcf.N4;
/// ť
pub const TCAR = keycodes.kcf.N5;
/// ž
pub const ZCAR = keycodes.kcf.N6;
/// ý
pub const YACU = keycodes.kcf.N7;
/// á
pub const AACU = keycodes.kcf.N8;
/// í
pub const IACU = keycodes.kcf.N9;
/// é
pub const EACU = keycodes.kcf.N0;
/// =
pub const EQL = keycodes.kcf.MINS;
/// ´ (dead)
pub const ACUT = DEAD(keycodes.kcf.EQL);
/// Q
pub const Q = keycodes.kcf.Q;
/// W
pub const W = keycodes.kcf.W;
/// E
pub const E = keycodes.kcf.E;
/// R
pub const R = keycodes.kcf.R;
/// T
pub const T = keycodes.kcf.T;
/// Z
pub const Z = keycodes.kcf.Y;
/// U
pub const U = keycodes.kcf.U;
/// I
pub const I = keycodes.kcf.I;
/// O
pub const O = keycodes.kcf.O;
/// P
pub const P = keycodes.kcf.P;
/// ú
pub const UACU = keycodes.kcf.LBRC;
/// ä
pub const ADIA = keycodes.kcf.RBRC;
/// A
pub const A = keycodes.kcf.A;
/// S
pub const S = keycodes.kcf.S;
/// D
pub const D = keycodes.kcf.D;
/// F
pub const F = keycodes.kcf.F;
/// G
pub const G = keycodes.kcf.G;
/// H
pub const H = keycodes.kcf.H;
/// J
pub const J = keycodes.kcf.J;
/// K
pub const K = keycodes.kcf.K;
/// L
pub const L = keycodes.kcf.L;
/// ô
pub const OCIR = keycodes.kcf.SCLN;
/// §
pub const SECT = keycodes.kcf.QUOT;
/// ň
pub const NCAR = keycodes.kcf.NUHS;
/// &
pub const AMPR = keycodes.kcf.NUBS;
/// Y
pub const Y = keycodes.kcf.Z;
/// X
pub const X = keycodes.kcf.X;
/// C
pub const C = keycodes.kcf.C;
/// V
pub const V = keycodes.kcf.V;
/// B
pub const B = keycodes.kcf.B;
/// N
pub const N = keycodes.kcf.N;
/// M
pub const M = keycodes.kcf.M;
/// ,
pub const COMM = keycodes.kcf.COMM;
/// .
pub const DOT = keycodes.kcf.DOT;
/// -
pub const MINS = keycodes.kcf.SLSH;
// Shifted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ° │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ % │ ˇ │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │   │   │   │   │   │   │   │   │ / │ ( │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │   │   │   │   │   │   │   │   │   │ " │ ! │ ) │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ * │   │   │   │   │   │   │   │ ? │ : │ _ │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ° (dead)
pub const RNGA = DEAD(L_SFT(SCLN));
/// 1
pub const N1 = L_SFT(PLUS);
/// 2
pub const N2 = L_SFT(LCAR);
/// 3
pub const N3 = L_SFT(SCAR);
/// 4
pub const N4 = L_SFT(CCAR);
/// 5
pub const N5 = L_SFT(TCAR);
/// 6
pub const N6 = L_SFT(ZCAR);
/// 7
pub const N7 = L_SFT(YACU);
/// 8
pub const N8 = L_SFT(AACU);
/// 9
pub const N9 = L_SFT(IACU);
/// 0
pub const N0 = L_SFT(EACU);
/// %
pub const PERC = L_SFT(EQL);
/// ˇ (dead)
pub const CARN = DEAD(L_SFT(ACUT));
/// /
pub const SLSH = L_SFT(UACU);
/// (
pub const LPRN = L_SFT(ADIA);
/// "
pub const DQUO = L_SFT(OCIR);
/// !
pub const EXLM = L_SFT(SECT);
/// )
pub const RPRN = L_SFT(NCAR);
/// *
pub const ASTR = L_SFT(AMPR);
/// ?
pub const QUES = L_SFT(COMM);
/// :
pub const COLN = L_SFT(DOT);
/// _
pub const UNDS = L_SFT(MINS);
// AltGr symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │   │ ~ │   │ ^ │ ˘ │ ° │ ˛ │ ` │ ˙ │   │ ˝ │ ¨ │ ¸ │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ \ │ | │ € │   │   │   │   │   │   │ ' │ ÷ │ × │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │   │ đ │ Đ │ [ │ ] │   │   │ ł │ Ł │ $ │ ß │ ¤ │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ < │ > │ # │   │ @ │ { │ } │   │   │   │   │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ~
pub const TILD = R_ALT(PLUS);
/// ^ (dead)
pub const CIRC = DEAD(R_ALT(SCAR));
/// ˘ (dead)
pub const BREV = DEAD(R_ALT(CCAR));
/// ˛ (dead)
pub const OGON = DEAD(R_ALT(TCAR));
/// `
pub const GRV = R_ALT(ZCAR);
/// ˙ (dead)
pub const DOTA = DEAD(R_ALT(YACU));
/// ˝ (dead)
pub const DACU = DEAD(R_ALT(EACU));
/// ¨ (dead)
pub const DIAE = DEAD(R_ALT(EQL));
/// ¸ (dead)
pub const CEDL = DEAD(R_ALT(ACUT));
/// (backslash)
pub const BSLS = R_ALT(Q);
/// |
pub const PIPE = R_ALT(W);
/// €
pub const EURO = R_ALT(E);
/// '
pub const QUOT = R_ALT(P);
/// ÷
pub const DIV = R_ALT(UACU);
/// ×
pub const MUL = R_ALT(ADIA);
/// đ
pub const LDST = R_ALT(S);
/// Đ
pub const CDST = R_ALT(D);
/// [
pub const LBRC = R_ALT(F);
/// ]
pub const RBRC = R_ALT(G);
/// ł
pub const LLST = R_ALT(K);
/// Ł
pub const CLST = R_ALT(L);
/// $
pub const DLR = R_ALT(OCIR);
/// ß
pub const SS = R_ALT(SECT);
/// ¤
pub const CURR = R_ALT(NCAR);
/// <
pub const LABK = R_ALT(AMPR);
/// >
pub const RABK = R_ALT(Y);
/// #
pub const HASH = R_ALT(X);
/// @
pub const AT = R_ALT(V);
/// {
pub const LCBR = R_ALT(B);
/// }
pub const RCBR = R_ALT(N);

// Label lookup table
pub const _labels = [_]zkc_core.LabelEntry{
    .{ .value = SCLN, .label = "SCLN", .short_label = "SCLN" },
    .{ .value = PLUS, .label = "PLUS", .short_label = "PLUS" },
    .{ .value = LCAR, .label = "LCAR", .short_label = "LCAR" },
    .{ .value = SCAR, .label = "SCAR", .short_label = "SCAR" },
    .{ .value = CCAR, .label = "CCAR", .short_label = "CCAR" },
    .{ .value = TCAR, .label = "TCAR", .short_label = "TCAR" },
    .{ .value = ZCAR, .label = "ZCAR", .short_label = "ZCAR" },
    .{ .value = YACU, .label = "YACU", .short_label = "YACU" },
    .{ .value = AACU, .label = "AACU", .short_label = "AACU" },
    .{ .value = IACU, .label = "IACU", .short_label = "IACU" },
    .{ .value = EACU, .label = "EACU", .short_label = "EACU" },
    .{ .value = EQL, .label = "EQL", .short_label = "EQL" },
    .{ .value = ACUT, .label = "ACUT", .short_label = "ACUT" },
    .{ .value = Q, .label = "Q", .short_label = "Q" },
    .{ .value = W, .label = "W", .short_label = "W" },
    .{ .value = E, .label = "E", .short_label = "E" },
    .{ .value = R, .label = "R", .short_label = "R" },
    .{ .value = T, .label = "T", .short_label = "T" },
    .{ .value = Z, .label = "Z", .short_label = "Z" },
    .{ .value = U, .label = "U", .short_label = "U" },
    .{ .value = I, .label = "I", .short_label = "I" },
    .{ .value = O, .label = "O", .short_label = "O" },
    .{ .value = P, .label = "P", .short_label = "P" },
    .{ .value = UACU, .label = "UACU", .short_label = "UACU" },
    .{ .value = ADIA, .label = "ADIA", .short_label = "ADIA" },
    .{ .value = A, .label = "A", .short_label = "A" },
    .{ .value = S, .label = "S", .short_label = "S" },
    .{ .value = D, .label = "D", .short_label = "D" },
    .{ .value = F, .label = "F", .short_label = "F" },
    .{ .value = G, .label = "G", .short_label = "G" },
    .{ .value = H, .label = "H", .short_label = "H" },
    .{ .value = J, .label = "J", .short_label = "J" },
    .{ .value = K, .label = "K", .short_label = "K" },
    .{ .value = L, .label = "L", .short_label = "L" },
    .{ .value = OCIR, .label = "OCIR", .short_label = "OCIR" },
    .{ .value = SECT, .label = "SECT", .short_label = "SECT" },
    .{ .value = NCAR, .label = "NCAR", .short_label = "NCAR" },
    .{ .value = AMPR, .label = "AMPR", .short_label = "AMPR" },
    .{ .value = Y, .label = "Y", .short_label = "Y" },
    .{ .value = X, .label = "X", .short_label = "X" },
    .{ .value = C, .label = "C", .short_label = "C" },
    .{ .value = V, .label = "V", .short_label = "V" },
    .{ .value = B, .label = "B", .short_label = "B" },
    .{ .value = N, .label = "N", .short_label = "N" },
    .{ .value = M, .label = "M", .short_label = "M" },
    .{ .value = COMM, .label = "COMM", .short_label = "COMM" },
    .{ .value = DOT, .label = "DOT", .short_label = "DOT" },
    .{ .value = MINS, .label = "MINS", .short_label = "MINS" },
    .{ .value = RNGA, .label = "RNGA", .short_label = "RNGA" },
    .{ .value = N1, .label = "1", .short_label = "1" },
    .{ .value = N2, .label = "2", .short_label = "2" },
    .{ .value = N3, .label = "3", .short_label = "3" },
    .{ .value = N4, .label = "4", .short_label = "4" },
    .{ .value = N5, .label = "5", .short_label = "5" },
    .{ .value = N6, .label = "6", .short_label = "6" },
    .{ .value = N7, .label = "7", .short_label = "7" },
    .{ .value = N8, .label = "8", .short_label = "8" },
    .{ .value = N9, .label = "9", .short_label = "9" },
    .{ .value = N0, .label = "0", .short_label = "0" },
    .{ .value = PERC, .label = "PERC", .short_label = "PERC" },
    .{ .value = CARN, .label = "CARN", .short_label = "CARN" },
    .{ .value = SLSH, .label = "SLSH", .short_label = "SLSH" },
    .{ .value = LPRN, .label = "LPRN", .short_label = "LPRN" },
    .{ .value = DQUO, .label = "DQUO", .short_label = "DQUO" },
    .{ .value = EXLM, .label = "EXLM", .short_label = "EXLM" },
    .{ .value = RPRN, .label = "RPRN", .short_label = "RPRN" },
    .{ .value = ASTR, .label = "ASTR", .short_label = "ASTR" },
    .{ .value = QUES, .label = "QUES", .short_label = "QUES" },
    .{ .value = COLN, .label = "COLN", .short_label = "COLN" },
    .{ .value = UNDS, .label = "UNDS", .short_label = "UNDS" },
    .{ .value = TILD, .label = "TILD", .short_label = "TILD" },
    .{ .value = CIRC, .label = "CIRC", .short_label = "CIRC" },
    .{ .value = BREV, .label = "BREV", .short_label = "BREV" },
    .{ .value = OGON, .label = "OGON", .short_label = "OGON" },
    .{ .value = GRV, .label = "GRV", .short_label = "GRV" },
    .{ .value = DOTA, .label = "DOTA", .short_label = "DOTA" },
    .{ .value = DACU, .label = "DACU", .short_label = "DACU" },
    .{ .value = DIAE, .label = "DIAE", .short_label = "DIAE" },
    .{ .value = CEDL, .label = "CEDL", .short_label = "CEDL" },
    .{ .value = BSLS, .label = "BSLS", .short_label = "BSLS" },
    .{ .value = PIPE, .label = "PIPE", .short_label = "PIPE" },
    .{ .value = EURO, .label = "EURO", .short_label = "EURO" },
    .{ .value = QUOT, .label = "QUOT", .short_label = "QUOT" },
    .{ .value = DIV, .label = "DIV", .short_label = "DIV" },
    .{ .value = MUL, .label = "MUL", .short_label = "MUL" },
    .{ .value = LDST, .label = "LDST", .short_label = "LDST" },
    .{ .value = CDST, .label = "CDST", .short_label = "CDST" },
    .{ .value = LBRC, .label = "LBRC", .short_label = "LBRC" },
    .{ .value = RBRC, .label = "RBRC", .short_label = "RBRC" },
    .{ .value = LLST, .label = "LLST", .short_label = "LLST" },
    .{ .value = CLST, .label = "CLST", .short_label = "CLST" },
    .{ .value = DLR, .label = "DLR", .short_label = "DLR" },
    .{ .value = SS, .label = "SS", .short_label = "SS" },
    .{ .value = CURR, .label = "CURR", .short_label = "CURR" },
    .{ .value = LABK, .label = "LABK", .short_label = "LABK" },
    .{ .value = RABK, .label = "RABK", .short_label = "RABK" },
    .{ .value = HASH, .label = "HASH", .short_label = "HASH" },
    .{ .value = AT, .label = "AT", .short_label = "AT" },
    .{ .value = LCBR, .label = "LCBR", .short_label = "LCBR" },
    .{ .value = RCBR, .label = "RCBR", .short_label = "RCBR" },
};

pub fn getLabel(keycode: core.KeyCodeFire, shortest: bool) ?[]const u8 {
    return zkc_core.getLabel(&_labels, keycode, shortest);
}
