// Copyright 2026 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by zkeycodes from QMK hjson keycode files
const zkc_core = @import("../src/core.zig");
const core = @import("zigmkay").core;
const L_SFT = zkc_core.L_SFT;
const L_ALT = zkc_core.L_ALT;
const R_ALT = zkc_core.R_ALT;
const R_CTL = zkc_core.R_CTL;
const DEAD = zkc_core.DEAD;
pub const keycodes = @import("keycodes.zig");

pub const QMK_SPANISH_DVORAK_KEYCODES_VERSION = "0.0.1";
pub const QMK_SPANISH_DVORAK_KEYCODES_VERSION_BCD = @as(c_int, 0x00000001);
pub const QMK_SPANISH_DVORAK_KEYCODES_VERSION_MAJOR = @as(c_int, 0);
pub const QMK_SPANISH_DVORAK_KEYCODES_VERSION_MINOR = @as(c_int, 0);
pub const QMK_SPANISH_DVORAK_KEYCODES_VERSION_PATCH = @as(c_int, 1);

//
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ º │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ ' │ ¡ │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ . │ , │ Ñ │ P │ Y │ F │ G │ C │ H │ L │ ` │ + │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │ A │ O │ E │ U │ I │ D │ R │ T │ N │ S │ ´ │ Ç │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ < │ - │ Q │ J │ K │ X │ B │ M │ W │ V │ Z │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// º
pub const MORD = keycodes.kcf.GRV;
/// 1
pub const N1 = keycodes.kcf.N1;
/// 2
pub const N2 = keycodes.kcf.N2;
/// 3
pub const N3 = keycodes.kcf.N3;
/// 4
pub const N4 = keycodes.kcf.N4;
/// 5
pub const N5 = keycodes.kcf.N5;
/// 6
pub const N6 = keycodes.kcf.N6;
/// 7
pub const N7 = keycodes.kcf.N7;
/// 8
pub const N8 = keycodes.kcf.N8;
/// 9
pub const N9 = keycodes.kcf.N9;
/// 0
pub const N0 = keycodes.kcf.N0;
/// '
pub const QUOT = keycodes.kcf.MINS;
/// ¡
pub const IEXL = keycodes.kcf.EQL;
/// .
pub const DOT = keycodes.kcf.Q;
/// ,
pub const COMM = keycodes.kcf.W;
/// Ñ
pub const NTIL = keycodes.kcf.E;
/// P
pub const P = keycodes.kcf.R;
/// Y
pub const Y = keycodes.kcf.T;
/// F
pub const F = keycodes.kcf.Y;
/// G
pub const G = keycodes.kcf.U;
/// C
pub const C = keycodes.kcf.I;
/// H
pub const H = keycodes.kcf.O;
/// L
pub const L = keycodes.kcf.P;
/// ` (dead)
pub const GRV = DEAD(keycodes.kcf.LBRC);
/// +
pub const PLUS = keycodes.kcf.RBRC;
/// A
pub const A = keycodes.kcf.A;
/// O
pub const O = keycodes.kcf.S;
/// E
pub const E = keycodes.kcf.D;
/// U
pub const U = keycodes.kcf.F;
/// I
pub const I = keycodes.kcf.G;
/// D
pub const D = keycodes.kcf.H;
/// R
pub const R = keycodes.kcf.J;
/// T
pub const T = keycodes.kcf.K;
/// N
pub const N = keycodes.kcf.L;
/// S
pub const S = keycodes.kcf.SCLN;
/// ´ (dead)
pub const ACUT = DEAD(keycodes.kcf.QUOT);
/// Ç
pub const CCED = keycodes.kcf.NUHS;
/// <
pub const LABK = keycodes.kcf.NUBS;
/// -
pub const MINS = keycodes.kcf.Z;
/// Q
pub const Q = keycodes.kcf.X;
/// J
pub const J = keycodes.kcf.C;
/// K
pub const K = keycodes.kcf.V;
/// X
pub const X = keycodes.kcf.B;
/// B
pub const B = keycodes.kcf.N;
/// M
pub const M = keycodes.kcf.M;
/// W
pub const W = keycodes.kcf.COMM;
/// V
pub const V = keycodes.kcf.DOT;
/// Z
pub const Z = keycodes.kcf.SLSH;
// Shifted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ª │ ! │ " │ · │ $ │ % │ & │ / │ ( │ ) │ = │ ? │ ¿ │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ : │ ; │   │   │   │   │   │   │   │   │ ^ │ * │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │   │   │   │   │   │   │   │   │   │   │ ¨ │   │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ > │ _ │   │   │   │   │   │   │   │   │   │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ª
pub const FORD = L_SFT(MORD);
/// !
pub const EXLM = L_SFT(N1);
/// "
pub const DQUO = L_SFT(N2);
/// ·
pub const BULT = L_SFT(N3);
/// $
pub const DLR = L_SFT(N4);
/// %
pub const PERC = L_SFT(N5);
/// &
pub const AMPR = L_SFT(N6);
/// /
pub const SLSH = L_SFT(N7);
/// (
pub const LPRN = L_SFT(N8);
/// )
pub const RPRN = L_SFT(N9);
/// =
pub const EQL = L_SFT(N0);
/// ?
pub const QUES = L_SFT(QUOT);
/// ¿
pub const IQUE = L_SFT(IEXL);
/// :
pub const COLN = L_SFT(DOT);
/// ;
pub const SCLN = L_SFT(COMM);
/// ^ (dead)
pub const CIRC = DEAD(L_SFT(GRV));
/// *
pub const ASTR = L_SFT(PLUS);
/// ¨ (dead)
pub const DIAE = DEAD(L_SFT(ACUT));
/// >
pub const RABK = L_SFT(LABK);
/// _
pub const UNDS = L_SFT(MINS);
// AltGr symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ \ │ | │ @ │ # │ ~ │ € │ ¬ │   │   │   │   │   │   │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │   │   │   │   │   │   │   │   │ [ │ ] │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │   │   │   │   │   │   │   │   │   │   │ { │ } │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │   │   │   │   │   │   │   │   │   │   │   │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// (backslash)
pub const BSLS = R_ALT(MORD);
/// |
pub const PIPE = R_ALT(N1);
/// @
pub const AT = R_ALT(N2);
/// #
pub const HASH = R_ALT(N3);
/// ~
pub const TILD = R_ALT(N4);
/// €
pub const EURO = R_ALT(N5);
/// ¬
pub const NOT = R_ALT(N6);
/// [
pub const LBRC = R_ALT(GRV);
/// ]
pub const RBRC = R_ALT(PLUS);
/// {
pub const LCBR = R_ALT(ACUT);
/// }
pub const RCBR = R_ALT(CCED);

// Label lookup table
pub const _labels = [_]zkc_core.LabelEntry{
    .{ .value = MORD, .label = "MORD", .short_label = "MORD" },
    .{ .value = N1, .label = "1", .short_label = "1" },
    .{ .value = N2, .label = "2", .short_label = "2" },
    .{ .value = N3, .label = "3", .short_label = "3" },
    .{ .value = N4, .label = "4", .short_label = "4" },
    .{ .value = N5, .label = "5", .short_label = "5" },
    .{ .value = N6, .label = "6", .short_label = "6" },
    .{ .value = N7, .label = "7", .short_label = "7" },
    .{ .value = N8, .label = "8", .short_label = "8" },
    .{ .value = N9, .label = "9", .short_label = "9" },
    .{ .value = N0, .label = "0", .short_label = "0" },
    .{ .value = QUOT, .label = "QUOT", .short_label = "QUOT" },
    .{ .value = IEXL, .label = "IEXL", .short_label = "IEXL" },
    .{ .value = DOT, .label = "DOT", .short_label = "DOT" },
    .{ .value = COMM, .label = "COMM", .short_label = "COMM" },
    .{ .value = NTIL, .label = "NTIL", .short_label = "NTIL" },
    .{ .value = P, .label = "P", .short_label = "P" },
    .{ .value = Y, .label = "Y", .short_label = "Y" },
    .{ .value = F, .label = "F", .short_label = "F" },
    .{ .value = G, .label = "G", .short_label = "G" },
    .{ .value = C, .label = "C", .short_label = "C" },
    .{ .value = H, .label = "H", .short_label = "H" },
    .{ .value = L, .label = "L", .short_label = "L" },
    .{ .value = GRV, .label = "GRV", .short_label = "GRV" },
    .{ .value = PLUS, .label = "PLUS", .short_label = "PLUS" },
    .{ .value = A, .label = "A", .short_label = "A" },
    .{ .value = O, .label = "O", .short_label = "O" },
    .{ .value = E, .label = "E", .short_label = "E" },
    .{ .value = U, .label = "U", .short_label = "U" },
    .{ .value = I, .label = "I", .short_label = "I" },
    .{ .value = D, .label = "D", .short_label = "D" },
    .{ .value = R, .label = "R", .short_label = "R" },
    .{ .value = T, .label = "T", .short_label = "T" },
    .{ .value = N, .label = "N", .short_label = "N" },
    .{ .value = S, .label = "S", .short_label = "S" },
    .{ .value = ACUT, .label = "ACUT", .short_label = "ACUT" },
    .{ .value = CCED, .label = "CCED", .short_label = "CCED" },
    .{ .value = LABK, .label = "LABK", .short_label = "LABK" },
    .{ .value = MINS, .label = "MINS", .short_label = "MINS" },
    .{ .value = Q, .label = "Q", .short_label = "Q" },
    .{ .value = J, .label = "J", .short_label = "J" },
    .{ .value = K, .label = "K", .short_label = "K" },
    .{ .value = X, .label = "X", .short_label = "X" },
    .{ .value = B, .label = "B", .short_label = "B" },
    .{ .value = M, .label = "M", .short_label = "M" },
    .{ .value = W, .label = "W", .short_label = "W" },
    .{ .value = V, .label = "V", .short_label = "V" },
    .{ .value = Z, .label = "Z", .short_label = "Z" },
    .{ .value = FORD, .label = "FORD", .short_label = "FORD" },
    .{ .value = EXLM, .label = "EXLM", .short_label = "EXLM" },
    .{ .value = DQUO, .label = "DQUO", .short_label = "DQUO" },
    .{ .value = BULT, .label = "BULT", .short_label = "BULT" },
    .{ .value = DLR, .label = "DLR", .short_label = "DLR" },
    .{ .value = PERC, .label = "PERC", .short_label = "PERC" },
    .{ .value = AMPR, .label = "AMPR", .short_label = "AMPR" },
    .{ .value = SLSH, .label = "SLSH", .short_label = "SLSH" },
    .{ .value = LPRN, .label = "LPRN", .short_label = "LPRN" },
    .{ .value = RPRN, .label = "RPRN", .short_label = "RPRN" },
    .{ .value = EQL, .label = "EQL", .short_label = "EQL" },
    .{ .value = QUES, .label = "QUES", .short_label = "QUES" },
    .{ .value = IQUE, .label = "IQUE", .short_label = "IQUE" },
    .{ .value = COLN, .label = "COLN", .short_label = "COLN" },
    .{ .value = SCLN, .label = "SCLN", .short_label = "SCLN" },
    .{ .value = CIRC, .label = "CIRC", .short_label = "CIRC" },
    .{ .value = ASTR, .label = "ASTR", .short_label = "ASTR" },
    .{ .value = DIAE, .label = "DIAE", .short_label = "DIAE" },
    .{ .value = RABK, .label = "RABK", .short_label = "RABK" },
    .{ .value = UNDS, .label = "UNDS", .short_label = "UNDS" },
    .{ .value = BSLS, .label = "BSLS", .short_label = "BSLS" },
    .{ .value = PIPE, .label = "PIPE", .short_label = "PIPE" },
    .{ .value = AT, .label = "AT", .short_label = "AT" },
    .{ .value = HASH, .label = "HASH", .short_label = "HASH" },
    .{ .value = TILD, .label = "TILD", .short_label = "TILD" },
    .{ .value = EURO, .label = "EURO", .short_label = "EURO" },
    .{ .value = NOT, .label = "NOT", .short_label = "NOT" },
    .{ .value = LBRC, .label = "LBRC", .short_label = "LBRC" },
    .{ .value = RBRC, .label = "RBRC", .short_label = "RBRC" },
    .{ .value = LCBR, .label = "LCBR", .short_label = "LCBR" },
    .{ .value = RCBR, .label = "RCBR", .short_label = "RCBR" },
};

pub fn getLabel(keycode: core.KeyCodeFire, shortest: bool) ?[]const u8 {
    return zkc_core.getLabel(&_labels, keycode, shortest);
}
