// Copyright 2026 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by zkeycodes from QMK hjson keycode files
const zkc_core = @import("../src/core.zig");
const core = @import("zigmkay").core;
const L_SFT = zkc_core.L_SFT;
const L_ALT = zkc_core.L_ALT;
const R_ALT = zkc_core.R_ALT;
const R_CTL = zkc_core.R_CTL;
const DEAD = zkc_core.DEAD;
pub const keycodes = @import("keycodes.zig");

pub const QMK_TURKISH_F_KEYCODES_VERSION = "0.0.1";
pub const QMK_TURKISH_F_KEYCODES_VERSION_BCD = @as(c_int, 0x00000001);
pub const QMK_TURKISH_F_KEYCODES_VERSION_MAJOR = @as(c_int, 0);
pub const QMK_TURKISH_F_KEYCODES_VERSION_MINOR = @as(c_int, 0);
pub const QMK_TURKISH_F_KEYCODES_VERSION_PATCH = @as(c_int, 1);

//
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ + │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ / │ - │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ F │ G │ Ğ │ I │ O │ D │ R │ N │ H │ P │ Q │ W │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │ U │ İ │ E │ A │ Ü │ T │ K │ M │ L │ Y │ Ş │ X │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ < │ J │ Ö │ V │ C │ Ç │ Z │ S │ B │ . │ , │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// +
pub const PLUS = keycodes.kcf.GRV;
/// 1
pub const N1 = keycodes.kcf.N1;
/// 2
pub const N2 = keycodes.kcf.N2;
/// 3
pub const N3 = keycodes.kcf.N3;
/// 4
pub const N4 = keycodes.kcf.N4;
/// 5
pub const N5 = keycodes.kcf.N5;
/// 6
pub const N6 = keycodes.kcf.N6;
/// 7
pub const N7 = keycodes.kcf.N7;
/// 8
pub const N8 = keycodes.kcf.N8;
/// 9
pub const N9 = keycodes.kcf.N9;
/// 0
pub const N0 = keycodes.kcf.N0;
/// /
pub const SLSH = keycodes.kcf.MINS;
/// -
pub const MINS = keycodes.kcf.EQL;
/// F
pub const F = keycodes.kcf.Q;
/// G
pub const G = keycodes.kcf.W;
/// Ğ
pub const GBRV = keycodes.kcf.E;
/// I
pub const I = keycodes.kcf.R;
/// O
pub const O = keycodes.kcf.T;
/// D
pub const D = keycodes.kcf.Y;
/// R
pub const R = keycodes.kcf.U;
/// N
pub const N = keycodes.kcf.I;
/// H
pub const H = keycodes.kcf.O;
/// P
pub const P = keycodes.kcf.P;
/// Q
pub const Q = keycodes.kcf.LBRC;
/// W
pub const W = keycodes.kcf.RBRC;
/// U
pub const U = keycodes.kcf.A;
/// İ
pub const IDOT = keycodes.kcf.S;
/// E
pub const E = keycodes.kcf.D;
/// A
pub const A = keycodes.kcf.F;
/// Ü
pub const UDIA = keycodes.kcf.G;
/// T
pub const T = keycodes.kcf.H;
/// K
pub const K = keycodes.kcf.J;
/// M
pub const M = keycodes.kcf.K;
/// L
pub const L = keycodes.kcf.L;
/// Y
pub const Y = keycodes.kcf.SCLN;
/// Ş
pub const SCED = keycodes.kcf.QUOT;
/// X
pub const X = keycodes.kcf.NUHS;
/// <
pub const LABK = keycodes.kcf.NUBS;
/// J
pub const J = keycodes.kcf.Z;
/// Ö
pub const ODIA = keycodes.kcf.X;
/// V
pub const V = keycodes.kcf.C;
/// C
pub const C = keycodes.kcf.V;
/// Ç
pub const CCED = keycodes.kcf.B;
/// Z
pub const Z = keycodes.kcf.N;
/// S
pub const S = keycodes.kcf.M;
/// B
pub const B = keycodes.kcf.COMM;
/// .
pub const DOT = keycodes.kcf.DOT;
/// ,
pub const COMM = keycodes.kcf.SLSH;
// Shifted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ * │ ! │ " │ ^ │ $ │ % │ & │ ' │ ( │ ) │ = │ ? │ _ │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │   │   │   │   │   │   │   │   │   │   │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │   │   │   │   │   │   │   │   │   │   │   │   │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ > │   │   │   │   │   │   │   │   │ : │ ; │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// *
pub const ASTR = L_SFT(PLUS);
/// !
pub const EXLM = L_SFT(N1);
/// "
pub const DQUO = L_SFT(N2);
/// ^ (dead)
pub const CIRC = DEAD(L_SFT(N3));
/// $
pub const DLR = L_SFT(N4);
/// %
pub const PERC = L_SFT(N5);
/// &
pub const AMPR = L_SFT(N6);
/// '
pub const QUOT = L_SFT(N7);
/// (
pub const LPRN = L_SFT(N8);
/// )
pub const RPRN = L_SFT(N9);
/// =
pub const EQL = L_SFT(N0);
/// ?
pub const QUES = L_SFT(SLSH);
/// _
pub const UNDS = L_SFT(MINS);
/// >
pub const RABK = L_SFT(LABK);
/// :
pub const COLN = L_SFT(DOT);
/// ;
pub const SCLN = L_SFT(COMM);
// AltGr symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ¬ │ ¹ │ ² │ # │ ¼ │ ½ │ ¾ │ { │ [ │ ] │ } │ \ │ | │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ @ │   │   │ ¶ │   │ ¥ │   │   │ Ø │ £ │ ¨ │ ~ │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │ Æ │ ß │ € │   │   │ ₺ │   │   │   │ ´ │   │ ` │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │   │ « │ » │ ¢ │   │   │   │ µ │ × │ ÷ │ - │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ¬
pub const NOT = R_ALT(PLUS);
/// ¹
pub const SUP1 = R_ALT(N1);
/// ²
pub const SUP2 = R_ALT(N2);
/// #
pub const HASH = R_ALT(N3);
/// ¼
pub const QRTR = R_ALT(N4);
/// ½
pub const HALF = R_ALT(N5);
/// ¾
pub const TQTR = R_ALT(N6);
/// {
pub const LCBR = R_ALT(N7);
/// [
pub const LBRC = R_ALT(N8);
/// ]
pub const RBRC = R_ALT(N9);
/// }
pub const RCBR = R_ALT(N0);
/// (backslash)
pub const BSLS = R_ALT(SLSH);
/// |
pub const PIPE = R_ALT(MINS);
/// @
pub const AT = R_ALT(F);
/// ¶
pub const PILC = R_ALT(I);
/// ¥
pub const YEN = R_ALT(D);
/// Ø
pub const OSTR = R_ALT(H);
/// £
pub const PND = R_ALT(P);
/// ¨ (dead)
pub const DIAE = DEAD(R_ALT(Q));
/// ~ (dead)
pub const TILD = DEAD(R_ALT(W));
/// Æ
pub const AE = R_ALT(U);
/// ß
pub const SS = R_ALT(IDOT);
/// €
pub const EURO = R_ALT(E);
/// ₺
pub const LIRA = R_ALT(T);
/// ´ (dead)
pub const ACUT = DEAD(R_ALT(Y));
/// ` (dead)
pub const GRV = DEAD(R_ALT(X));
/// «
pub const LDAQ = R_ALT(J);
/// »
pub const RDAQ = R_ALT(ODIA);
/// ¢
pub const CENT = R_ALT(V);
/// µ
pub const MICR = R_ALT(S);
/// ×
pub const MUL = R_ALT(B);
/// ÷
pub const DIV = R_ALT(DOT);
/// ­ (soft hyphen)
pub const SHYP = R_ALT(COMM);
// Shift+AltGr symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │   │   │   │ ³ │ ¤ │   │   │   │   │   │   │ ¿ │   │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │   │ ® │   │   │   │   │   │   │   │   │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
// │      │   │ § │   │ ª │   │   │   │   │   │   │   │   │    │
// ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
// │    │ ¦ │   │   │ © │   │   │   │ º │   │   │   │          │
// ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ³
pub const SUP3 = L_SFT(R_ALT(N3));
/// ¤
pub const CURR = L_SFT(R_ALT(N4));
/// ¿
pub const IQUE = L_SFT(R_ALT(SLSH));
/// ®
pub const REGD = L_SFT(R_ALT(I));
/// §
pub const SECT = L_SFT(R_ALT(IDOT));
/// ª
pub const FORD = L_SFT(R_ALT(A));
/// ¦
pub const BRKP = L_SFT(R_ALT(LABK));
/// ©
pub const COPY = L_SFT(R_ALT(V));
/// º
pub const MORD = L_SFT(R_ALT(S));

// Label lookup table
pub const _labels = [_]zkc_core.LabelEntry{
    .{ .value = PLUS, .label = "PLUS", .short_label = "PLUS" },
    .{ .value = N1, .label = "1", .short_label = "1" },
    .{ .value = N2, .label = "2", .short_label = "2" },
    .{ .value = N3, .label = "3", .short_label = "3" },
    .{ .value = N4, .label = "4", .short_label = "4" },
    .{ .value = N5, .label = "5", .short_label = "5" },
    .{ .value = N6, .label = "6", .short_label = "6" },
    .{ .value = N7, .label = "7", .short_label = "7" },
    .{ .value = N8, .label = "8", .short_label = "8" },
    .{ .value = N9, .label = "9", .short_label = "9" },
    .{ .value = N0, .label = "0", .short_label = "0" },
    .{ .value = SLSH, .label = "SLSH", .short_label = "SLSH" },
    .{ .value = MINS, .label = "MINS", .short_label = "MINS" },
    .{ .value = F, .label = "F", .short_label = "F" },
    .{ .value = G, .label = "G", .short_label = "G" },
    .{ .value = GBRV, .label = "GBRV", .short_label = "GBRV" },
    .{ .value = I, .label = "I", .short_label = "I" },
    .{ .value = O, .label = "O", .short_label = "O" },
    .{ .value = D, .label = "D", .short_label = "D" },
    .{ .value = R, .label = "R", .short_label = "R" },
    .{ .value = N, .label = "N", .short_label = "N" },
    .{ .value = H, .label = "H", .short_label = "H" },
    .{ .value = P, .label = "P", .short_label = "P" },
    .{ .value = Q, .label = "Q", .short_label = "Q" },
    .{ .value = W, .label = "W", .short_label = "W" },
    .{ .value = U, .label = "U", .short_label = "U" },
    .{ .value = IDOT, .label = "IDOT", .short_label = "IDOT" },
    .{ .value = E, .label = "E", .short_label = "E" },
    .{ .value = A, .label = "A", .short_label = "A" },
    .{ .value = UDIA, .label = "UDIA", .short_label = "UDIA" },
    .{ .value = T, .label = "T", .short_label = "T" },
    .{ .value = K, .label = "K", .short_label = "K" },
    .{ .value = M, .label = "M", .short_label = "M" },
    .{ .value = L, .label = "L", .short_label = "L" },
    .{ .value = Y, .label = "Y", .short_label = "Y" },
    .{ .value = SCED, .label = "SCED", .short_label = "SCED" },
    .{ .value = X, .label = "X", .short_label = "X" },
    .{ .value = LABK, .label = "LABK", .short_label = "LABK" },
    .{ .value = J, .label = "J", .short_label = "J" },
    .{ .value = ODIA, .label = "ODIA", .short_label = "ODIA" },
    .{ .value = V, .label = "V", .short_label = "V" },
    .{ .value = C, .label = "C", .short_label = "C" },
    .{ .value = CCED, .label = "CCED", .short_label = "CCED" },
    .{ .value = Z, .label = "Z", .short_label = "Z" },
    .{ .value = S, .label = "S", .short_label = "S" },
    .{ .value = B, .label = "B", .short_label = "B" },
    .{ .value = DOT, .label = "DOT", .short_label = "DOT" },
    .{ .value = COMM, .label = "COMM", .short_label = "COMM" },
    .{ .value = ASTR, .label = "ASTR", .short_label = "ASTR" },
    .{ .value = EXLM, .label = "EXLM", .short_label = "EXLM" },
    .{ .value = DQUO, .label = "DQUO", .short_label = "DQUO" },
    .{ .value = CIRC, .label = "CIRC", .short_label = "CIRC" },
    .{ .value = DLR, .label = "DLR", .short_label = "DLR" },
    .{ .value = PERC, .label = "PERC", .short_label = "PERC" },
    .{ .value = AMPR, .label = "AMPR", .short_label = "AMPR" },
    .{ .value = QUOT, .label = "QUOT", .short_label = "QUOT" },
    .{ .value = LPRN, .label = "LPRN", .short_label = "LPRN" },
    .{ .value = RPRN, .label = "RPRN", .short_label = "RPRN" },
    .{ .value = EQL, .label = "EQL", .short_label = "EQL" },
    .{ .value = QUES, .label = "QUES", .short_label = "QUES" },
    .{ .value = UNDS, .label = "UNDS", .short_label = "UNDS" },
    .{ .value = RABK, .label = "RABK", .short_label = "RABK" },
    .{ .value = COLN, .label = "COLN", .short_label = "COLN" },
    .{ .value = SCLN, .label = "SCLN", .short_label = "SCLN" },
    .{ .value = NOT, .label = "NOT", .short_label = "NOT" },
    .{ .value = SUP1, .label = "SUP1", .short_label = "SUP1" },
    .{ .value = SUP2, .label = "SUP2", .short_label = "SUP2" },
    .{ .value = HASH, .label = "HASH", .short_label = "HASH" },
    .{ .value = QRTR, .label = "QRTR", .short_label = "QRTR" },
    .{ .value = HALF, .label = "HALF", .short_label = "HALF" },
    .{ .value = TQTR, .label = "TQTR", .short_label = "TQTR" },
    .{ .value = LCBR, .label = "LCBR", .short_label = "LCBR" },
    .{ .value = LBRC, .label = "LBRC", .short_label = "LBRC" },
    .{ .value = RBRC, .label = "RBRC", .short_label = "RBRC" },
    .{ .value = RCBR, .label = "RCBR", .short_label = "RCBR" },
    .{ .value = BSLS, .label = "BSLS", .short_label = "BSLS" },
    .{ .value = PIPE, .label = "PIPE", .short_label = "PIPE" },
    .{ .value = AT, .label = "AT", .short_label = "AT" },
    .{ .value = PILC, .label = "PILC", .short_label = "PILC" },
    .{ .value = YEN, .label = "YEN", .short_label = "YEN" },
    .{ .value = OSTR, .label = "OSTR", .short_label = "OSTR" },
    .{ .value = PND, .label = "PND", .short_label = "PND" },
    .{ .value = DIAE, .label = "DIAE", .short_label = "DIAE" },
    .{ .value = TILD, .label = "TILD", .short_label = "TILD" },
    .{ .value = AE, .label = "AE", .short_label = "AE" },
    .{ .value = SS, .label = "SS", .short_label = "SS" },
    .{ .value = EURO, .label = "EURO", .short_label = "EURO" },
    .{ .value = LIRA, .label = "LIRA", .short_label = "LIRA" },
    .{ .value = ACUT, .label = "ACUT", .short_label = "ACUT" },
    .{ .value = GRV, .label = "GRV", .short_label = "GRV" },
    .{ .value = LDAQ, .label = "LDAQ", .short_label = "LDAQ" },
    .{ .value = RDAQ, .label = "RDAQ", .short_label = "RDAQ" },
    .{ .value = CENT, .label = "CENT", .short_label = "CENT" },
    .{ .value = MICR, .label = "MICR", .short_label = "MICR" },
    .{ .value = MUL, .label = "MUL", .short_label = "MUL" },
    .{ .value = DIV, .label = "DIV", .short_label = "DIV" },
    .{ .value = SHYP, .label = "SHYP", .short_label = "SHYP" },
    .{ .value = SUP3, .label = "SUP3", .short_label = "SUP3" },
    .{ .value = CURR, .label = "CURR", .short_label = "CURR" },
    .{ .value = IQUE, .label = "IQUE", .short_label = "IQUE" },
    .{ .value = REGD, .label = "REGD", .short_label = "REGD" },
    .{ .value = SECT, .label = "SECT", .short_label = "SECT" },
    .{ .value = FORD, .label = "FORD", .short_label = "FORD" },
    .{ .value = BRKP, .label = "BRKP", .short_label = "BRKP" },
    .{ .value = COPY, .label = "COPY", .short_label = "COPY" },
    .{ .value = MORD, .label = "MORD", .short_label = "MORD" },
};

pub fn getLabel(keycode: core.KeyCodeFire, shortest: bool) ?[]const u8 {
    return zkc_core.getLabel(&_labels, keycode, shortest);
}
