// Copyright 2026 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by zkeycodes from QMK hjson keycode files
const zkc_core = @import("../src/core.zig");
const core = @import("zigmkay").core;
const L_SFT = zkc_core.L_SFT;
const L_ALT = zkc_core.L_ALT;
const R_ALT = zkc_core.R_ALT;
const R_CTL = zkc_core.R_CTL;
const DEAD = zkc_core.DEAD;
pub const keycodes = @import("keycodes.zig");

pub const QMK_US_KEYCODES_VERSION = "0.0.1";
pub const QMK_US_KEYCODES_VERSION_BCD = @as(c_int, 0x00000001);
pub const QMK_US_KEYCODES_VERSION_MAJOR = @as(c_int, 0);
pub const QMK_US_KEYCODES_VERSION_MINOR = @as(c_int, 0);
pub const QMK_US_KEYCODES_VERSION_PATCH = @as(c_int, 1);

// Shifted symbols
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │ ~ │ ! │ @ │ # │ $ │ % │ ^ │ & │ * │ ( │ ) │ _ │ + │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │   │   │   │   │   │   │   │   │   │   │ { │ } │  |  │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
// │      │   │   │   │   │   │   │   │   │   │ : │ " │        │
// ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
// │        │   │   │   │   │   │   │   │ < │ > │ ? │          │
// ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
/// ~
pub const TILD = L_SFT(keycodes.kcf.GRAVE);
/// !
pub const EXLM = L_SFT(keycodes.kcf.N1);
/// @
pub const AT = L_SFT(keycodes.kcf.N2);
/// #
pub const HASH = L_SFT(keycodes.kcf.N3);
/// $
pub const DLR = L_SFT(keycodes.kcf.N4);
/// %
pub const PERC = L_SFT(keycodes.kcf.N5);
/// ^
pub const CIRC = L_SFT(keycodes.kcf.N6);
/// &
pub const AMPR = L_SFT(keycodes.kcf.N7);
/// *
pub const ASTR = L_SFT(keycodes.kcf.N8);
/// (
pub const LPRN = L_SFT(keycodes.kcf.N9);
/// )
pub const RPRN = L_SFT(keycodes.kcf.N0);
/// _
pub const UNDS = L_SFT(keycodes.kcf.MINUS);
/// +
pub const PLUS = L_SFT(keycodes.kcf.EQUAL);
/// {
pub const LCBR = L_SFT(keycodes.kcf.LEFT_BRACKET);
/// }
pub const RCBR = L_SFT(keycodes.kcf.RIGHT_BRACKET);
/// |
pub const PIPE = L_SFT(keycodes.kcf.BACKSLASH);
/// :
pub const COLN = L_SFT(keycodes.kcf.SEMICOLON);
/// "
pub const DQUO = L_SFT(keycodes.kcf.QUOTE);
/// <
pub const LABK = L_SFT(keycodes.kcf.COMMA);
/// >
pub const RABK = L_SFT(keycodes.kcf.DOT);
/// ?
pub const QUES = L_SFT(keycodes.kcf.SLASH);

// Label lookup table
pub const _labels = [_]zkc_core.LabelEntry{
    .{ .value = TILD, .label = "TILD", .short_label = "TILD" },
    .{ .value = EXLM, .label = "EXLM", .short_label = "EXLM" },
    .{ .value = AT, .label = "AT", .short_label = "AT" },
    .{ .value = HASH, .label = "HASH", .short_label = "HASH" },
    .{ .value = DLR, .label = "DLR", .short_label = "DLR" },
    .{ .value = PERC, .label = "PERC", .short_label = "PERC" },
    .{ .value = CIRC, .label = "CIRC", .short_label = "CIRC" },
    .{ .value = AMPR, .label = "AMPR", .short_label = "AMPR" },
    .{ .value = ASTR, .label = "ASTR", .short_label = "ASTR" },
    .{ .value = LPRN, .label = "LPRN", .short_label = "LPRN" },
    .{ .value = RPRN, .label = "RPRN", .short_label = "RPRN" },
    .{ .value = UNDS, .label = "UNDS", .short_label = "UNDS" },
    .{ .value = PLUS, .label = "PLUS", .short_label = "PLUS" },
    .{ .value = LCBR, .label = "LCBR", .short_label = "LCBR" },
    .{ .value = RCBR, .label = "RCBR", .short_label = "RCBR" },
    .{ .value = PIPE, .label = "PIPE", .short_label = "PIPE" },
    .{ .value = COLN, .label = "COLN", .short_label = "COLN" },
    .{ .value = DQUO, .label = "DQUO", .short_label = "DQUO" },
    .{ .value = LABK, .label = "LABK", .short_label = "LABK" },
    .{ .value = RABK, .label = "RABK", .short_label = "RABK" },
    .{ .value = QUES, .label = "QUES", .short_label = "QUES" },
};

pub fn getLabel(keycode: core.KeyCodeFire, shortest: bool) ?[]const u8 {
    return zkc_core.getLabel(&_labels, keycode, shortest);
}
